# Generated by Django 3.2.8 on 2023-03-18 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('completed', 'Completed')], default='todo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Assign On')),
                ('duty', models.TextField(blank=True, max_length=500, null=True, verbose_name='Job description')),
                ('is_assigned', models.BooleanField(choices=[(False, 'Unassigned'), (True, 'Assigned')], default=False)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to=settings.AUTH_USER_MODEL, verbose_name='Assignee')),
                ('assignor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignors', to=settings.AUTH_USER_MODEL, verbose_name='Assignor')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignproposal', to='proposals.proposal', verbose_name='Proposal')),
            ],
            options={
                'verbose_name': 'Assign Member',
                'verbose_name_plural': 'Assign Member',
                'ordering': ('-modified',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('notice', models.TextField(max_length=500, verbose_name='Notice')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20, verbose_name='Team Status')),
                ('package_status', models.CharField(choices=[('default', 'Default'), ('active', 'Active')], default='default', max_length=20, verbose_name='Package Status')),
                ('package_expiry', models.DateTimeField(blank=True, null=True, verbose_name='Package Expiry Date')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('team_balance', models.PositiveIntegerField(default=0, help_text='Team Transaction Balance', verbose_name='Team Balance')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Customer ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Subscription ID')),
                ('paypal_customer_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Paypal Customer ID')),
                ('paypal_subscription_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Paypal Subscription ID')),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razorpay Payment ID')),
                ('razorpay_subscription_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razorpay Subscription ID')),
                ('razorpay_payment_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razorpay Short_Link')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammanager', to=settings.AUTH_USER_MODEL, verbose_name='Team Founder')),
                ('members', models.ManyToManyField(related_name='team_member', to=settings.AUTH_USER_MODEL, verbose_name='Team Members')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teammerchant', to='account.merchant', verbose_name='Merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.TextField(blank=True, max_length=200, null=True, verbose_name='Task description')),
                ('is_tracked', models.BooleanField(choices=[(False, 'untracked'), (True, 'Tracked')], default=False)),
                ('minutes', models.PositiveIntegerField(default=0, verbose_name='Time Tracked')),
                ('created_at', models.DateTimeField()),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='teams.assignmember')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to=settings.AUTH_USER_MODEL, verbose_name='Assignee')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='proposals.proposal', verbose_name='Proposal')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamsender', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamchats', to='teams.team', verbose_name='Chat Team')),
            ],
            options={
                'ordering': ['sent_on'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='Code')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted')], default='invited', max_length=20, verbose_name='Status')),
                ('type', models.CharField(choices=[('founder', 'Founder'), ('internal', 'Internal'), ('external', 'External')], default='founder', max_length=20, verbose_name='Invite Type')),
                ('sent_on', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merchantinvite', to='account.merchant', verbose_name='Merchant')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='Receiver')),
                ('sender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='teams.team', verbose_name='Team')),
            ],
        ),
        migrations.AddField(
            model_name='assignmember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignteam', to='teams.team', verbose_name='Team'),
        ),
    ]
