# Generated by Django 4.1.9 on 2023-11-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='package',
            unique_together=set(),
        ),
    ]
