# Generated by Django 3.2.8 on 2023-04-24 20:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20230424_2021'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Basic', 'Basic'), ('Team', 'Subscription')], default='Basic', max_length=10, unique=True, verbose_name='Package Type')),
                ('max_member_per_team', models.PositiveIntegerField(default=0, verbose_name='Maximum Number Per Team')),
                ('max_invites_per_team', models.PositiveIntegerField(default=0, verbose_name='Maximum Invites Per Team')),
                ('max_proposals_allowable_per_team', models.PositiveIntegerField(default=0, verbose_name='Maximum Proposals Allowable Per Team')),
                ('max_projects_applicable_per_team', models.PositiveIntegerField(default=0, verbose_name='Maximum Projects Applicable Per Team')),
                ('max_tasks_applicable_per_team', models.PositiveIntegerField(default=0, verbose_name='Maximum Tasks Applicable Per Team')),
                ('max_proposals_per_project', models.PositiveIntegerField(default=0, verbose_name='Maximum Proposals Per Project')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Price')),
                ('is_default', models.BooleanField(default=False)),
                ('ordering', models.PositiveIntegerField(default=1, help_text='This determines how each package will appear to user eg, 1 means first position', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Display')),
            ],
            options={
                'verbose_name': 'Upsell Package',
                'verbose_name_plural': 'Upsell Packages',
                'ordering': ('-ordering',),
            },
        ),
        migrations.AlterField(
            model_name='team',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.merchant', verbose_name='Merchant'),
        ),
    ]
