# Generated by Django 4.1.9 on 2023-09-16 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_merchant_package_merchant_packages_and_more'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='merchant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='account.merchant', verbose_name='Merchant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.package', verbose_name='Team Plan'),
        ),
    ]
