# Generated by Django 3.2.8 on 2023-06-11 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_merchant_project_type'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmember',
            name='merchant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='account.merchant', verbose_name='Merchant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamchat',
            name='merchant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='account.merchant', verbose_name='Merchant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracking',
            name='merchant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='account.merchant', verbose_name='Merchant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitation',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.merchant', verbose_name='Merchant'),
        ),
    ]
