# Generated by Django 3.2.8 on 2022-06-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='razorpay_order_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razorpay Customer ID'),
        ),
        migrations.AddField(
            model_name='team',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razorpay Payment ID'),
        ),
        migrations.AddField(
            model_name='team',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razorpay Signature'),
        ),
    ]
