# Generated by Django 3.2.8 on 2022-06-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20220624_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='razorpay_payment_id',
        ),
        migrations.AddField(
            model_name='team',
            name='razorpay_payment_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razorpay Short_Link'),
        ),
    ]
