# Generated by Django 3.2.8 on 2023-06-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20230611_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='notice',
            field=models.TextField(max_length=2000, verbose_name='Notice'),
        ),
    ]
