# Generated by Django 4.1.9 on 2023-09-16 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_merchant_packages'),
        ('teams', '0002_package_merchant_alter_team_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmember',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.merchant', verbose_name='Merchant'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.merchant', verbose_name='Merchant'),
        ),
        migrations.AlterField(
            model_name='package',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.merchant', verbose_name='Merchant'),
        ),
        migrations.AlterField(
            model_name='team',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.merchant', verbose_name='Merchant'),
        ),
        migrations.AlterField(
            model_name='teamchat',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.merchant', verbose_name='Merchant'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.merchant', verbose_name='Merchant'),
        ),
    ]
