# Generated by Django 4.1.9 on 2023-11-16 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_package_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.package', verbose_name='Team Plan'),
        ),
    ]
