# Generated by Django 3.2.8 on 2023-04-24 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20230424_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='is_default',
        ),
    ]
