# Generated by Django 4.1.9 on 2023-08-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_assignmember_site_invitation_site_team_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmember',
            name='site',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='site',
        ),
        migrations.RemoveField(
            model_name='team',
            name='site',
        ),
        migrations.RemoveField(
            model_name='teamchat',
            name='site',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='site',
        ),
    ]
