# Generated by Django 4.1.9 on 2023-09-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_merchant_packages'),
        ('teams', '0003_alter_assignmember_merchant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('basic', 'Basic'), ('team', 'Subscription')], default='basic', max_length=20, verbose_name='Package Type'),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('type', 'merchant')},
        ),
    ]
