# Generated by Django 3.2.8 on 2023-03-08 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_rename_user_merchant_merchant'),
        ('teams', '0003_auto_20230308_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='merchant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='merchantinvite', to='account.merchant', verbose_name='Merchant'),
            preserve_default=False,
        ),
    ]
