# Generated by Django 4.1.9 on 2023-11-16 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_team_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='verbose_type',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('team', 'Subscription')], max_length=40, null=True, verbose_name='Package Type'),
        ),
        migrations.AlterField(
            model_name='team',
            name='package',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.package', verbose_name='Team Plan'),
            preserve_default=False,
        ),
    ]
