# Generated by Django 3.2.8 on 2023-04-24 21:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_remove_package_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='max_invites_per_team',
        ),
        migrations.RemoveField(
            model_name='package',
            name='max_projects_applicable_per_team',
        ),
        migrations.RemoveField(
            model_name='package',
            name='max_proposals_per_project',
        ),
        migrations.RemoveField(
            model_name='package',
            name='max_tasks_applicable_per_team',
        ),
        migrations.AddField(
            model_name='package',
            name='monthly_offer_contracts_per_team',
            field=models.PositiveIntegerField(default=0, help_text="Clients can view team member's profile and send offer Contracts up to 100 monthly", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Monthly Offer Contracts'),
        ),
        migrations.AddField(
            model_name='package',
            name='monthly_projects_applicable_per_team',
            field=models.PositiveIntegerField(default=10, help_text='Monthly Jobs Applications with min of 5 and max 50', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)], verbose_name='Monthly Applications Per Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teampackage', to='teams.package', verbose_name='Team Plan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='max_member_per_team',
            field=models.PositiveIntegerField(default=0, help_text='New feature Coming Soon: Here, freelancer team can send followup/ reminder mail per external contract to client. Daily sending will have min of 1 amd max is 3 mails', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Daily Contract Mail reminder'),
        ),
        migrations.AlterField(
            model_name='package',
            name='max_proposals_allowable_per_team',
            field=models.PositiveIntegerField(default=5, help_text='You can add min of 5 and max of 50 Proposals per Team', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)], verbose_name='Max Proposals Per Team'),
        ),
    ]
