# Generated by Django 3.2.8 on 2022-06-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20220624_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='razorpay_order_key',
        ),
        migrations.RemoveField(
            model_name='team',
            name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='team',
            name='razorpay_plan_item',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razorpay Plan ID'),
        ),
        migrations.AddField(
            model_name='team',
            name='razorpay_subbscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razorpay Subscription ID'),
        ),
    ]
