# Generated by Django 3.2.8 on 2023-06-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_team_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='package_status',
            field=models.CharField(choices=[('default', 'Default Plan'), ('active', 'Active Plan')], default='default', max_length=20, verbose_name='Package Status'),
        ),
    ]
