# Generated by Django 4.1.9 on 2023-11-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_package_verbose_type_alter_team_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='verbose_type',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Branded Name'),
        ),
    ]
