# Generated by Django 4.1.9 on 2023-09-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_package_type_alter_package_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='package',
            unique_together=set(),
        ),
    ]
