# Generated by Django 3.2.8 on 2022-06-24 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20220624_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='razorpay_subbscription_id',
            new_name='razorpay_subscription_id',
        ),
    ]
