# Generated by Django 3.2.8 on 2023-06-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='gallery_link',
            field=models.URLField(blank=True, help_text='A link to your gallery of greaat jobs done', max_length=2083, null=True, verbose_name='Sample Website'),
        ),
    ]
