# Generated by Django 3.2.8 on 2023-04-24 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_package_max_member_per_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('ordering',), 'verbose_name': 'Upsell Package', 'verbose_name_plural': 'Upsell Packages'},
        ),
    ]
