# Generated by Django 3.2.8 on 2022-06-28 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0005_rename_razorpay_subbscription_id_team_razorpay_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='Receiver'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='sender',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='account.customer', verbose_name='Sender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=20),
            preserve_default=False,
        ),
    ]
