# Generated by Django 4.1.9 on 2023-09-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_package_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('basic', 'Basic'), ('team', 'Subscription')], max_length=20, verbose_name='Package Type'),
        ),
    ]
