# Generated by Django 4.1.9 on 2023-07-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_gallery_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('basic', 'Basic'), ('team', 'Subscription')], default='basic', max_length=10, unique=True, verbose_name='Package Type'),
        ),
    ]
