# Generated by Django 3.2.8 on 2022-06-28 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0006_auto_20220628_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='receiver',
            field=models.ForeignKey(blank=True, default=4, on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to='account.customer', verbose_name='Receiver'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitation',
            name='sender',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
    ]
