# Generated by Django 4.1.9 on 2023-09-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_merchant_packages'),
        ('teams', '0006_alter_package_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('type', 'merchant')},
        ),
    ]
