# Generated by Django 4.1.9 on 2023-07-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_alter_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='notice',
            field=models.TextField(max_length=2000, verbose_name='Purpose/Mission'),
        ),
    ]
