# Generated by Django 4.1.9 on 2023-09-16 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_alter_package_max_member_per_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='max_member_per_team',
            field=models.PositiveIntegerField(default=1, help_text='A freelancer can invite upt this number inclusive', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Max Member per Team'),
        ),
        migrations.AlterField(
            model_name='package',
            name='monthly_projects_applicable_per_team',
            field=models.PositiveIntegerField(default=5, help_text='Monthly Jobs Applications with min of 5 and max 50', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)], verbose_name='Monthly Applications Per Team'),
        ),
    ]
