# Generated by Django 3.2.8 on 2022-07-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_alter_invitation_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='razorpay_plan_item',
        ),
        migrations.AddField(
            model_name='team',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razorpay Payment ID'),
        ),
    ]
