# Generated by Django 3.2.8 on 2022-07-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_auto_20220716_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_balance',
            field=models.PositiveIntegerField(default=0, help_text='Team Transaction Balance', verbose_name='Team Balance'),
        ),
    ]
