# Generated by Django 3.2.8 on 2022-08-08 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_team_team_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='monthly_projects_applicable_per_team',
            field=models.PositiveIntegerField(default=10, help_text='Monthly Jobs Applications with min of 5 and max 50', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)], verbose_name='Monthly Project Applicable Per Team'),
        ),
    ]
