# Generated by Django 3.2.8 on 2022-08-29 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_alter_package_monthly_projects_applicable_per_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='daily_Handshake_mails_to_clients',
            field=models.PositiveIntegerField(default=0, help_text='team can send followup mail per invoice to client. Daily min is 1 amd max is 3', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Daily Contract Mail reminder'),
        ),
        migrations.AlterField(
            model_name='package',
            name='monthly_offer_contracts_per_team',
            field=models.PositiveIntegerField(default=0, help_text="Clients can view team member's profile and send offer Contracts up to 100 monthly", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Monthly Offer Contracts'),
        ),
        migrations.AlterField(
            model_name='package',
            name='monthly_projects_applicable_per_team',
            field=models.PositiveIntegerField(default=10, help_text='Monthly Jobs Applications with min of 5 and max 50', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)], verbose_name='Monthly Applications Per Team'),
        ),
    ]
