# Generated by Django 3.2.8 on 2022-08-29 01:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_auto_20220829_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='daily_Handshake_mails_to_clients',
            field=models.PositiveIntegerField(default=0, help_text='New feature Coming Soon: Here, freelancer team can send followup/ reminder mail per external contract to client. Daily sending will have min of 1 amd max is 3 mails', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Daily Contract Mail reminder'),
        ),
    ]
