# Generated by Django 3.2.8 on 2022-09-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_alter_package_daily_handshake_mails_to_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='type',
            field=models.CharField(choices=[('founder', 'Founder'), ('internal', 'Internal'), ('external', 'External')], max_length=20),
        ),
    ]
