# Generated by Django 3.2.8 on 2022-09-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0018_auto_20220902_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmember',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Assign On'),
        ),
    ]
