# Generated by Django 3.2.8 on 2022-09-07 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0019_assignmember_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmember',
            options={'ordering': ('-modified',), 'verbose_name': 'Assign Member', 'verbose_name_plural': 'Assign Member'},
        ),
    ]
