# Generated by Django 3.2.8 on 2023-03-18 11:06

import django.core.validators
from django.db import migrations, models
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Amount')),
                ('comment', models.TextField(max_length=200, verbose_name='Credit Comment')),
                ('reference', models.CharField(blank=True, help_text='STAN means System Audit Trail Number', max_length=200, verbose_name='STAN')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Started On')),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('approved', 'Approved')], default='initiated', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Credit Memo',
                'verbose_name_plural': 'Credit Memos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_account', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer Account Number', max_length=100, null=True, verbose_name='Bearer Account/Email'))),
                ('paypal_bearer', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer names', max_length=100, null=True, verbose_name='Bearer names'))),
                ('paypal_country', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer account country. E.g Singapore', max_length=100, null=True, verbose_name='Bearer Country Name'))),
                ('stripe_country', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer account country. E.g Canada', max_length=100, null=True, verbose_name='Bearer Country Name'))),
                ('stripe_bank', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer Bank Name - Account Specific', max_length=100, null=True, verbose_name='Bearer Bank Name'))),
                ('stripe_account', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer Account Number', max_length=100, null=True, verbose_name='Account Number'))),
                ('stripe_routing', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer Routing Number - Country/Bank Specific', max_length=100, null=True, verbose_name='Routing Number'))),
                ('stripe_swift_iban', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer Swift code/Iban- Country/Bank Specific', max_length=100, null=True, verbose_name='Swift/Iban code'))),
                ('stripe_bearer', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer names', max_length=150, null=True, verbose_name='Bearer Names'))),
                ('stripe_extra_info', django_cryptography.fields.encrypt(models.TextField(blank=True, help_text='Additional information to be included', max_length=100, null=True, verbose_name='Extra Credentials'))),
                ('flutterwave_type', django_cryptography.fields.encrypt(models.CharField(choices=[('mobilemoney', 'Mobile Money'), ('bank', 'Bank Account')], default='mobilemoney', max_length=20, verbose_name='Flutterwave Account Type'))),
                ('flutterwave_bank', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer Bank name - Account Type Specific', max_length=150, null=True, verbose_name='Bearer Bank Names'))),
                ('flutterwave_bearer', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer Account names', max_length=150, null=True, verbose_name='Bearer Names'))),
                ('flutterwave_country', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer account country. E.g Nigeria', max_length=100, null=True, verbose_name='Bearer Country Name'))),
                ('flutterwave_account', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer Account Number', max_length=100, null=True, verbose_name='Flutterwave Account Number'))),
                ('flutterwave_swift_iban', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Swift code/Iban- Country Specific', max_length=100, null=True, verbose_name='Swift/Iban'))),
                ('flutterwave_extra_info', django_cryptography.fields.encrypt(models.TextField(blank=True, help_text='Additional information to be included', max_length=100, null=True, verbose_name='Extra Credentials'))),
                ('razorpay_bearer', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer Account names', max_length=150, null=True, verbose_name='Razorpay Bearer Names'))),
                ('razorpay_upi', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer UPI ID to receive payment', max_length=100, null=True, verbose_name='Razorpay UPI ID'))),
                ('razorpay_country', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer account country. E.g India', max_length=100, null=True, verbose_name='Bearer Country Name'))),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Started On')),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Account',
                'verbose_name_plural': 'Payment Account',
            },
        ),
        migrations.CreateModel(
            name='PaymentAPIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.CharField(blank=True, default='This is the API Section for the integrated payment gateways', max_length=255, verbose_name='Preamble')),
                ('gateway_count', models.PositiveSmallIntegerField(blank=True, default=4, null=True, verbose_name='Number of Gateways')),
                ('stripe_public_key', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='STRIPE PUBLISHABLE KEY'))),
                ('stripe_secret_key', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='STRIPE SECRET KEY'))),
                ('stripe_webhook_key', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='STRIPE WEEBHOOK KEY(OPTIONAL)'))),
                ('stripe_subscription_price_id', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='STRIPE SUBSCRIPTION PRICE ID'))),
                ('paypal_public_key', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='PAYPAL PUBLISHABLE KEY'))),
                ('paypal_secret_key', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='PAYPAL SECRET KEY'))),
                ('paypal_subscription_price_id', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='PAYPAL SUBSCRIPTION PRICE ID'))),
                ('sandbox', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=True, verbose_name='Sandbox Mode')),
                ('flutterwave_public_key', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='FLUTTERWAVE PUBLISHABLE KEY'))),
                ('flutterwave_secret_key', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='FLUTTERWAVE SECRET KEY'))),
                ('flutterwave_secret_hash', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Flutterwave secret Hash')),
                ('flutterwave_subscription_price_id', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='FLUTTERWAVE SUBSCRIPTION PRICE ID'))),
                ('razorpay_public_key_id', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='RAZORPAY PUBLISHABLE KEY'))),
                ('razorpay_secret_key_id', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='RAZORPAY SECRET KEY'))),
                ('razorpay_subscription_price_id', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='RAZORPAY SUBSCRIPTION PRICE ID'))),
            ],
            options={
                'verbose_name': 'Payment API',
                'verbose_name_plural': 'Payment API',
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('balance', 'Balance'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('flutterwave', 'Flutterwave'), ('razorpay', 'Razorpay'), ('mtn_momo', 'MTN Momo')], default='balance', max_length=20, unique=True, verbose_name='Payment Gateway')),
                ('status', models.BooleanField(choices=[(False, 'Inactive'), (True, 'Active')], default=False, verbose_name='Status')),
                ('processing_fee', models.PositiveIntegerField(blank=True, default=0, help_text='discount price must be less than actual price', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)], verbose_name='Processing Fee')),
                ('ordering', models.PositiveIntegerField(default=1, help_text='This determines how each Gateway will appear to user eg, 1 means 1st position', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Ordering')),
                ('default', models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], verbose_name='Default')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Amount')),
                ('status', models.BooleanField(choices=[(False, 'Pending'), (True, 'Paid')], default=False, verbose_name='Action Type')),
                ('gateway', models.CharField(max_length=50, verbose_name='Payment Account')),
                ('message', models.TextField(blank=True, max_length=500, null=True, verbose_name='Payment Error Message')),
                ('payday', models.DateTimeField(blank=True, null=True, verbose_name='Payment Due')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested On')),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, help_text='This is a unique number assigned for audit purposes', max_length=15, verbose_name='Ref Number')),
            ],
            options={
                'verbose_name': 'Payment Request',
                'verbose_name_plural': 'Payment Request',
                'ordering': ['-created_at'],
            },
        ),
    ]
