# Generated by Django 3.2.8 on 2022-07-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentrequest',
            options={'verbose_name': 'Payment Request', 'verbose_name_plural': 'Payment Request'},
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='gateway',
            field=models.CharField(default='', max_length=50, verbose_name='Payment Account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='status_choice',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=50, verbose_name='Action Type'),
        ),
    ]
