# Generated by Django 3.2.8 on 2023-04-21 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paymentrequesterteam', to='teams.team', verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paymentrequest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.merchant', verbose_name='Merchant'),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='primary_account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymntaccountgateway', to='payments.paymentgateway', verbose_name='Account Type'),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paymentaccount', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchantapis',
            name='merchant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paymentapi', to='account.merchant', verbose_name='Merchant'),
        ),
        migrations.AddField(
            model_name='admincredit',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditreceiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admincredit',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admincreditor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admincredit',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admincreditteam', to='teams.team', verbose_name='Team'),
        ),
    ]
