# Generated by Django 3.2.8 on 2022-07-24 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20220724_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='payday',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Payment Deadline'),
            preserve_default=False,
        ),
    ]
