# Generated by Django 4.1.9 on 2023-11-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantapis',
            name='mtn_active',
        ),
        migrations.RemoveField(
            model_name='merchantapis',
            name='mtn_api_key',
        ),
        migrations.RemoveField(
            model_name='merchantapis',
            name='mtn_api_user_id',
        ),
        migrations.RemoveField(
            model_name='merchantapis',
            name='mtn_callback_url',
        ),
        migrations.RemoveField(
            model_name='merchantapis',
            name='mtn_subscription_key',
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='name',
            field=models.CharField(choices=[('balance', 'Balance'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('flutterwave', 'Flutterwave'), ('razorpay', 'Razorpay'), ('paystack', 'Paystack')], default='balance', max_length=20, unique=True, verbose_name='Payment Gateway'),
        ),
    ]
