# Generated by Django 3.2.8 on 2022-07-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentrequest_payday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='payday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment Deadline'),
        ),
    ]
