# Generated by Django 4.1.9 on 2023-11-19 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_package_verbose_type'),
        ('account', '0005_remove_merchant_basic_price_and_more'),
        ('payments', '0003_remove_merchantapis_mtn_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('balance', 'Balance'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('razorpay', 'Razorpay')], default='balance', max_length=200, verbose_name='Payment Method')),
                ('price', models.PositiveIntegerField()),
                ('status', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Paid')),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer ID')),
                ('subscription_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subscription ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Subscription Start')),
                ('activation_time', models.DateTimeField(blank=True, null=True, verbose_name='Activation Time')),
                ('expired_time', models.DateTimeField(blank=True, null=True, verbose_name='Est. Expiration')),
                ('reference', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Order Key')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.merchant', verbose_name='Merchant')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptionteam', to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': ('-created_at',),
            },
        ),
    ]
