# Generated by Django 4.1.9 on 2023-08-07 17:57

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_merchantapis_stripe_sandbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantapis',
            name='flutterwave_secret_hash',
        ),
        migrations.AddField(
            model_name='merchantapis',
            name='paystack_active',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='merchantapis',
            name='paystack_public_key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='PAYSTACK PUBLISHABLE KEY')),
        ),
        migrations.AddField(
            model_name='merchantapis',
            name='paystack_secret_key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='PAYSTACK SECRET KEY')),
        ),
        migrations.AddField(
            model_name='merchantapis',
            name='paystack_subscription_price_id',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='PAYSTACK SUBSCRIPTION PRICE ID')),
        ),
    ]
