# Generated by Django 4.1.9 on 2023-11-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.BooleanField(choices=[(False, 'Failed'), (True, 'Success')], default=False, verbose_name='Paid'),
        ),
    ]
