# Generated by Django 3.2.8 on 2023-03-26 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20230322_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flutterwavemerchant',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='mtnmerchant',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='paypalmerchant',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='razorpaymerchant',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='stripemerchant',
            name='gateway',
        ),
    ]
