# Generated by Django 3.2.8 on 2022-07-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_paymentrequest_payday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Started On'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='payday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='PayDay By'),
        ),
    ]
