# Generated by Django 4.1.9 on 2023-11-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_subscription_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='customer_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Token'),
        ),
    ]
