# Generated by Django 3.2.8 on 2023-03-26 22:27

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20230325_1309'),
        ('payments', '0005_auto_20230326_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentapis',
            name='gateway_count',
        ),
        migrations.CreateModel(
            name='MerchantAPIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.CharField(blank=True, default='This is the API Section for the integrated payment gateways', max_length=255, verbose_name='Preamble')),
                ('stripe_public_key', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='STRIPE PUBLISHABLE KEY'))),
                ('stripe_secret_key', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='STRIPE SECRET KEY'))),
                ('stripe_webhook_key', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='STRIPE WEEBHOOK KEY(OPTIONAL)'))),
                ('stripe_subscription_price_id', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='STRIPE SUBSCRIPTION PRICE ID'))),
                ('paypal_public_key', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='PAYPAL PUBLISHABLE KEY'))),
                ('paypal_secret_key', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='PAYPAL SECRET KEY'))),
                ('paypal_subscription_price_id', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='PAYPAL SUBSCRIPTION PRICE ID'))),
                ('sandbox', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=True, verbose_name='Sandbox Mode')),
                ('flutterwave_public_key', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='FLUTTERWAVE PUBLISHABLE KEY'))),
                ('flutterwave_secret_key', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='FLUTTERWAVE SECRET KEY'))),
                ('flutterwave_secret_hash', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Flutterwave secret Hash')),
                ('flutterwave_subscription_price_id', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='FLUTTERWAVE SUBSCRIPTION PRICE ID'))),
                ('razorpay_public_key_id', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='RAZORPAY PUBLISHABLE KEY'))),
                ('razorpay_secret_key_id', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='RAZORPAY SECRET KEY'))),
                ('razorpay_subscription_price_id', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='RAZORPAY SUBSCRIPTION PRICE ID'))),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paymentapi', to='account.merchant', verbose_name='Merchant')),
            ],
            options={
                'verbose_name': 'Payment API',
                'verbose_name_plural': 'Payment API',
            },
        ),
    ]
