# Generated by Django 3.2.8 on 2022-07-24 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0005_auto_20220724_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Paypal Account to receive payment', max_length=100, null=True, verbose_name='PayPal Account'))),
                ('stripe', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Stripe Account to receive payment', max_length=100, null=True, verbose_name='Stripe Account'))),
                ('flutterwave', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Stripe Account to receive payment', max_length=100, null=True, verbose_name='Flutterwave Account'))),
                ('razorpay', django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Stripe Account to receive payment', max_length=100, null=True, verbose_name='Razorpay Account'))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paymentaccount', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Account',
                'verbose_name_plural': 'Payment Account',
            },
        ),
    ]
