# Generated by Django 3.2.8 on 2022-07-24 23:59

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_paymentaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='flutterwave',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Flutterwave Account to receive payment', max_length=100, null=True, verbose_name='Flutterwave Account')),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='razorpay',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Razorpay Account to receive payment', max_length=100, null=True, verbose_name='Razorpay Account')),
        ),
    ]
