# Generated by Django 3.2.8 on 2023-03-26 22:37

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20230326_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantapis',
            name='preview',
        ),
        migrations.AddField(
            model_name='merchantapis',
            name='flutterwave_active',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='merchantapis',
            name='mtn_active',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='merchantapis',
            name='mtn_api_key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='MTN API KEY')),
        ),
        migrations.AddField(
            model_name='merchantapis',
            name='mtn_api_user_id',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='MTN API_USER ID')),
        ),
        migrations.AddField(
            model_name='merchantapis',
            name='mtn_callback_url',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='MTN CALLBACK URL')),
        ),
        migrations.AddField(
            model_name='merchantapis',
            name='mtn_subscription_key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='MTN SUBSCRIPTION PRICE ID')),
        ),
        migrations.AddField(
            model_name='merchantapis',
            name='paypal_active',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='merchantapis',
            name='razorpay_active',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='merchantapis',
            name='stripe_active',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Status'),
        ),
    ]
