# Generated by Django 4.1.9 on 2023-11-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_subscription_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='customer_token',
            field=models.CharField(blank=True, max_length=2088, null=True, verbose_name='Customer Token'),
        ),
    ]
