# Generated by Django 3.2.8 on 2022-07-25 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20220724_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Started On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
