# Generated by Django 3.2.8 on 2023-03-26 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20230326_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypalmerchant',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='razorpaymerchant',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='stripemerchant',
            name='merchant',
        ),
        migrations.AlterModelOptions(
            name='merchantapis',
            options={'verbose_name': 'Merchant API', 'verbose_name_plural': 'Merchant API'},
        ),
        migrations.DeleteModel(
            name='FlutterwaveMerchant',
        ),
        migrations.DeleteModel(
            name='PayPalMerchant',
        ),
        migrations.DeleteModel(
            name='RazorpayMerchant',
        ),
        migrations.DeleteModel(
            name='StripeMerchant',
        ),
    ]
