# Generated by Django 3.2.8 on 2023-03-26 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20230326_2329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MTNMerchant',
        ),
    ]
