# Generated by Django 3.2.8 on 2023-03-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_delete_mtnmerchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='name',
            field=models.CharField(choices=[('balance', 'Balance'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('flutterwave', 'Flutterwave'), ('razorpay', 'Razorpay'), ('paystack', 'Paystack'), ('mtn_momo', 'MTN Momo')], default='balance', max_length=20, unique=True, verbose_name='Payment Gateway'),
        ),
    ]
