# Generated by Django 3.2.8 on 2022-07-31 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_team_team_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0009_alter_paymentrequest_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Amount')),
                ('message', models.TextField(max_length=200, verbose_name='Credit Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Started On')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admincreditteam', to='teams.team', verbose_name='Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admincreditor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Credit',
                'verbose_name_plural': 'Admin Credits',
                'ordering': ['-created_at'],
            },
        ),
    ]
