# Generated by Django 3.2.8 on 2022-07-31 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0010_admincredit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admincredit',
            old_name='user',
            new_name='sender',
        ),
        migrations.AddField(
            model_name='admincredit',
            name='receiver',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='creditreceiver', to='account.customer'),
            preserve_default=False,
        ),
    ]
