# Generated by Django 3.2.8 on 2022-08-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20220731_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admincredit',
            name='message',
        ),
        migrations.AddField(
            model_name='admincredit',
            name='comment',
            field=models.TextField(default=0, max_length=200, verbose_name='Credit Comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admincredit',
            name='reference',
            field=models.CharField(blank=True, help_text='STAN means System Audit Trail Number', max_length=200, verbose_name='STAN'),
        ),
    ]
