# Generated by Django 3.2.8 on 2022-08-02 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0012_auto_20220801_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='paymentaccount', to=settings.AUTH_USER_MODEL),
        ),
    ]
