# Generated by Django 3.2.8 on 2022-08-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_alter_paymentaccount_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='status_choice',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='status',
            field=models.BooleanField(choices=[(False, 'Pending'), (True, 'Paid')], default=False, verbose_name='Action Type'),
        ),
    ]
