# Generated by Django 3.2.8 on 2022-08-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_paymentrequest_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='reference',
            field=models.CharField(blank=True, help_text='This is a unique number assigned for audit purposes', max_length=15, verbose_name='Ref Number'),
        ),
    ]
