# Generated by Django 3.2.8 on 2022-08-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_auto_20220804_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Payment Error Message'),
        ),
    ]
