# Generated by Django 3.2.8 on 2022-08-08 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_admincredit_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admincredit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Credit Memo', 'verbose_name_plural': 'Credit Memos'},
        ),
    ]
