# Generated by Django 3.2.8 on 2022-10-20 23:24

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_alter_admincredit_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentaccount',
            name='flutterwave',
        ),
        migrations.RemoveField(
            model_name='paymentaccount',
            name='paypal',
        ),
        migrations.RemoveField(
            model_name='paymentaccount',
            name='razorpay',
        ),
        migrations.RemoveField(
            model_name='paymentaccount',
            name='stripe',
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='flutterwave_account',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer Account Number', max_length=100, null=True, verbose_name='Flutterwave Account Number')),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='flutterwave_bank',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer Bank name - Account Type Specific', max_length=150, null=True, verbose_name='Bearer Bank Names')),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='flutterwave_bearer',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer Account names', max_length=150, null=True, verbose_name='Bearer Names')),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='flutterwave_country',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer account country. E.g Nigeria', max_length=100, null=True, verbose_name='Bearer Country Name')),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='flutterwave_extra_info',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, help_text='Additional information to be included', max_length=100, null=True, verbose_name='Extra Credentials')),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='flutterwave_swift_iban',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Swift code/Iban- Country Specific', max_length=100, null=True, verbose_name='Swift/Iban')),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='flutterwave_type',
            field=django_cryptography.fields.encrypt(models.CharField(choices=[('mobilemoney', 'Mobile Money'), ('bank', 'Bank Account')], default='mobilemoney', max_length=20, verbose_name='Flutterwave Account Type')),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='paypal_account',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer Account Number', max_length=100, null=True, verbose_name='Bearer Account/Email')),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='paypal_bearer',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer names', max_length=100, null=True, verbose_name='Bearer names')),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='paypal_country',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer account country. E.g Singapore', max_length=100, null=True, verbose_name='Bearer Country Name')),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='razorpay_bearer',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer Account names', max_length=150, null=True, verbose_name='Razorpay Bearer Names')),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='razorpay_country',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer account country. E.g India', max_length=100, null=True, verbose_name='Bearer Country Name')),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='razorpay_upi',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer UPI ID to receive payment', max_length=100, null=True, verbose_name='Razorpay UPI ID')),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='stripe_account',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer Account Number', max_length=100, null=True, verbose_name='Account Number')),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='stripe_bank',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer Bank Name - Account Specific', max_length=100, null=True, verbose_name='Bearer Bank Name')),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='stripe_bearer',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer names', max_length=150, null=True, verbose_name='Bearer Names')),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='stripe_country',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer account country. E.g Canada', max_length=100, null=True, verbose_name='Bearer Country Name')),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='stripe_extra_info',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, help_text='Additional information to be included', max_length=100, null=True, verbose_name='Extra Credentials')),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='stripe_routing',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer Routing Number - Country/Bank Specific', max_length=100, null=True, verbose_name='Routing Number')),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='stripe_swift_iban',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='Bearer Swift code/Iban- Country/Bank Specific', max_length=100, null=True, verbose_name='Swift/Iban code')),
        ),
    ]
