# Generated by Django 3.2.8 on 2022-10-20 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0036_auto_20221017_2122'),
        ('freelancer', '0017_rename_reference_id_freelanceraction_reference'),
        ('payments', '0021_auto_20221020_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaccount',
            name='primary_account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymntaccountgateway', to='general_settings.paymentgateway', verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paymentaccount', to='freelancer.freelancer'),
        ),
    ]
