# Generated by Django 3.2.8 on 2022-10-20 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0022_auto_20221020_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paymentaccount', to=settings.AUTH_USER_MODEL),
        ),
    ]
