# Generated by Django 3.2.8 on 2023-03-05 22:21

import django.contrib.sites.managers
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('merchant', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
