# Generated by Django 3.2.8 on 2023-03-18 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='members',
            field=models.ManyToManyField(related_name='merchant_staff', to=settings.AUTH_USER_MODEL, verbose_name='Company Staff'),
        ),
    ]
