# Generated by Django 4.1.9 on 2023-09-16 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='package',
        ),
        migrations.AddField(
            model_name='merchant',
            name='packages',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='package', to='account.package', verbose_name='Package'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='multiple_freelancer_teams',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, help_text='Enables each freelancer can create multiple teams', verbose_name='Multiple teams per Freelancer'),
        ),
    ]
