# Generated by Django 4.1.9 on 2023-11-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='team_plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('team', 'Subscription')], default='basic', max_length=20, verbose_name='Package Type'),
        ),
    ]
