# Generated by Django 3.2.8 on 2022-08-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_hr',
            field=models.BooleanField(default=False, verbose_name='HR Status'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_marketing_manager',
            field=models.BooleanField(default=False, verbose_name='Marketing Manager Status'),
        ),
    ]
