# Generated by Django 3.2.8 on 2023-05-19 21:27

import django.core.validators
from django.db import migrations, models
import general_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='brand_ambassador_image',
            field=models.ImageField(blank=True, help_text="This will appear to logged-in user on 'About Us Page, Freelancer page, project page'. Size should be 255px x 255px. image must be any of these: 'JPEG','JPG','PNG','PSD'", null=True, upload_to=general_settings.models.site_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPG', 'JPEG', 'PNG', 'PSD'])], verbose_name='Brand Ambassador Image'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='button_color',
            field=models.CharField(blank=True, default='purple', help_text="Customize colors for signup, login, any other visitor buttons. Example '3F0F8FF', or 'red' or 'blue' or 'purple' or any css color code. Warning!: Donnot add quotation marks around the color attributes", max_length=100, null=True, verbose_name='Visitor Buttons'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Enter the full secure url path of your Facebook page', max_length=255, null=True, verbose_name='Facebook Page'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Enter the full secure url path of your Instagram page', max_length=255, null=True, verbose_name='Instagram Page'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='navbar_color',
            field=models.CharField(blank=True, default='purple', help_text="Customize colors for Navbar. Example '3F0F8FF', or 'red' or 'blue' or 'purple' or any css color code. Warning!: Donnot add quotation marks around the color attributes", max_length=100, null=True, verbose_name='NavBar Color'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='site_Logo',
            field=models.ImageField(blank=True, default='site/logo.png', null=True, upload_to=general_settings.models.site_path, verbose_name='Site Logo'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Enter the full secure url path of your Twitter page', max_length=255, null=True, verbose_name='Twitter Page'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Enter the full secure url path of your Youtube page', max_length=255, null=True, verbose_name='Youtube Page'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Business Address'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='description',
            field=models.TextField(blank=True, default='The Example Marketplace', max_length=300, null=True, verbose_name='Site Decription'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='tagline',
            field=models.CharField(blank=True, default='The Marketplace', max_length=150, null=True, verbose_name='Site Tagline'),
        ),
    ]
