# Generated by Django 3.2.8 on 2023-04-24 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='daily_Handshake_mails_to_clients',
            new_name='max_member_per_team',
        ),
        migrations.AddField(
            model_name='package',
            name='upsell_price',
            field=models.PositiveIntegerField(default=0, help_text='Decide your reasonable price with max limit of 1000', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Package Price'),
        ),
    ]
