# Generated by Django 3.2.8 on 2023-03-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20230306_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='status',
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('Basic', 'Starter'), ('Team', 'Standard'), ('Enterprise', 'Enterprise')], default='Basic', max_length=50, unique=True, verbose_name='Package Type'),
        ),
    ]
