# Generated by Django 3.2.8 on 2023-03-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_package_max_num_of_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active_merchant_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Active Merchant ID'),
        ),
    ]
