# Generated by Django 4.1.9 on 2023-11-15 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_merchant_team_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='basic_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Basic Price'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='max_member_per_team',
            field=models.PositiveIntegerField(default=1, help_text='A freelancer can invite upt this number inclusive', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Max Member per Team'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='max_proposals_allowable_per_team',
            field=models.PositiveIntegerField(default=5, help_text='You can add min of 5 and max of 50 Proposals per Team', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)], verbose_name='Max Proposals Per Team'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='monthly_offer_contracts_per_team',
            field=models.PositiveIntegerField(default=5, help_text="Clients can view team member's profile and send offer Contracts up to 100 monthly", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Monthly Offer Contracts'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='monthly_projects_applicable_per_team',
            field=models.PositiveIntegerField(default=5, help_text='Monthly Jobs Applications with min of 5 and max 50', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)], verbose_name='Monthly Applications Per Team'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='ordering',
            field=models.PositiveIntegerField(default=1, help_text='This determines how each package will appear to user eg, 1 means first position', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Display'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='team_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Team Price'),
        ),
    ]
