# Generated by Django 4.1.9 on 2023-09-16 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_merchant_package_merchant_packages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='packages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='account.package', verbose_name='Package'),
        ),
    ]
