# Generated by Django 3.2.8 on 2023-04-24 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20230424_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='max_member_per_team',
            field=models.PositiveIntegerField(default=0, help_text='New feature Coming Soon: Here, freelancer team can send followup/ reminder mail per external contract to client. Daily sending will have min of 1 amd max is 3 mails', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Max Member per Team'),
        ),
    ]
