# Generated by Django 4.1.9 on 2023-09-17 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_merchant_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='level_four_name',
            field=models.CharField(default='Level Four Discount System', max_length=30, verbose_name='Level Four(L4)'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='level_four_rate',
            field=models.PositiveIntegerField(default=7, help_text='Highest Rate for L4 Discount with minimum default of 7%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='L4 Rate'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='level_four_start_amount',
            field=models.PositiveIntegerField(default=1000, help_text='Minimum checkout Amount with default of 1000 currency points', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50000)], verbose_name='L4 Amount Start'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='level_one_delta_amount',
            field=models.PositiveIntegerField(default=199, help_text='checkout amount delta with default of 199 currency points', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50000)], verbose_name='L1 Amount Delta'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='level_one_name',
            field=models.CharField(default='Level One Discount System', max_length=30, verbose_name='Level One(L1)'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='level_one_rate',
            field=models.PositiveIntegerField(default=0, help_text='Starting Rate for L1 Discount with minimum default of 0 %', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0)], verbose_name='L1 Rate'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='level_one_start_amount',
            field=models.PositiveIntegerField(default=10, help_text='Minimum checkout amount with default of zero(0) currency points', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50000)], verbose_name='L1 Amount Start'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='level_three_delta_amount',
            field=models.PositiveIntegerField(default=999, help_text='checkout amount delta with default of 999 currency points', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50000)], verbose_name='L3 Amount Delta'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='level_three_name',
            field=models.CharField(default='Level Three Discount System', max_length=30, verbose_name='Level Three(L3)'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='level_three_rate',
            field=models.PositiveIntegerField(default=5, help_text='Medium Rate for L3 Discount with minimum default of 5%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='L3 Rate'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='level_three_start_amount',
            field=models.PositiveIntegerField(default=500, help_text='Minimum checkout amount with default of 500 currency points', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50000)], verbose_name='L3 Amount Start'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='level_two_delta_amount',
            field=models.PositiveIntegerField(default=499, help_text='checkout amount delta with default of 499 currency points', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50000)], verbose_name='L2 Amount Delta'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='level_two_name',
            field=models.CharField(default='Level Two Discount System', max_length=30, verbose_name='Level Two(L2)'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='level_two_rate',
            field=models.PositiveIntegerField(default=3, help_text='Second level Rate for L2 Discount with minimum default of 3%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='L2 Rate'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='level_two_start_amount',
            field=models.PositiveIntegerField(default=300, help_text='Minimum checkout amount with default of 300 currency points', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50000)], verbose_name='L2 Amount Start'),
        ),
    ]
