# Generated by Django 3.2.8 on 2023-05-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20230519_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='footer_description',
            field=models.TextField(blank=True, default='Dotem eiusmod tempor incune utnaem labore etdolore maigna aliqua enim poskina ilukita ylokem lokateise ination voluptate velit esse cillum dolore eu fugiat nulla pariatur lokaim urianewce', max_length=250, null=True, verbose_name='Footer Content'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='promo_description',
            field=models.TextField(blank=True, default='The Example Marketplace', max_length=300, null=True, verbose_name='Div Four Promo Decription'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='promo_image',
            field=models.ImageField(blank=True, default='freelancer/awards/banner.png', null=True, upload_to='promo/', verbose_name='Promo Image'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='promo_subtitle',
            field=models.CharField(blank=True, default='Business on the Go', max_length=100, null=True, verbose_name='Div Four Promo Subitle'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='promo_title',
            field=models.CharField(blank=True, default='#1 Choice For Businesses', max_length=100, null=True, verbose_name='Div Four Promo Title'),
        ),
    ]
