# Generated by Django 3.2.8 on 2023-03-06 12:01

import django.contrib.sites.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20230306_1149'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='merchant',
            managers=[
                ('curr_merchant', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
