# Generated by Django 3.2.8 on 2023-03-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customer_active_merchant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='can_change_domain',
            field=models.BooleanField(default=False, help_text='Merchant with this domain can change domain', verbose_name='Domain Change'),
        ),
    ]
