# Generated by Django 3.2.8 on 2023-05-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_package_upsell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='default_domain',
            field=models.CharField(default='merchant.trosgate.com', max_length=255, verbose_name='Default Domain'),
            preserve_default=False,
        ),
    ]
