# Generated by Django 4.1.9 on 2023-09-18 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_merchant_level_four_name_merchant_level_four_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='level_one_delta_amount',
            field=models.PositiveIntegerField(default=299, help_text='checkout amount delta with default of 199 currency points', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50000)], verbose_name='L1 Amount Delta'),
        ),
    ]
