# Generated by Django 3.2.8 on 2022-08-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220805_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_accountant',
            field=models.BooleanField(default=False, verbose_name='Accountant'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Important: This controls login access for Freelaancer and CLient only', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_hr',
            field=models.BooleanField(default=False, verbose_name='HR'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_marketer',
            field=models.BooleanField(default=False, verbose_name='Marketer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_pro',
            field=models.BooleanField(default=False, verbose_name='P.R.O'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Important: This controls login access for SuperAdmin and Staff only', verbose_name='Allow Login Access'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Important: This role controls everything. Think twice before you grant', verbose_name='CEO/SuperAdmin'),
        ),
    ]
