# Generated by Django 3.2.8 on 2023-03-06 12:08

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('account', '0005_alter_merchant_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchant',
            options={'ordering': ('-created_at',), 'verbose_name': 'Merchant', 'verbose_name_plural': 'Merchants'},
        ),
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('merchant', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='last_login',
        ),
        migrations.AddField(
            model_name='customer',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Created'),
        ),
    ]
