# Generated by Django 3.2.8 on 2023-03-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_package_can_change_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='can_change_domain',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, help_text='Merchant with this domain can change domain', verbose_name='Domain Change'),
        ),
    ]
