# Generated by Django 4.1.9 on 2023-11-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_merchant_basic_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='proposal_detail',
            field=models.BooleanField(choices=[(False, 'Proposal without Image'), (True, 'Proposal with Image')], default=False, verbose_name='Proposal Detail Display'),
        ),
    ]
