# Generated by Django 3.2.8 on 2023-03-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20230306_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='business_name',
            field=models.CharField(default=0, max_length=255, verbose_name='Business Name'),
            preserve_default=False,
        ),
    ]
