# Generated by Django 3.2.8 on 2022-08-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220806_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Important: This controls login access for Staffs, Freelancer and CLient', verbose_name='Activate/Deactivate User Login'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_staff',
            field=models.BooleanField(default=False, help_text="Important: Addition to 'Activate/Deactivate User Login', this controls login access for SuperAdmin and Staffs only", verbose_name='Activate/Deactivate Staff Login'),
        ),
    ]
