# Generated by Django 3.2.8 on 2023-05-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_merchant_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='category_subtitle',
            field=models.CharField(blank=True, default='Professional by categories', max_length=100, null=True, verbose_name='Div Two Category Subitle'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='category_title',
            field=models.CharField(blank=True, default='Explore Categories', max_length=100, null=True, verbose_name='Div Two Category Title'),
        ),
    ]
