# Generated by Django 3.2.8 on 2023-03-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_merchant_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='package',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='account.package', verbose_name='Package'),
            preserve_default=False,
        ),
    ]
