# Generated by Django 3.2.8 on 2023-03-20 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20230320_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='max_users_sitewide',
            field=models.PositiveIntegerField(default=100, help_text='Total users including merchant and staffs', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000000)], verbose_name='Max number of users'),
        ),
    ]
