# Generated by Django 3.2.8 on 2022-08-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20220806_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_accountant',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_hr',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_marketer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_pro',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_assistant',
            field=models.BooleanField(default=False, verbose_name='Virtual Assistant'),
        ),
    ]
