# Generated by Django 3.2.8 on 2023-03-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20230322_1944'),
        ('account', '0009_package_multiple_freelancer_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='gateways',
            field=models.ManyToManyField(related_name='packages', to='payments.PaymentGateway', verbose_name='Supported Gateways'),
        ),
    ]
