# Generated by Django 3.2.8 on 2023-03-06 15:59

import django.contrib.sites.managers
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_merchant_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='merchant',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('curr_merchant', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
