# Generated by Django 3.2.8 on 2023-03-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_merchant_gateways'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Last Created'),
        ),
    ]
