# Generated by Django 3.2.8 on 2023-05-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_merchant_banner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='promo_type',
            field=models.BooleanField(choices=[(False, 'Call to Action'), (True, 'How it Works')], default=True, verbose_name='Marketing Section'),
        ),
    ]
