# Generated by Django 3.2.8 on 2022-09-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_twofactorauth_pass_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('date_joined',), 'verbose_name': 'User Manager', 'verbose_name_plural': 'User Manager'},
        ),
    ]
