# Generated by Django 3.2.8 on 2023-03-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_merchant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Residence Address'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='announcement',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Announcement'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='banner_photo',
            field=models.ImageField(default='client/banner.png', upload_to='client/', verbose_name='Banner Photo'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='company_logo',
            field=models.ImageField(default='client/logo.png', upload_to='client/', verbose_name='Brand Logo'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='description',
            field=models.TextField(blank=True, error_messages={'name': {'max_length': 'A maximum of 2000 words required'}}, max_length=2000, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10, verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='profile_photo',
            field=models.ImageField(default='client/avatar5.png', upload_to='client/', verbose_name='Profile Photo'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='tagline',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tagline'),
        ),
    ]
