# Generated by Django 3.2.8 on 2022-09-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_customer_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
    ]
