# Generated by Django 3.2.8 on 2023-05-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_merchant_proposal_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='category_type',
            field=models.BooleanField(choices=[(False, 'Flat Display Category'), (True, 'Popup Display Category')], default=False, verbose_name='Category Type'),
        ),
    ]
