# Generated by Django 3.2.8 on 2023-03-07 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_rename_merchant_merchant_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='user',
            new_name='merchant',
        ),
    ]
