# Generated by Django 3.2.8 on 2022-10-20 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twofactorauth',
            options={'ordering': ('-last_login',), 'verbose_name': 'Access Token', 'verbose_name_plural': 'Access Token'},
        ),
    ]
