# Generated by Django 3.2.8 on 2023-05-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_merchant_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='promo_type',
            field=models.CharField(choices=[('zero', 'No Marketing'), ('one', 'Call to Action'), ('two', 'How it Works')], default='two', max_length=30, verbose_name='Marketing Section'),
        ),
    ]
