# Generated by Django 3.2.8 on 2023-06-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_merchant_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='project_type',
            field=models.BooleanField(choices=[(False, 'VerticaL display'), (True, 'Horizontal display')], default=False, verbose_name='Job Listing Type'),
        ),
    ]
