# Generated by Django 4.1.9 on 2023-08-08 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_merchant_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='official_name',
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(blank=True, max_length=255, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='country',
            name='currency_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='country',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='country',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='country',
            name='phone_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Phone Code'),
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Continent'),
        ),
        migrations.AddField(
            model_name='country',
            name='subregion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Continent'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(blank=True, max_length=150, verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Country Name'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Country Name')),
                ('state_code', models.CharField(blank=True, max_length=100, verbose_name='Country Code')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='latitude')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='longitude')),
                ('ordering', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order Priority')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='account.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='City Name')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='latitude')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='longitude')),
                ('wikidata', models.CharField(blank=True, max_length=255, null=True, verbose_name='Wiki Data Id')),
                ('ordering', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order Priority')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='account.country', verbose_name='Country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='account.state', verbose_name='State')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['ordering'],
            },
        ),
    ]
