# Generated by Django 4.1.9 on 2023-08-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_remove_country_official_name_country_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='State Name'),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='State Code'),
        ),
    ]
