# Generated by Django 4.1.9 on 2023-08-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_state_name_alter_state_state_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='flag',
        ),
    ]
