# Generated by Django 3.2.8 on 2022-05-24 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('contract_duration', models.CharField(choices=[('01 day', '01 Day'), ('02 days', '02 Days'), ('03 days', '03 Days'), ('04 days', '04 Days'), ('05 days', '05 Days'), ('06 days', '06 Days'), ('01 week', '01 Week'), ('02 week', '02 Weeks'), ('03 week', '03 Weeks'), ('01 month', '01 Month'), ('02 month', '02 Months'), ('03 month', '03 Months'), ('04 month', '04 Months'), ('05 month', '05 Months'), ('06 month', '06 Months')], default='01 day', max_length=20, verbose_name='Completion Time')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('urlcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('line_one', models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Service Description')),
                ('line_one_quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_one_unit_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('line_one_total_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total')),
                ('line_two', models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Service Extras One')),
                ('line_two_quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_two_unit_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('line_two_total_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total')),
                ('line_three', models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Service Extras Two')),
                ('line_three_quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_three_unit_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('line_three_total_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total')),
                ('line_four', models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Service Extras Three')),
                ('line_four_quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_four_unit_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('line_four_total_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total')),
                ('line_five', models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Service Extras Four')),
                ('line_five_quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_five_unit_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('line_five_total_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total')),
                ('grand_total', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Grand Total')),
            ],
            options={
                'verbose_name': 'External Contract',
                'verbose_name_plural': 'External Contract',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ContractChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contract Chat',
                'verbose_name_plural': 'Contract Chat',
                'ordering': ['sent_on'],
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=6, null=True)),
                ('phone_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'External Contractor',
                'verbose_name_plural': 'External Contractor',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='InternalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_duration', models.CharField(choices=[('01 day', '01 Day'), ('02 days', '02 Days'), ('03 days', '03 Days'), ('04 days', '04 Days'), ('05 days', '05 Days'), ('06 days', '06 Days'), ('01 week', '01 Week'), ('02 week', '02 Weeks'), ('03 week', '03 Weeks'), ('01 month', '01 Month'), ('02 month', '02 Months'), ('03 month', '03 Months'), ('04 month', '04 Months'), ('05 month', '05 Months'), ('06 month', '06 Months')], default='01 day', max_length=20, verbose_name='Duration')),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=100, verbose_name='Status')),
                ('team_reaction', models.BooleanField(blank=True, choices=[(False, 'Rejected'), (True, 'Accepted')], null=True, verbose_name='Reaction')),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Reference')),
                ('urlcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('line_one', models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Service Description')),
                ('line_one_quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_one_unit_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('line_one_total_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total')),
                ('line_two', models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Service Extras One')),
                ('line_two_quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_two_unit_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('line_two_total_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total')),
                ('line_three', models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Service Extras Two')),
                ('line_three_quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_three_unit_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('line_three_total_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total')),
                ('line_four', models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Service Extras Three')),
                ('line_four_quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_four_unit_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('line_four_total_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total')),
                ('line_five', models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Service Extras Four')),
                ('line_five_quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('line_five_unit_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Unit Price')),
                ('line_five_total_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total')),
                ('grand_total', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Grand Total')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internalcontractauthor', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('payment_gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internalcontractgateway', to='general_settings.paymentgateway', verbose_name='Payment Type')),
            ],
            options={
                'verbose_name': 'Internal Contract',
                'verbose_name_plural': 'Internal Contracts',
                'ordering': ['-date_created'],
            },
        ),
    ]
