# Generated by Django 3.2.8 on 2022-07-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_internalcontract_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalcontract',
            name='payment_gateway',
        ),
        migrations.AlterField(
            model_name='internalcontract',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='internalcontract',
            name='team_reaction',
            field=models.CharField(choices=[('awaiting', 'Awaiting'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='awaiting', max_length=30, verbose_name='State'),
        ),
    ]
