# Generated by Django 3.2.8 on 2022-08-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_auto_20220809_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internalcontract',
            old_name='team_reaction',
            new_name='reaction',
        ),
        migrations.RemoveField(
            model_name='internalcontract',
            name='status',
        ),
    ]
