# Generated by Django 3.2.8 on 2022-08-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_auto_20220829_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalcontract',
            name='duration',
        ),
    ]
