# Generated by Django 3.2.8 on 2022-08-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0012_remove_internalcontract_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalcontract',
            name='reference',
            field=models.CharField(blank=True, default='in5464848', max_length=100, unique=True, verbose_name='Reference'),
            preserve_default=False,
        ),
    ]
