# Generated by Django 3.2.8 on 2022-08-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0014_auto_20220829_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='line_one',
            field=models.CharField(default='build me a website', max_length=120, verbose_name='Service Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='line_one_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='line_one_total_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='line_one_unit_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='reference',
            field=models.CharField(blank=True, default='55dsad', max_length=100, unique=True, verbose_name='Reference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='slug',
            field=models.SlugField(max_length=150, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='internalcontract',
            name='slug',
            field=models.SlugField(blank=True, max_length=350, verbose_name='Slug'),
        ),
    ]
