# Generated by Django 3.2.8 on 2022-08-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0016_alter_contract_contract_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='tax_Number',
        ),
    ]
