# Generated by Django 3.2.8 on 2022-08-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0017_auto_20220829_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractor',
            options={'ordering': ['-date_created'], 'verbose_name': 'External Client', 'verbose_name_plural': 'External Client'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='reaction',
            field=models.CharField(choices=[('awaiting', 'Awaiting'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='accepted', max_length=30, verbose_name='State'),
        ),
    ]
