# Generated by Django 3.2.8 on 2022-09-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0018_auto_20220829_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='notes',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='reaction',
            field=models.CharField(choices=[('awaiting', 'Awaiting'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='awaiting', max_length=30, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='internalcontract',
            name='notes',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
