# Generated by Django 3.2.8 on 2022-10-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0021_alter_contractor_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
