# Generated by Django 3.2.8 on 2022-10-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0022_alter_contractor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='email',
            field=models.CharField(help_text='Enter Valid Email for client to receive mail', max_length=100),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='name',
            field=models.CharField(help_text='Enter an official name known for the client', max_length=100),
        ),
    ]
