# Generated by Django 3.2.8 on 2022-10-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0025_alter_contract_line_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='email',
            field=models.CharField(help_text='Enter Valid Email for client to receive mail', max_length=100, unique=True),
        ),
    ]
