# Generated by Django 3.2.8 on 2023-03-05 22:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Message')),
                ('budget', models.IntegerField(default=10, error_messages={'budget': {'max_length': 'Set the budget amount between 10 and 50000 currency points'}}, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(70000)], verbose_name='Budget')),
                ('estimated_duration', models.CharField(choices=[('01 day', '01 Day'), ('02 days', '02 Days'), ('03 days', '03 Days'), ('04 days', '04 Days'), ('05 days', '05 Days'), ('06 days', '06 Days'), ('01 week', '01 Week'), ('02 week', '02 Weeks'), ('03 week', '03 Weeks'), ('01 month', '01 Month')], max_length=20, verbose_name='Est. Duration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to=settings.AUTH_USER_MODEL, verbose_name='Applicant')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.project', verbose_name='Project')),
            ],
        ),
    ]
