# Generated by Django 3.2.8 on 2023-06-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Approved'), ('rejected', 'Closed')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
