# Generated by Django 4.1.9 on 2023-09-21 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='team',
            field=models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='teams.team', verbose_name='Applicant Team'),
        ),
    ]
