# Generated by Django 3.2.8 on 2022-10-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20220913_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='estimated_duration',
            field=models.CharField(choices=[('01 day', '01 Day'), ('02 days', '02 Days'), ('03 days', '03 Days'), ('04 days', '04 Days'), ('05 days', '05 Days'), ('06 days', '06 Days'), ('01 week', '01 Week'), ('02 week', '02 Weeks'), ('03 week', '03 Weeks'), ('01 month', '01 Month')], max_length=20, verbose_name='Est. Duration'),
        ),
    ]
