# Generated by Django 3.2.8 on 2023-06-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20230607_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Approved'), ('closed', 'Closed')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
