# Generated by Django 3.2.8 on 2022-10-17 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_estimated_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='budget',
            field=models.IntegerField(default=10, error_messages={'budget': {'max_length': 'Set the budget amount between 10 and 50000 currency points'}}, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(70000)], verbose_name='Budget'),
        ),
    ]
