# Generated by Django 3.2.8 on 2022-05-24 22:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Reference Number')),
                ('available_balance', models.PositiveIntegerField(default=0, verbose_name='Account Balance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='clientfunduser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Account',
                'verbose_name_plural': 'Client Account',
            },
        ),
        migrations.CreateModel(
            name='ClientAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Deposit Narration')),
                ('stripe_order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stripe Order ID')),
                ('deposit_amount', models.PositiveIntegerField(default=0, verbose_name='Deposit Amount')),
                ('deposit_fee', models.PositiveIntegerField(default=0, verbose_name='Deposit Fee')),
                ('reference', models.CharField(max_length=100, verbose_name='Reference')),
                ('status', models.BooleanField(choices=[(False, 'Failed'), (True, 'Success')], default=False, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientfundaccount', to='client.clientaccount', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Client Action',
                'verbose_name_plural': 'Client Action',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='Gender')),
                ('budget_per_hourly_rate', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(500)], verbose_name='Budget/Hourly')),
                ('tagline', models.CharField(blank=True, max_length=100, verbose_name='Tagline')),
                ('description', models.TextField(blank=True, error_messages={'name': {'max_length': 'A maximum of 2000 words required'}}, max_length=2000, verbose_name='Description')),
                ('brand_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Brand Name')),
                ('profile_photo', models.ImageField(default='client/avatar5.png', upload_to='client/', verbose_name='Profile Photo')),
                ('company_logo', models.ImageField(default='client/logo.png', upload_to='client/', verbose_name='Brand Logo')),
                ('banner_photo', models.ImageField(default='client/banner.png', upload_to='client/', verbose_name='Banner Photo')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Residence Address')),
                ('announcement', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Announcement')),
                ('business_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='general_settings.size', verbose_name='Business Size')),
                ('employees', models.ManyToManyField(blank=True, default=None, related_name='employeefreelancer', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ManyToManyField(related_name='clientskill', to='general_settings.Skill', verbose_name='skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
        ),
    ]
