# Generated by Django 3.2.8 on 2023-03-08 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_rename_user_merchant_merchant'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='merchant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='clientmerchant', to='account.merchant', verbose_name='Merchant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='merchant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='clientactmerchant', to='account.merchant', verbose_name='Merchant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientaction',
            name='merchant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='merchantaction', to='account.merchant', verbose_name='Merchant'),
            preserve_default=False,
        ),
    ]
