# Generated by Django 3.2.8 on 2022-07-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccount',
            name='debug_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Pending Balance'),
        ),
    ]
