# Generated by Django 4.1.9 on 2023-08-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_site_clientaccount_site_clientaction_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='site',
        ),
        migrations.RemoveField(
            model_name='clientaccount',
            name='site',
        ),
        migrations.RemoveField(
            model_name='clientaction',
            name='site',
        ),
    ]
