# Generated by Django 3.2.8 on 2022-08-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_clientaccount_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Client Deposit', 'verbose_name_plural': 'Client Deposits'},
        ),
        migrations.RemoveField(
            model_name='clientaction',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='clientaction',
            name='modified_on',
        ),
        migrations.RemoveField(
            model_name='clientaction',
            name='stripe_order_id',
        ),
        migrations.AddField(
            model_name='clientaction',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='clientaction',
            name='gateway',
            field=models.CharField(default='', max_length=20, verbose_name='Payment Method'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Requested On'),
        ),
        migrations.AlterField(
            model_name='clientaction',
            name='narration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Narration'),
        ),
        migrations.AlterField(
            model_name='clientaction',
            name='reference',
            field=models.CharField(blank=True, help_text='This is a unique number assigned for audit purposes', max_length=15, verbose_name='Ref Number'),
        ),
        migrations.AlterField(
            model_name='clientaction',
            name='status',
            field=models.BooleanField(choices=[(False, 'Failed'), (True, 'Paid')], default=False, verbose_name='Status'),
        ),
    ]
