# Generated by Django 3.2.8 on 2022-08-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20220823_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Deposited On'),
        ),
    ]
