# Generated by Django 3.2.8 on 2022-09-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_clientaction_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientaccount',
            options={'ordering': ('user__pk',), 'verbose_name': 'Client Account', 'verbose_name_plural': 'Client Account'},
        ),
        migrations.AlterModelOptions(
            name='clientaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Deposit Ejournal', 'verbose_name_plural': 'Deposit Ejournal'},
        ),
    ]
