# Generated by Django 3.2.8 on 2022-09-15 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0029_alter_testemail_test_email'),
        ('client', '0007_auto_20220914_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='budget_per_hourly_rate',
        ),
        migrations.AddField(
            model_name='client',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='general_settings.department', verbose_name='Department'),
        ),
    ]
