# Generated by Django 3.2.8 on 2022-09-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_clientaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaction',
            name='reference',
            field=models.CharField(blank=True, default=2, help_text='This is a unique number assigned for audit purposes', max_length=15, unique=True, verbose_name='Ref Number'),
            preserve_default=False,
        ),
    ]
