# Generated by Django 3.2.8 on 2022-09-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_clientaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaction',
            name='reference',
            field=models.CharField(blank=True, help_text='This is a unique number assigned for audit purposes', max_length=15, verbose_name='Ref Number'),
        ),
    ]
