# Generated by Django 3.2.8 on 2022-05-24 22:47

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'name': {'max_length': 'Title field must be unique for your individual projects'}}, help_text='Title field is Required', max_length=255, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('preview', models.TextField(error_messages={'name': {'max_length': 'Preview field is required'}}, max_length=250, verbose_name='Preview')),
                ('description', ckeditor.fields.RichTextField(error_messages={'name': {'max_length': 'Describe your proposal in details'}}, max_length=3500, verbose_name='Description')),
                ('service_level', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='basic', error_messages={'name': {'max_length': 'Service Level field is required'}}, max_length=20, verbose_name='Service Level')),
                ('project_type', models.CharField(choices=[('fixed', 'Fixed'), ('hourly', 'Hourly')], default='fixed', error_messages={'name': {'max_length': 'Project type field is required'}}, max_length=20, verbose_name='Project Type')),
                ('sample_link', models.URLField(blank=True, help_text='the link must be a verified url', max_length=2083, null=True, verbose_name='Sample Website')),
                ('rating', models.PositiveSmallIntegerField(choices=[(0, '☆☆☆☆☆'), (1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=0, verbose_name='Rating')),
                ('amount', models.IntegerField(default=5, error_messages={'name': {'max_length': 'Set the budget amount (eg.1000) excluding the currency sign'}}, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50000)], verbose_name='Budget')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('dura_converter', models.CharField(choices=[('01 day', '01 Day'), ('02 days', '02 Days'), ('03 days', '03 Days'), ('04 days', '04 Days'), ('05 days', '05 Days'), ('06 days', '06 Days'), ('01 week', '01 Week'), ('02 week', '02 Weeks'), ('03 week', '03 Weeks'), ('01 month', '01 Month')], default='01 day', max_length=100, verbose_name='Duration')),
                ('duration', models.DateTimeField(blank=True, help_text='deadline for project', verbose_name='Completion In')),
                ('published', models.BooleanField(choices=[(False, 'Unfeature'), (True, 'Feature')], default=False, verbose_name='Featured')),
                ('status', models.CharField(choices=[('review', 'Review'), ('active', 'Active'), ('ongoing', 'Ongoing'), ('archived', 'Archived')], default='review', max_length=20, verbose_name='Status')),
                ('specification', models.CharField(choices=[('onetime', 'One-Time'), ('full time', 'Full Time'), ('part time', 'Part Time')], default='full time', max_length=20, verbose_name='Specification')),
                ('reference', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Identifier')),
                ('category', models.ForeignKey(error_messages={'name': {'max_length': 'You need to set category before projects can be created'}}, on_delete=django.db.models.deletion.RESTRICT, related_name='projects', to='general_settings.category', verbose_name='Category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL, verbose_name='Project Author')),
                ('project_skill', models.ManyToManyField(to='general_settings.Skill', verbose_name='Project Skill')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectSkillRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_of_proficiency', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('expert', 'expert')], default='basic', help_text='Please select as appropriate', max_length=30, verbose_name='Proficiency level')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectskill', to='projects.project', verbose_name='Project')),
                ('skill', models.ManyToManyField(to='general_settings.Skill', verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Project Skill',
                'verbose_name_plural': 'Project Skills',
            },
        ),
        migrations.CreateModel(
            name='ProjectLanguageRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_language', models.CharField(max_length=30, verbose_name='Project Language')),
                ('level_of_proficiency', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('expert', 'expert')], default='basic', help_text='Please select as appropriate', max_length=30)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_settings.communicationlanguage', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Project Language',
                'verbose_name_plural': 'Project Language',
            },
        ),
    ]
