# Generated by Django 3.2.8 on 2023-05-14 18:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general_settings', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title field is Required', max_length=255, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('preview', models.CharField(error_messages={'name': {'max_length': 'Preview field is required with maximum of 250 characters'}}, max_length=255, verbose_name='Preview')),
                ('status', models.CharField(choices=[('review', 'Review'), ('active', 'Active'), ('modify', 'Modify'), ('archived', 'Archived')], default='review', max_length=20, verbose_name='Status')),
                ('description', models.TextField(error_messages={'name': {'max_length': 'Description field is required'}}, max_length=3500, verbose_name='Description')),
                ('dura_converter', models.CharField(choices=[('one_day', '01 Day'), ('two_days', '02 Days'), ('three_days', '03 Days'), ('four_days', '04 Days'), ('five_days', '05 Days'), ('six_days', '06 Days'), ('one_week', '01 Week'), ('two_weeks', '02 Weeks'), ('three_weeks', '03 Weeks'), ('one_month', '01 Month')], default='one_day', max_length=100, verbose_name='Deadline')),
                ('service_level', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='basic', error_messages={'name': {'max_length': 'Service Level field is required'}}, max_length=20, verbose_name='Service Level')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('published', models.BooleanField(choices=[(False, 'Unfeature'), (True, 'Feature')], default=False, verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('salary', models.IntegerField(default=10, error_messages={'amount': {'max_length': 'Set the budget amount between 10 and 50000 currency points'}}, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50000)], verbose_name='Price')),
                ('sample_link', models.URLField(blank=True, help_text='the link must be a verified url', max_length=2083, null=True, verbose_name='Sample Website')),
                ('rating', models.PositiveSmallIntegerField(choices=[(0, '☆☆☆☆☆'), (1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=0, verbose_name='Rating')),
                ('duration', models.DateTimeField(blank=True, help_text='deadline for expiration of project', null=True, verbose_name='Duration')),
                ('completion_time', models.CharField(choices=[('one_day', '01 Day'), ('two_days', '02 Days'), ('three_days', '03 Days'), ('four_days', '04 Days'), ('five_days', '05 Days'), ('six_days', '06 Days'), ('one_week', '01 Week'), ('two_weeks', '02 Weeks'), ('three_weeks', '03 Weeks'), ('one_month', '01 Month')], default='one_day', max_length=100, verbose_name='Completion In')),
                ('action', models.BooleanField(default=False, verbose_name='Action')),
                ('reopen_count', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Reopen Count')),
                ('category', models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.RESTRICT, to='general_settings.category', verbose_name='Category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.merchant', verbose_name='Merchant')),
                ('skill', models.ManyToManyField(error_messages={'name': {'max_length': 'Skill field is required'}}, to='general_settings.Skill', verbose_name='Proposal Skills')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ('-created_at',),
            },
            managers=[
                ('public', django.db.models.manager.Manager()),
            ],
        ),
    ]
