# Generated by Django 4.1.9 on 2023-08-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.PositiveIntegerField(choices=[(1, '01 Day'), (2, '02 Days'), (3, '03 Days'), (4, '04 Days'), (5, '05 Days'), (6, '06 Days'), (7, '01 Week'), (14, '02 Weeks'), (21, '03 Weeks'), (30, '01 Month')], default=3, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='revision',
            field=models.PositiveIntegerField(choices=[(1, '1 Time'), (2, '2 Times'), (3, '3 Times'), (4, '4 Times'), (5, '5 Times'), (6, '6 Times'), (7, '7 Times')], default=1, verbose_name='Revision'),
        ),
    ]
