# Generated by Django 3.2.8 on 2022-05-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completion_time',
            field=models.CharField(choices=[('01 day', '01 Day'), ('02 days', '02 Days'), ('03 days', '03 Days'), ('04 days', '04 Days'), ('05 days', '05 Days'), ('06 days', '06 Days'), ('01 week', '01 Week'), ('02 week', '02 Weeks'), ('03 week', '03 Weeks'), ('01 month', '01 Month')], default='01 day', max_length=100, verbose_name='Completion In'),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.DateTimeField(blank=True, help_text='deadline for project', verbose_name='Deadline'),
        ),
    ]
