# Generated by Django 3.2.8 on 2023-05-14 18:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='identifier',
            field=models.URLField(default=uuid.uuid4, verbose_name='Identifier'),
        ),
    ]
