# Generated by Django 4.1.9 on 2023-08-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_duration_alter_project_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completion_time',
            field=models.PositiveIntegerField(choices=[(1, '01 Day'), (2, '02 Days'), (3, '03 Days'), (4, '04 Days'), (5, '05 Days'), (6, '06 Days'), (7, '01 Week'), (14, '02 Weeks'), (21, '03 Weeks'), (30, '01 Month')], default=1, verbose_name='Completion In'),
        ),
    ]
