# Generated by Django 3.2.8 on 2023-06-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('review', 'Review'), ('active', 'Active'), ('modify', 'Modify'), ('archived', 'Archived')], default='active', max_length=20, verbose_name='Status'),
        ),
    ]
