# Generated by Django 4.1.9 on 2023-07-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='salary',
            field=models.IntegerField(error_messages={'amount': {'max_length': 'Set the salary for this proposal'}}, verbose_name='Price'),
        ),
    ]
