# Generated by Django 3.2.8 on 2022-06-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20220612_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.DateTimeField(blank=True, help_text='deadline for project', null=True, verbose_name='Duration'),
        ),
    ]
