# Generated by Django 4.1.9 on 2023-08-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='site',
        ),
    ]
