# Generated by Django 4.1.9 on 2023-08-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='reopen_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Reopen Count'),
        ),
    ]
