# Generated by Django 4.1.9 on 2023-08-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_country_flag'),
        ('projects', '0006_alter_project_reopen_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('slug', 'merchant')},
        ),
    ]
