# Generated by Django 3.2.8 on 2022-09-15 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20220622_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amount',
            field=models.IntegerField(default=10, error_messages={'name': {'max_length': 'Set the budget amount (eg.1000) excluding the currency sign'}}, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50000)], verbose_name='Budget'),
        ),
    ]
