# Generated by Django 3.2.8 on 2022-09-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.DateTimeField(blank=True, help_text='deadline for expiration of project', null=True, verbose_name='Duration'),
        ),
        migrations.DeleteModel(
            name='ProjectSkillRequired',
        ),
    ]
