# Generated by Django 3.2.8 on 2022-09-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='action',
            field=models.BooleanField(default=False, verbose_name='Action'),
        ),
    ]
