# Generated by Django 3.2.8 on 2022-09-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectLanguageRequired',
        ),
    ]
