# Generated by Django 3.2.8 on 2022-10-01 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_project_reopen_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='reopen_count',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Reopen Count'),
        ),
    ]
