# Generated by Django 3.2.8 on 2022-10-17 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_project_reopen_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amount',
            field=models.IntegerField(default=10, error_messages={'amount': {'max_length': 'Set the budget amount between 10 and 50000 currency points'}}, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50000)], verbose_name='Budget'),
        ),
    ]
