# DEPLOYMENT FOR FIRST TIME


name: Django Deployment

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx supervisor

      - name: Set up virtual environment
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
          script: |
            cd /webapps/trosgate/trosgate_env
            source bin/activate
            git pull
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic
            sudo cp /path/to/nginx.conf /etc/nginx/sites-available/
            sudo ln -s /etc/nginx/sites-available/nginx.conf /etc/nginx/sites-enabled/
            sudo cp /path/to/supervisor.conf /etc/supervisor/conf.d/
            sudo systemctl restart nginx
            sudo supervisorctl restart trosgate
