name: Django Deployment

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3 python3-pip python3-venv nginx supervisor -y
        sudo groupadd webapps
        sudo useradd -g webapps Katey
        mkdir /home/Katey/trosgate
        chown -R Katey:webapps /home/Katey/trosgate
        python3 -m venv /home/Katey/trosgate/trosgate_env
        source /home/Katey/trosgate/trosgate_env/bin/activate
        pip3 install -r /home/Katey/trosgate/trosgate-marketplace-script/requirements.txt
      
    - name: Build and test code
      run: |
        cd /home/Katey/trosgate/trosgate-marketplace-script
        python manage.py test
        python manage.py collectstatic
      
    - name: Deploy code to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: Katey
        password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
        script: |
          cd /home/Katey/trosgate/trosgate-marketplace-script
          git pull
          source /home/Katey/trosgate/trosgate_env/bin/activate
          pip3 install -r requirements.txt
          python manage.py migrate
          sudo supervisorctl restart trosgate:*
          sudo systemctl restart nginx 
