# Generated by Django 3.2.8 on 2022-05-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FutureRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.CharField(blank=True, default='Your future in your hands to control', max_length=100)),
                ('alert', models.CharField(blank=True, default='Some of these features require additional settings. Be guided by the comments', max_length=100)),
                ('more_team_per_user', models.BooleanField(blank=True, choices=[(False, 'Disabled'), (True, 'Launched')], default=True, help_text='By default, each freelancer is created with one Team. This feature enables freelancer to create unlimited Teams and invite user to any of them', verbose_name='More Teams per Freelancer')),
                ('ext_contract', models.BooleanField(blank=True, choices=[(False, 'Disabled'), (True, 'Launched')], default=True, help_text='This feature allows freelancer to add their own clients(from outside your platform). Then create contracts and link to those clients for them to receive mail and checkout without login', verbose_name='External Contract')),
                ('deposit', models.BooleanField(blank=True, choices=[(False, 'Disabled'), (True, 'Launched')], default=True, help_text='In addition to the generic flow where client will pay for services on the fly, this feature allows client to deposit first, and use it to purchase any service', verbose_name='Client Deposit')),
                ('transfer', models.BooleanField(blank=True, choices=[(False, 'Disabled'), (True, 'Launched')], default=True, help_text='By default, freelancer Team members must pay themselves outside platform. Team founder can take advantage of this Gift/Transfer feature to pay other Team members on platform', verbose_name='Gift/Transfer')),
                ('sms_authenticator', models.BooleanField(blank=True, choices=[(False, 'Disabled'), (True, 'Launched')], default=True, help_text='This will only work if you first setup Twilio credentials in dashboard under settings. If launched, freelancer and client will be required to verify login by SMS', verbose_name='2FA SMS Auth')),
            ],
            options={
                'verbose_name': 'Future Release',
                'verbose_name_plural': 'Future Releases',
            },
        ),
    ]
