# Generated by Django 4.1.9 on 2023-08-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FutureRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.CharField(blank=True, default='Your future in your hands to control', max_length=100)),
                ('alert', models.CharField(blank=True, default='Some of these features require additional settings. Be guided by the comments', max_length=100)),
                ('more_team_per_user', models.BooleanField(blank=True, choices=[(False, 'Disabled'), (True, 'Launched')], default=True, help_text='By default, each freelancer is created with single Team. Same team can be upgraded. This plugin enables freelancer to create unlimited Teams and invite user to any of them. Also, newly created team have ability to upgrade', verbose_name='Teams Builder Plus')),
                ('ext_contract', models.BooleanField(blank=True, choices=[(False, 'Disabled'), (True, 'Launched')], default=True, help_text='This feature allows freelancer to add their own clients(from outside your platform). Then create contracts and link to those clients for them to receive mail and checkout after signup', verbose_name='External Contract')),
                ('deposit', models.BooleanField(blank=True, choices=[(False, 'Disabled'), (True, 'Launched')], default=True, help_text='With direct checkout flow, client will pay for services on the fly(direct). This plugin allows client to deposit first, and use it to purchase any service within the platform', verbose_name='Client Deposit')),
                ('transfer', models.BooleanField(blank=True, choices=[(False, 'Disabled'), (True, 'Launched')], default=True, help_text='By default, service payments go to Team founder and freelancer Team members must pay themselves outside platform. If team is upgraded, Team founder can take advantage of this Plugin to pay other Team members on platform', verbose_name='Fund splitter/Transfer')),
                ('sms_authenticator', models.BooleanField(blank=True, choices=[(False, 'Disabled'), (True, 'Launched')], default=True, help_text='By default, all users(excluding Staff) will be able to login to dashoard using EMAIL and PASSWORD. This plugin will (1) Present extra Token form after login, (2) Send simple mail alert containingg token, (3) button to resend token if customer has not received, (4) Then a valid token entered will log user to dashboard', verbose_name='2FA Mailer')),
            ],
            options={
                'verbose_name': 'Plugin -Site',
                'verbose_name_plural': 'Plugins -Site',
            },
        ),
        migrations.CreateModel(
            name='PluginFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('preview', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Preview')),
                ('promo_image', models.ImageField(default='home_promo.jpg', upload_to='promo/', verbose_name='Promo Image')),
                ('feature1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Feature1')),
                ('feature2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Feature2')),
                ('feature3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Feature3')),
                ('feature4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Feature4')),
                ('feature5', models.CharField(blank=True, max_length=255, null=True, verbose_name='Feature5')),
                ('feature6', models.CharField(blank=True, max_length=255, null=True, verbose_name='Feature6')),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Plugin Feature',
                'verbose_name_plural': 'Plugins Features',
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('preview', models.TextField(max_length=750, verbose_name='Preview')),
                ('description', models.TextField(max_length=3500, verbose_name='Description')),
                ('mode', models.BooleanField(choices=[(False, 'One Time'), (True, 'Monthly')], default=False, verbose_name='Payment Mode')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('feature', models.ManyToManyField(related_name='features', to='future.pluginfeature', verbose_name='Plugin feature')),
            ],
            options={
                'verbose_name': 'Plugin - Merchant',
                'verbose_name_plural': 'Plugins - Merchant',
                'ordering': ('ordering',),
            },
        ),
    ]
