# Generated by Django 4.1.9 on 2023-07-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('preview', models.CharField(default='Your future in your hands to control', max_length=100)),
                ('description', models.TextField(max_length=3500, verbose_name='Description')),
                ('promo_image', models.ImageField(default='home_promo.jpg', upload_to='promo/', verbose_name='Promo Image')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Plugin - Merchant',
                'verbose_name_plural': 'Plugins - Merchant',
                'ordering': ('ordering',),
            },
        ),
        migrations.AlterModelOptions(
            name='futurerelease',
            options={'verbose_name': 'Plugin -Site', 'verbose_name_plural': 'Plugins -Site'},
        ),
    ]
