# Generated by Django 4.1.9 on 2023-07-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future', '0002_plugin_alter_futurerelease_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='preview',
            field=models.TextField(max_length=350, verbose_name='Preview'),
        ),
    ]
