# Generated by Django 4.1.9 on 2023-07-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future', '0003_alter_plugin_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='mode',
            field=models.BooleanField(choices=[(False, 'One Time'), (True, 'Monthly')], default=False, verbose_name='Payment Mode'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='preview',
            field=models.TextField(max_length=750, verbose_name='Preview'),
        ),
    ]
