# Generated by Django 3.2.8 on 2022-09-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future', '0003_auto_20220916_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurerelease',
            name='more_team_per_user',
            field=models.BooleanField(blank=True, choices=[(False, 'Disabled'), (True, 'Launched')], default=True, help_text='By default, each freelancer is created with single Team. Same team can be upgraded. This plugin enables freelancer to create unlimited Teams and invite user to any of them. Also, newly created team have ability to upgrade', verbose_name='Teams Builder Plus'),
        ),
    ]
