# Generated by Django 4.1.9 on 2023-07-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future', '0004_plugin_mode_alter_plugin_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('preview', models.TextField(blank=True, max_length=100, null=True, verbose_name='Preview')),
                ('promo_image', models.ImageField(default='home_promo.jpg', upload_to='promo/', verbose_name='Promo Image')),
                ('feature1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Feature1')),
                ('feature2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Feature2')),
                ('feature3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Feature3')),
                ('feature4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Feature4')),
                ('feature5', models.CharField(blank=True, max_length=255, null=True, verbose_name='Feature5')),
                ('feature6', models.CharField(blank=True, max_length=255, null=True, verbose_name='Feature6')),
            ],
        ),
        migrations.RemoveField(
            model_name='plugin',
            name='promo_image',
        ),
        migrations.AddField(
            model_name='plugin',
            name='feature',
            field=models.ManyToManyField(related_name='features', to='future.pluginfeature', verbose_name='Plugin feature'),
        ),
    ]
