# Generated by Django 4.1.9 on 2023-07-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future', '0005_pluginfeature_remove_plugin_promo_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pluginfeature',
            options={'ordering': ('ordering',), 'verbose_name': 'Plugin Feature', 'verbose_name_plural': 'Plugins Features'},
        ),
        migrations.AddField(
            model_name='pluginfeature',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
