# Generated by Django 4.1.9 on 2023-07-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future', '0007_alter_pluginfeature_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginfeature',
            name='preview',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Preview'),
        ),
    ]
