# Generated by Django 3.2.8 on 2023-05-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='Statistics data on website visitors', max_length=100, null=True, verbose_name='NewStats')),
                ('win', models.PositiveIntegerField(default=0, help_text='To track, resolve all the values to zero to start tracking visitors')),
                ('mac', models.PositiveIntegerField(default=0, help_text='To track, resolve all the values to zero to start tracking visitors')),
                ('iph', models.PositiveIntegerField(default=0, help_text='To track, resolve all the values to zero to start tracking visitors')),
                ('android', models.PositiveIntegerField(default=0, help_text='To track, resolve all the values to zero to start tracking visitors')),
                ('oth', models.PositiveIntegerField(default=0, help_text='To track, resolve all the values to zero to start tracking visitors')),
            ],
            options={
                'verbose_name': 'Site Visitor Statistics',
                'verbose_name_plural': 'Site Visitor Statistics',
            },
        ),
    ]
