# Generated by Django 3.2.8 on 2022-05-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='Statistics data on website visitors', max_length=100, null=True, verbose_name='NewStats')),
                ('win', models.PositiveIntegerField(help_text='To track, resolve all the values to zero to start tracking visitors')),
                ('mac', models.PositiveIntegerField(help_text='To track, resolve all the values to zero to start tracking visitors')),
                ('iph', models.PositiveIntegerField(help_text='To track, resolve all the values to zero to start tracking visitors')),
                ('android', models.PositiveIntegerField(help_text='To track, resolve all the values to zero to start tracking visitors')),
                ('oth', models.PositiveIntegerField(help_text='To track, resolve all the values to zero to start tracking visitors')),
            ],
            options={
                'verbose_name': 'NewStats',
                'verbose_name_plural': 'NewStats',
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='Statistics data on project', max_length=100, null=True, verbose_name='Description')),
                ('active', models.PositiveIntegerField(blank=True, null=True)),
                ('review', models.PositiveIntegerField(blank=True, null=True)),
                ('ongoing', models.PositiveIntegerField(blank=True, null=True)),
                ('archived', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Projects Status',
                'verbose_name_plural': 'Projects Status',
            },
        ),
    ]
