# Generated by Django 4.1.9 on 2023-09-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('account', '0002_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Project Applicant Paid',
                'verbose_name_plural': 'Project Applicant Paid',
                'ordering': ('-created_at',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transactions.applicationsale',),
        ),
        migrations.CreateModel(
            name='SuccessInternalContract',
            fields=[
            ],
            options={
                'verbose_name': 'Internal Contracts Paid',
                'verbose_name_plural': 'Internal Contracts Paid',
                'ordering': ('-created_at',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transactions.contractsale',),
        ),
        migrations.CreateModel(
            name='SuccessProposal',
            fields=[
            ],
            options={
                'verbose_name': 'Proposal Paid',
                'verbose_name_plural': 'Proposal Paid',
                'ordering': ('-created_at',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transactions.proposalsale',),
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
            ],
            options={
                'verbose_name': 'User Statistics',
                'verbose_name_plural': 'User Statistics',
                'ordering': ('date_joined',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.customer',),
        ),
    ]
