# Generated by Django 3.2.8 on 2023-04-23 18:41

import django.contrib.sites.managers
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('transactions', '0001_initial'),
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Project Applicant Paid',
                'verbose_name_plural': 'Project Applicant Paid',
                'ordering': ('-created_at',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transactions.applicationsale',),
        ),
        migrations.CreateModel(
            name='SuccessInternalContract',
            fields=[
            ],
            options={
                'verbose_name': 'Internal Contracts Paid',
                'verbose_name_plural': 'Internal Contracts Paid',
                'ordering': ('-created_at',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transactions.contractsale',),
        ),
        migrations.CreateModel(
            name='SuccessProposal',
            fields=[
            ],
            options={
                'verbose_name': 'Proposal Paid',
                'verbose_name_plural': 'Proposal Paid',
                'ordering': ('-created_at',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transactions.proposalsale',),
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
            ],
            options={
                'verbose_name': 'User Statistics',
                'verbose_name_plural': 'User Statistics',
                'ordering': ('date_joined',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.customer',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('merchants', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
