# Generated by Django 3.2.8 on 2022-09-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newstats',
            options={'verbose_name': 'Visitor Stats', 'verbose_name_plural': 'Visitor Stats'},
        ),
    ]
