# Generated by Django 3.2.8 on 2022-09-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_newstats_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectStatus',
        ),
    ]
