# Generated by Django 3.2.8 on 2022-09-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_auto_20220907_2157'),
        ('analytics', '0003_delete_projectstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessProposal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transactions.proposalsale',),
        ),
    ]
