# Generated by Django 3.2.8 on 2022-09-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_auto_20220907_2157'),
        ('analytics', '0004_successproposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessApplication',
            fields=[
            ],
            options={
                'verbose_name': 'Success Applicant Hire',
                'verbose_name_plural': 'Success Applicant Hire',
                'ordering': ('-created_at',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transactions.applicationsale',),
        ),
        migrations.AlterModelOptions(
            name='successproposal',
            options={'ordering': ('-created_at',), 'verbose_name': 'Success Proposal', 'verbose_name_plural': 'Success Proposals'},
        ),
    ]
