# Generated by Django 3.2.8 on 2022-09-09 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_auto_20220907_2157'),
        ('analytics', '0005_auto_20220909_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessContract',
            fields=[
            ],
            options={
                'verbose_name': 'Internal Contracts Paid',
                'verbose_name_plural': 'Internal Contracts Paid',
                'ordering': ('-created_at',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transactions.applicationsale',),
        ),
        migrations.AlterModelOptions(
            name='successapplication',
            options={'ordering': ('-created_at',), 'verbose_name': 'Applicant Hired', 'verbose_name_plural': 'Applicant Hired'},
        ),
        migrations.AlterModelOptions(
            name='successproposal',
            options={'ordering': ('-created_at',), 'verbose_name': 'Proposal Paid', 'verbose_name_plural': 'Success Paid'},
        ),
    ]
