# Generated by Django 3.2.8 on 2022-09-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_auto_20220907_2157'),
        ('analytics', '0006_auto_20220909_2056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuccessContract',
        ),
        migrations.CreateModel(
            name='SuccessInternalContract',
            fields=[
            ],
            options={
                'verbose_name': 'Internal Contracts Paid',
                'verbose_name_plural': 'Internal Contracts Paid',
                'ordering': ('-created_at',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transactions.contractsale',),
        ),
    ]
