# Generated by Django 3.2.8 on 2022-09-09 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_twofactorauth_pass_code'),
        ('analytics', '0007_auto_20220909_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
            ],
            options={
                'verbose_name': 'User Statistics',
                'verbose_name_plural': 'User Statistics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.customer',),
        ),
        migrations.AlterModelOptions(
            name='newstats',
            options={'verbose_name': 'Site Visitor Statistics', 'verbose_name_plural': 'Site Visitor Statistics'},
        ),
        migrations.AlterModelOptions(
            name='successapplication',
            options={'ordering': ('-created_at',), 'verbose_name': 'Project Applicant Paid', 'verbose_name_plural': 'Project Applicant Paid'},
        ),
        migrations.AlterModelOptions(
            name='successproposal',
            options={'ordering': ('-created_at',), 'verbose_name': 'Proposal Paid', 'verbose_name_plural': 'Proposal Paid'},
        ),
    ]
