# Generated by Django 3.2.8 on 2022-09-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_auto_20220909_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstatistics',
            options={'ordering': ('date_joined',), 'verbose_name': 'User Statistics', 'verbose_name_plural': 'User Statistics'},
        ),
    ]
