# Generated by Django 3.2.8 on 2022-10-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_alter_userstatistics_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstats',
            name='android',
            field=models.PositiveIntegerField(default=0, help_text='To track, resolve all the values to zero to start tracking visitors'),
        ),
        migrations.AlterField(
            model_name='newstats',
            name='iph',
            field=models.PositiveIntegerField(default=0, help_text='To track, resolve all the values to zero to start tracking visitors'),
        ),
        migrations.AlterField(
            model_name='newstats',
            name='mac',
            field=models.PositiveIntegerField(default=0, help_text='To track, resolve all the values to zero to start tracking visitors'),
        ),
        migrations.AlterField(
            model_name='newstats',
            name='oth',
            field=models.PositiveIntegerField(default=0, help_text='To track, resolve all the values to zero to start tracking visitors'),
        ),
        migrations.AlterField(
            model_name='newstats',
            name='win',
            field=models.PositiveIntegerField(default=0, help_text='To track, resolve all the values to zero to start tracking visitors'),
        ),
    ]
