name: Django Deployment

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3 python3-pip python3-venv nginx supervisor -y
        python3 -m venv trosgate_env
        source trosgate_env/bin/activate
        pip3 install -r requirements.txt
      
    - name: Build and test code
      run: |
        python manage.py test
        python manage.py collectstatic
      
    - name: Deploy code to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: katey
        password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
        script: |
          cd /home/Katey/trosgate
          git pull
          source trosgate_env/bin/activate
          pip3 install -r requirements.txt
          python manage.py migrate
          sudo supervisorctl restart gunicorn
          sudo systemctl restart nginx
