# Generated by Django 4.1.9 on 2023-08-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_message_site_room_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='site',
        ),
        migrations.RemoveField(
            model_name='room',
            name='site',
        ),
    ]
