# Generated by Django 3.2.8 on 2023-06-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='page_name',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('closed', 'Closed')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
