# Generated by Django 3.2.8 on 2023-06-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20230613_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='page_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('closed', 'Closed')], default='waiting', max_length=20),
        ),
    ]
