# Generated by Django 3.2.8 on 2023-04-23 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500, verbose_name='Answer Option')),
                ('is_correct', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='Quiz Master')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('marks', models.PositiveIntegerField(verbose_name='Marks')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('answers', models.ManyToManyField(related_name='questions', to='quiz.Answer', verbose_name='Answers')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Quiz Master')),
            ],
        ),
        migrations.CreateModel(
            name='Quizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('instruction', models.TextField(verbose_name='Instruction')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created On')),
                ('attempts', models.PositiveIntegerField(verbose_name='Attempt')),
                ('duration', models.PositiveIntegerField(verbose_name='Duration(Min)')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('is_published', models.BooleanField(choices=[(False, 'Private'), (True, 'Public')], default=False, verbose_name='Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizmaster', to=settings.AUTH_USER_MODEL, verbose_name='Quiz Master')),
                ('questions', models.ManyToManyField(related_name='quizes', to='quiz.Question', verbose_name='questions')),
                ('skills', models.ManyToManyField(related_name='quizskills', to='general_settings.Skill', verbose_name='Required Skills')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='Score')),
                ('completed', models.DateTimeField(auto_now_add=True, verbose_name='Completed On')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myparticipants', to=settings.AUTH_USER_MODEL, verbose_name='Quiz Master')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='quiz.quizes', verbose_name='Quiz Name')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myattemptanswer', to='quiz.answer', verbose_name='Answer')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myattemptpaticipant', to='quiz.participant', verbose_name='Participant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myattemptquestion', to='quiz.question', verbose_name='Question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myattemptquiz', to='quiz.quizes', verbose_name='Quiz')),
            ],
        ),
    ]
