# Generated by Django 3.2.8 on 2022-05-24 22:47

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title field is Required', max_length=255, unique=True, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, help_text='subtitle field is optional with length of 200 characters', max_length=200, null=True, verbose_name='Subtitle')),
                ('preview', models.TextField(default=None, help_text='preview max length is 1000', max_length=1000, verbose_name='Preview')),
                ('is_published', models.BooleanField(choices=[(False, 'Private'), (True, 'Public')], default=False, verbose_name='Show/Hide')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('thumbnail', models.ImageField(blank=True, default='default-thumbnail.jpg', help_text="image must be any of these 'JPEG','JPG','PNG','PSD', and dimension 820x312", null=True, upload_to='howitworks/thumbnail', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPG', 'JPEG', 'PNG', 'PSD'])], verbose_name='Proposal Thumbnail')),
                ('backlink', models.URLField(blank=True, help_text="This Optional link will be placed after the last word of 'preview'", max_length=2083, null=True, verbose_name='Back link')),
                ('option_one', models.CharField(blank=True, max_length=100, null=True, verbose_name='Option #1')),
                ('option_one_description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Option #1 Description')),
                ('option_two', models.CharField(blank=True, max_length=100, null=True, verbose_name='Option #2')),
                ('option_two_description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Option #2 Description')),
                ('option_three', models.CharField(blank=True, max_length=100, null=True, verbose_name='Option #3')),
                ('option_three_description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Option #3 Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'How it Works - Freelancing',
                'verbose_name_plural': 'How it Works - Freelancing',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Hiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title field is Required', max_length=255, unique=True, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, help_text='subtitle field is optional with length of 200 characters', max_length=200, null=True, verbose_name='Subtitle')),
                ('preview', models.TextField(default=None, help_text='preview max length is 1000', max_length=1000, verbose_name='Preview')),
                ('is_published', models.BooleanField(choices=[(False, 'Private'), (True, 'Public')], default=False, verbose_name='Show/Hide')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('thumbnail', models.ImageField(blank=True, default='default-thumbnail.jpg', help_text="image must be any of these 'JPEG','JPG','PNG','PSD', and dimension 820x312", null=True, upload_to='howitworks/thumbnail', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPG', 'JPEG', 'PNG', 'PSD'])], verbose_name='Proposal Thumbnail')),
                ('backlink', models.URLField(blank=True, help_text="This Optional link will be placed after the last word of 'preview'", max_length=1000, null=True, verbose_name='Back link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('ordering', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order Priority')),
            ],
            options={
                'verbose_name': 'How it Works - Hiring',
                'verbose_name_plural': 'How it Works - Hiring',
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Title field is Required', max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(help_text='Email field is Required', max_length=100, unique=True, verbose_name='Email')),
                ('availability1', models.DateTimeField(blank=True, help_text='Times we can call you', null=True, verbose_name='Availability One')),
                ('availability2', models.DateTimeField(blank=True, help_text='Times to call you', null=True, verbose_name='Availability Two')),
                ('availability3', models.DateTimeField(blank=True, help_text='Times to call you', null=True, verbose_name='Availability Three')),
                ('comment', models.TextField(blank=True, help_text='Any comment you have', max_length=500, null=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title field is Required', max_length=255, unique=True, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, help_text='subtitle field is optional with length of 200 characters', max_length=200, null=True, verbose_name='Subtitle')),
                ('preview', models.TextField(default=None, help_text='preview max length is 1000', max_length=1000, verbose_name='Preview')),
                ('is_published', models.BooleanField(choices=[(False, 'Private'), (True, 'Public')], default=False, verbose_name='Show/Hide')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('thumbnail', models.ImageField(blank=True, default='default-thumbnail.jpg', help_text="image must be any of these 'JPEG','JPG','PNG','PSD', and dimension 820x312", null=True, upload_to='howitworks/thumbnail', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPG', 'JPEG', 'PNG', 'PSD'])], verbose_name='Proposal Thumbnail')),
                ('backlink', models.URLField(blank=True, help_text="This Optional link will be placed after the last word of 'preview'", max_length=2083, null=True, verbose_name='Back link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'How it Works - Sponsorship',
                'verbose_name_plural': 'How it Works - Sponsorship',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title field is Required', max_length=255, unique=True, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(help_text='Description max length is 3500', max_length=3500, verbose_name='Description')),
                ('is_published', models.BooleanField(choices=[(False, 'Private'), (True, 'Public')], default=False, verbose_name='Show/Hide')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('ordering', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order Priority')),
            ],
            options={
                'verbose_name': 'T & C',
                'verbose_name_plural': 'T & C',
                'ordering': ('ordering',),
            },
        ),
    ]
