# Generated by Django 3.2.8 on 2022-08-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiring',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='Order Priority'),
        ),
    ]
