# Generated by Django 3.2.8 on 2023-04-07 18:17

import django.contrib.sites.managers
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='termsandconditions',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('tenants', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
