# Generated by Django 3.2.8 on 2022-10-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_hiring_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandconditions',
            name='quote',
            field=models.TextField(blank=True, help_text='This optional text will appear at the top of Description', max_length=350, null=True, verbose_name='Quote'),
        ),
    ]
