# Generated by Django 3.2.8 on 2022-10-16 00:11

import django.core.validators
from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_termsandconditions_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title field is Required', max_length=255, unique=True, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, help_text='subtitle field is optional with length of 200 characters', max_length=200, null=True, verbose_name='Subtitle')),
                ('description', models.TextField(default='This is the description of the about page This is the description of the about page This is the description of the about page This is the description of the about page', help_text='Description max length is 3500', max_length=3500, verbose_name='Description')),
                ('banner_type', models.BooleanField(choices=[(True, 'Activate Video'), (False, 'Activate Banner')], default=False, verbose_name='Media Switch')),
                ('video_url', models.URLField(blank=True, null=True, help_text='Your can Paste your Youtube or Vimeo video url here to embed. Only secured url allowed', verbose_name='Royal embed Video')),
                ('ad_image', models.ImageField(blank=True, help_text="image must be any of these: 'JPEG','JPG','PNG','PSD'", null=True, upload_to=pages.models.aboutus_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPG', 'JPEG', 'PNG', 'PSD'])], verbose_name='Ad Image')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('banner_color', models.CharField(blank=True, default='purple', help_text="Put your color here to decorate Banner Background and buttons like signup and login. Example '3F0F8FF', or 'red' or 'blue' or 'purple' or any css color code. Warning!: Donnot add quotation marks around the color attributes", max_length=100, null=True, verbose_name='Banner Background Color')),
                ('banner_button_one_color', models.CharField(blank=True, default='green', help_text="Put your bootstrap color here to decorate Banner Button 1. Example 'primary' or 'secondary' or 'light' or 'success' . Warning!: Exclude quotation marks when you input color attributes", max_length=100, null=True, verbose_name='Banner Button1 Color')),
                ('banner_button_two_color', models.CharField(blank=True, default='light', help_text="Put your bootstrap color here to decorate Banner Button 2. Example 'primary' or 'secondary' or 'light' or 'success' . Warning!: Exclude quotation marks when you input color attributes", max_length=100, null=True, verbose_name='Banner Button2 Color')),
                ('banner_image', models.ImageField(blank=True, help_text="image must be any of these: 'JPEG','JPG','PNG','PSD'", null=True, upload_to=pages.models.aboutus_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPG', 'JPEG', 'PNG', 'PSD'])], verbose_name='Hero Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'About Us Page',
                'verbose_name_plural': 'About Us Page',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='termsandconditions',
            options={'ordering': ('ordering',), 'verbose_name': 'Terms of Service', 'verbose_name_plural': 'Terms of Service'},
        ),
    ]
