# Generated by Django 3.2.8 on 2022-10-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20221016_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspage',
            name='subtitle_block',
            field=models.CharField(default='Consectetur adipisicing elit sed dotem eiusmod tempor incuntes ut labore etdolore maigna aliqua enim.', max_length=150, verbose_name='Banner Subtitle'),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='title_block',
            field=models.CharField(default='Hire Experts or Team', max_length=100, verbose_name='Banner Title'),
        ),
    ]
