# Generated by Django 3.2.8 on 2022-10-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20221016_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspage',
            name='display_stats',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Display Stats'),
        ),
    ]
