# Generated by Django 3.2.8 on 2022-10-16 15:29

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20221016_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('sir', 'Sir'), ('miss', 'Miss'), ('hon', 'Hon'), ('dr', 'Dr.'), ('prof', 'Prof')], default='mr', help_text='How would you like us to address you?', max_length=10, verbose_name='Title')),
                ('name', django_cryptography.fields.encrypt(models.CharField(max_length=150, verbose_name='Full Name'))),
                ('email', django_cryptography.fields.encrypt(models.EmailField(max_length=150, verbose_name='Email'))),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('accept_investors', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Accept Investor')),
            ],
            options={
                'verbose_name': 'Investors',
                'verbose_name_plural': 'Investors',
                'ordering': ('-created_at',),
            },
        ),
        # migrations.DeleteModel(
        #     name='Sponsor',
        # ),
        # migrations.DeleteModel(
        #     name='Sponsorship',
        # ),
    ]
