# Generated by Django 3.2.8 on 2022-10-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20221016_1529'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Sponsor',
        # ),
        # migrations.DeleteModel(
        #     name='Sponsorship',
        # ),
        migrations.RemoveField(
            model_name='investor',
            name='accept_investors',
        ),
    ]
