# Generated by Django 3.2.8 on 2022-10-16 15:51

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20221016_1537'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Sponsor',
        # ),
        # migrations.DeleteModel(
        #     name='Sponsorship',
        # ),
        migrations.AddField(
            model_name='investor',
            name='pass_code',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='Access Token')),
        ),
        migrations.AlterField(
            model_name='investor',
            name='email',
            field=django_cryptography.fields.encrypt(models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
        ),
        migrations.AlterField(
            model_name='investor',
            name='name',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=150, null=True, verbose_name='Full Name')),
        ),
    ]
