# Generated by Django 3.2.8 on 2022-10-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20221016_1626'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Sponsor',
        # ),
        # migrations.DeleteModel(
        #     name='Sponsorship',
        # ),
        migrations.RemoveField(
            model_name='investor',
            name='status',
        ),
        migrations.AddField(
            model_name='investor',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
    ]
