# Generated by Django 3.2.8 on 2022-10-16 16:42

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20221016_1632'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Sponsor',
        # ),
        # migrations.DeleteModel(
        #     name='Sponsorship',
        # ),
        migrations.AlterField(
            model_name='investor',
            name='email',
            field=django_cryptography.fields.encrypt(models.EmailField(default='a@a.com', max_length=150, unique=True, verbose_name='Email')),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investor',
            name='name',
            field=django_cryptography.fields.encrypt(models.CharField(default='sample man', max_length=150, verbose_name='Full Name')),
            preserve_default=False,
        ),
    ]
