# Generated by Django 3.2.8 on 2022-10-16 19:11

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20221016_1642'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Sponsor',
        # ),
        # migrations.DeleteModel(
        #     name='Sponsorship',
        # ),
        migrations.AddField(
            model_name='investor',
            name='confirm_email',
            field=django_cryptography.fields.encrypt(models.EmailField(default='a@ab.com', max_length=100, unique=True, verbose_name='Confirm Email')),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investor',
            name='email',
            field=django_cryptography.fields.encrypt(models.EmailField(max_length=100, unique=True, verbose_name='Email')),
        ),
        migrations.AlterField(
            model_name='investor',
            name='name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100, verbose_name='Full Name')),
        ),
    ]
