# Generated by Django 3.2.8 on 2022-10-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20221016_1911'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Sponsor',
        # ),
        # migrations.DeleteModel(
        #     name='Sponsorship',
        # ),
        migrations.RemoveField(
            model_name='investor',
            name='confirm_email',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='name',
        ),
        migrations.AddField(
            model_name='investor',
            name='myconfirm_email',
            field=models.EmailField(default='a@a.com', max_length=100, verbose_name='Confirm Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='myemail',
            field=models.EmailField(default='a@a.com', max_length=100, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='myname',
            field=models.CharField(default='aa@a.com', max_length=100, verbose_name='Full Name'),
            preserve_default=False,
        ),
    ]
