# Generated by Django 3.2.8 on 2022-10-16 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20221016_2121'),
    ]

    # operations = [
    #     migrations.DeleteModel(
    #         name='Sponsor',
    #     ),
    #     migrations.DeleteModel(
    #         name='Sponsorship',
    #     ),
    # ]
