# Generated by Django 3.2.8 on 2022-10-22 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20221016_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutuspage',
            name='video_url',
        ),
    ]
