# Generated by Django 3.2.8 on 2022-10-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_remove_aboutuspage_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspage',
            name='video_url',
            field=models.URLField(blank=True, help_text='Enter the full path to your video url on youtube or vimeo etc', max_length=2083, null=True, verbose_name='Embed Video Url'),
        ),
    ]
