# Generated by Django 3.2.8 on 2022-06-26 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_rename_razorpay_subbscription_id_team_razorpay_subscription_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title field is Required', max_length=150, verbose_name='Title')),
                ('content', models.TextField(max_length=500, verbose_name='Message')),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('query_type', models.CharField(choices=[('proposal', 'Proposal'), ('project', 'Project'), ('active', 'Contract')], default=None, max_length=20, verbose_name='Query Type')),
                ('query_type_reference', models.CharField(help_text='Reference for the Query type selected', max_length=20, verbose_name='Query Reference')),
                ('states', models.CharField(choices=[('open', 'Open'), ('review', 'Review'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='Query Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('assisted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminsupport', to=settings.AUTH_USER_MODEL, verbose_name='Support Team')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportersupport', to=settings.AUTH_USER_MODEL, verbose_name='Reporter')),
                ('team', models.ForeignKey(blank=True, help_text='Only Applicable to Freelancer Queries', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporterteam', to='teams.team', verbose_name='Team')),
            ],
        ),
    ]
