# Generated by Django 3.2.8 on 2022-08-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20220824_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='supported_by',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='query_type',
            field=models.CharField(choices=[('general_enquiry', '1. General Enquiry'), ('signup_challenge', '2. Signin/Signup Issues'), ('password_reset', '3. Password Reset'), ('team_invite_issue', '4. Team Invitation Issues'), ('team_dispute', '5. Team Members Dispute'), ('quiz_q_and_a_issue', '6. Quiz, Q&A Issues'), ('checkou_issue', '7. Checkout Challenge'), ('Account_payout_issues', '8. Payout Account Issue'), ('fees_and_charges', '9. Fees and Over-Charges'), ('review_approval_issues', '10. Order Review/Approval'), ('order_cancellation_issues', '11. Order Cancellation'), ('credit_payment_challenge', '12. Freelancer Credit'), ('proposal_issue', '13. Proposal Issues'), ('project_issue', '14. Project Issues'), ('contract_issue', '15. Contract Issues'), ('deposit_challenge', '16. Deposit Challenge'), ('withdrawal_challenge', '17. Withdrawal Challenge'), ('transfer_challenge', '18. Transfer Challenge'), ('system_bug', '19. Reporting System Bug'), ('other_issues', '20. Other Issues')], default='general_enquiry', max_length=50, verbose_name='Query Type'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='states',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('reopen', 'RE-OPEN')], default='active', max_length=20, verbose_name='Status'),
        ),
    ]
