# Generated by Django 3.2.8 on 2022-08-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_auto_20220824_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='content',
            field=models.TextField(max_length=2000, verbose_name='Message'),
        ),
    ]
