# Generated by Django 3.2.8 on 2022-08-25 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_auto_20220825_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketClone',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('marketing.ticket',),
        ),
    ]
