# Generated by Django 3.2.8 on 2022-08-25 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_ticketclone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickettracker', to='marketing.ticket', verbose_name='Ticket'),
        ),
    ]
