# Generated by Django 3.2.8 on 2022-08-25 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0009_alter_ticketmessage_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketClone',
        ),
        migrations.RemoveField(
            model_name='ticketmessage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ticketmessage',
            name='supported_by',
        ),
        migrations.AddField(
            model_name='ticket',
            name='supported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticketsupport', to=settings.AUTH_USER_MODEL, verbose_name='Support'),
        ),
    ]
