# Generated by Django 3.2.8 on 2022-08-25 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0012_ticket_support'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Ticket Reply', 'verbose_name_plural': 'Ticket Replies'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firstticketsupport', to=settings.AUTH_USER_MODEL, verbose_name='Current Support'),
        ),
    ]
