# Generated by Django 3.2.8 on 2022-08-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0013_auto_20220825_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='link_title_one',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Helpful Article Title #1'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='link_title_one_backlink',
            field=models.URLField(blank=True, help_text="This Optional link will be placed in the mail to customer'", max_length=2083, null=True, verbose_name='Article Title #1 Backlink'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='link_title_three',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Helpful Article Title #3'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='link_title_three_backlink',
            field=models.URLField(blank=True, help_text="This Optional link will be placed in the mail to customer'", max_length=2083, null=True, verbose_name='Article Title #3 Backlink'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='link_title_two',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Helpful Article Title #2'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='link_title_two_backlink',
            field=models.URLField(blank=True, help_text="This Optional link will be placed in the mail to customer'", max_length=2083, null=True, verbose_name='Article Title #2 Backlink'),
        ),
    ]
