# Generated by Django 3.2.8 on 2022-08-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0014_auto_20220825_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmessage',
            name='link_title_three',
        ),
        migrations.RemoveField(
            model_name='ticketmessage',
            name='link_title_three_backlink',
        ),
    ]
