# Generated by Django 3.2.8 on 2022-08-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0015_auto_20220825_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='product_type_reference',
            field=models.CharField(blank=True, default='', help_text='Reference for the product type selected', max_length=50, verbose_name='Product Reference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reference',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Ticket #'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='states',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('reopen', 'Re-Open')], default='active', max_length=20, verbose_name='Status'),
        ),
    ]
