# Generated by Django 3.2.8 on 2022-08-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0016_auto_20220826_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
    ]
