# Generated by Django 3.2.8 on 2022-08-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0017_ticket_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='reference',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Ticket #'),
        ),
    ]
