# Generated by Django 3.2.8 on 2022-08-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0018_alter_ticket_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='product_type',
            field=models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('proposal', 'Proposal'), ('project', 'Project'), ('active', 'Contract')], default='Not Applicable', max_length=100, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='product_type_reference',
            field=models.CharField(blank=True, help_text='Reference for the product type selected', max_length=100, null=True, verbose_name='Product Reference'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='query_type',
            field=models.CharField(choices=[('general_enquiry', '1. General Enquiry'), ('signup_challenge', '2. Signin/Signup Issues'), ('password_reset', '3. Password Reset'), ('team_invite_issue', '4. Team Invitation Issues'), ('team_dispute', '5. Team Members Dispute'), ('quiz_q_and_a_issue', '6. Quiz, Q&A Issues'), ('checkou_issue', '7. Checkout Challenge'), ('Account_payout_issues', '8. Payout Account Issue'), ('fees_and_charges', '9. Fees and Over-Charges'), ('review_approval_issues', '10. Order Review/Approval'), ('order_cancellation_issues', '11. Order Cancellation'), ('credit_payment_challenge', '12. Freelancer Credit'), ('proposal_issue', '13. Proposal Issues'), ('project_issue', '14. Project Issues'), ('contract_issue', '15. Contract Issues'), ('deposit_challenge', '16. Deposit Challenge'), ('withdrawal_challenge', '17. Withdrawal Challenge'), ('transfer_challenge', '18. Transfer Challenge'), ('system_bug', '19. Reporting System Bug'), ('other_issues', '20. Other Issues')], default='general_enquiry', max_length=100, verbose_name='Query Type'),
        ),
    ]
