# Generated by Django 3.2.8 on 2022-08-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0021_auto_20220826_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='action',
            field=models.BooleanField(choices=[(False, 'Customer Replied'), (True, 'Admin Replied')], default=False, verbose_name='Default'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='states',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('reopen', 'Reopen')], default='active', max_length=20, verbose_name='Status'),
        ),
    ]
