# Generated by Django 3.2.8 on 2022-08-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0022_auto_20220827_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='action',
            field=models.BooleanField(choices=[(False, 'Customer Replied'), (True, 'Admin Replied')], default=True, verbose_name='Default'),
        ),
    ]
