# Generated by Django 3.2.8 on 2022-08-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0023_alter_ticketmessage_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='action',
            field=models.BooleanField(choices=[(False, 'Customer Replied'), (True, 'Admin Replied')], default=True, verbose_name='Action'),
        ),
    ]
