# Generated by Django 3.2.8 on 2022-09-14 17:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0024_alter_ticketmessage_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(error_messages={'name': {'max_length': 'Description field is required'}}, max_length=10000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='ordering',
            field=models.PositiveIntegerField(default=1, help_text='This determines how each package will appear to user eg, 1 means first position', verbose_name='Ordering'),
        ),
    ]
