# Generated by Django 3.2.8 on 2022-09-14 18:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0025_auto_20220914_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='introduction',
            field=models.TextField(blank=True, help_text='Optional- Must have a maximum of 350 words', max_length=300, null=True, verbose_name='Introduction'),
        ),
        migrations.AddField(
            model_name='blog',
            name='quote',
            field=models.CharField(blank=True, help_text='Optional-Must have a maximum of 200 words', max_length=300, null=True, verbose_name='Special Quote'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(error_messages={'name': {'max_length': 'Description field is required'}}, max_length=10000, verbose_name='Details'),
        ),
    ]
