# Generated by Django 3.2.8 on 2022-09-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0026_auto_20220914_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='default',
        ),
        migrations.AddField(
            model_name='announcement',
            name='ordering',
            field=models.PositiveIntegerField(default=1, help_text='This determines how each notice will appear to user eg, 1 means topmost position', verbose_name='Ordering'),
        ),
    ]
