# Generated by Django 3.2.8 on 2022-09-14 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0027_auto_20220914_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='content',
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(default=1, help_text='This blog will be removed if author is deleted', on_delete=django.db.models.deletion.CASCADE, related_name='announcer', to='account.customer', verbose_name='Publisher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='preview',
            field=models.TextField(default='this is a test', help_text='Preview of the blog must be unique - up to max of 255 words', max_length=350, verbose_name='Preview'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='this is title', help_text='title of the blog must be unique - up to max of 255 words', max_length=255, unique=True, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='backlink',
            field=models.URLField(blank=True, help_text="If this notice has detail page to read more, this Optional link will be placed after the last word of 'Preview' to send them there", max_length=2083, null=True, verbose_name='Target Url'),
        ),
    ]
