# Generated by Django 3.2.8 on 2022-09-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0028_auto_20220914_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-created_at',), 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcement'},
        ),
    ]
