# Generated by Django 3.2.8 on 2022-05-24 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0001_initial'),
        ('teams', '0001_initial'),
        ('proposals', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone Number')),
                ('country', models.CharField(blank=True, max_length=150, verbose_name='Country')),
                ('salary_paid', models.PositiveIntegerField(verbose_name='Salary Paid')),
                ('payment_method', models.CharField(blank=True, max_length=200, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='failed', max_length=10, verbose_name='Status')),
                ('unique_reference', models.CharField(blank=True, max_length=100, verbose_name='Unique Reference')),
                ('paypal_order_key', models.CharField(blank=True, max_length=200, verbose_name='PayPal Order Key')),
                ('flutterwave_order_key', models.CharField(blank=True, max_length=250, null=True, verbose_name='Flutterwave Order Key')),
                ('stripe_order_key', models.CharField(blank=True, max_length=250, null=True, verbose_name='Stripe Order Key')),
                ('razorpay_order_key', models.CharField(blank=True, max_length=250, null=True, verbose_name='Razorpay Order Key')),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='Razorpay Payment ID')),
                ('razorpay_signature', models.CharField(blank=True, max_length=250, null=True, verbose_name='Razorpay Signature')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ordered On')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modified On')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderclient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(blank=True, max_length=200, verbose_name='Payment Method')),
                ('price', models.PositiveIntegerField()),
                ('status', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Paid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ordered On')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modified On')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamsubscriber', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptionteam', to='teams.team', verbose_name='Team')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_category', models.CharField(blank=True, max_length=50, verbose_name='Sales Category')),
                ('sales_price', models.PositiveIntegerField(verbose_name='Total Sales')),
                ('total_sales_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Sales')),
                ('staff_hired', models.PositiveIntegerField(default=1, verbose_name='Total Staff Hired')),
                ('client_fee_charged', models.PositiveIntegerField(verbose_name='Client Fee')),
                ('freelancer_fee_charged', models.PositiveIntegerField(verbose_name='Freelancer Fee')),
                ('total_freelancer_fee_charged', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Freelancer Fee')),
                ('discount_offered', models.PositiveIntegerField(verbose_name='Discount Offered')),
                ('Total_discount_offered', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Discount')),
                ('earning', models.PositiveIntegerField(verbose_name='Earning')),
                ('total_earning', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Earning')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ordered On')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modified On')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totalpurchase', to='transactions.purchase', verbose_name='Purchased Client')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earningteam', to='teams.team', verbose_name='Team')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_price', models.PositiveIntegerField(verbose_name='Sales Price')),
                ('total_sales_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Proposal Salary')),
                ('staff_hired', models.PositiveIntegerField(default=1, verbose_name='Staff Hired')),
                ('earning_fee_charged', models.PositiveIntegerField(verbose_name='Earning Fee')),
                ('total_earning_fee_charged', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Earning Fee')),
                ('discount_offered', models.PositiveIntegerField(verbose_name='Discount Offered')),
                ('Total_discount_offered', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Discount')),
                ('earning', models.PositiveIntegerField(verbose_name='Earning')),
                ('total_earning', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Earning')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ordered On')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modified On')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposalhired', to='proposals.proposal', verbose_name='Proposal Hired')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposalsales', to='transactions.purchase', verbose_name='Purchase Client')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiredproposalteam', to='teams.team', verbose_name='Team')),
            ],
        ),
        migrations.CreateModel(
            name='ContractSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_price', models.PositiveIntegerField(verbose_name='Sales Price')),
                ('total_sales_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Contract Total')),
                ('staff_hired', models.PositiveIntegerField(default=1, verbose_name='Staff Hired')),
                ('earning_fee_charged', models.PositiveIntegerField(verbose_name='Earning Fee')),
                ('total_earning_fee_charged', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Earning Fee')),
                ('discount_offered', models.PositiveIntegerField(verbose_name='Discount Offered')),
                ('Total_discount_offered', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Discount')),
                ('earning', models.PositiveIntegerField(verbose_name='Earning')),
                ('total_earning', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Earning')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ordered On')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modified On')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracthired', to='contract.internalcontract', verbose_name='Contract Hired')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractsales', to='transactions.purchase', verbose_name='Purchase Client')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiredcontractteam', to='teams.team', verbose_name='Team')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_price', models.PositiveIntegerField(verbose_name='Sales Price')),
                ('total_sales_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Applicant Budget')),
                ('staff_hired', models.PositiveIntegerField(default=1, verbose_name='Staff Hired')),
                ('earning_fee_charged', models.PositiveIntegerField(verbose_name='Earning Fee')),
                ('total_earning_fee_charged', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Earning Fee')),
                ('discount_offered', models.PositiveIntegerField(verbose_name='Discount Offered')),
                ('Total_discount_offered', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Discount')),
                ('earning', models.PositiveIntegerField(verbose_name='Earning')),
                ('total_earnings', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Earning')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ordered On')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modified On')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicantprojectapplied', to='projects.project', verbose_name='Project Applied')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicantionsales', to='transactions.purchase', verbose_name='Purchase Client')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiredapplicantteam', to='teams.team', verbose_name='Team')),
            ],
        ),
    ]
