# Generated by Django 4.1.9 on 2023-10-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtContract',
        ),
    ]
