# Generated by Django 4.1.9 on 2023-08-27 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsale',
            name='site',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractsale',
            name='site',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extcontract',
            name='site',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='site',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposalsale',
            name='site',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='site',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='site',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
            preserve_default=False,
        ),
    ]
