# Generated by Django 3.2.8 on 2022-05-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationsale',
            old_name='Total_discount_offered',
            new_name='total_discount_offered',
        ),
        migrations.RenameField(
            model_name='contractsale',
            old_name='Total_discount_offered',
            new_name='total_discount_offered',
        ),
        migrations.RenameField(
            model_name='proposalsale',
            old_name='Total_discount_offered',
            new_name='total_discount_offered',
        ),
        migrations.RenameField(
            model_name='salesreporting',
            old_name='Total_discount_offered',
            new_name='total_discount_offered',
        ),
        migrations.AddField(
            model_name='applicationsale',
            name='disc_sales_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Discounted Salary'),
        ),
        migrations.AddField(
            model_name='contractsale',
            name='disc_sales_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Discounted Salary'),
        ),
        migrations.AddField(
            model_name='proposalsale',
            name='disc_sales_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Discounted Salary'),
        ),
        migrations.AddField(
            model_name='salesreporting',
            name='disc_sales_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Discounted Salary'),
        ),
        migrations.AlterField(
            model_name='proposalsale',
            name='total_sales_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Total Salary'),
        ),
    ]
