# Generated by Django 4.1.9 on 2023-11-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_delete_extcontract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionitem',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='subscriptionitem',
            name='team',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='SubscriptionItem',
        ),
    ]
