# Generated by Django 4.1.9 on 2023-08-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_applicationsale_site_contractsale_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationsale',
            name='site',
        ),
        migrations.RemoveField(
            model_name='contractsale',
            name='site',
        ),
        migrations.RemoveField(
            model_name='extcontract',
            name='site',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='site',
        ),
        migrations.RemoveField(
            model_name='proposalsale',
            name='site',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='site',
        ),
        migrations.RemoveField(
            model_name='subscriptionitem',
            name='site',
        ),
    ]
