# Generated by Django 3.2.8 on 2023-06-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20230605_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='country',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='email',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='phone',
        ),
    ]
