# Generated by Django 3.2.8 on 2022-06-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20220602_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Completed On'),
        ),
    ]
