# Generated by Django 4.1.9 on 2023-08-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_applicationsale_site_remove_contractsale_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsale',
            name='reference',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='contractsale',
            name='reference',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='extcontract',
            name='reference',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='proposalsale',
            name='reference',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
