# Generated by Django 3.2.8 on 2023-06-05 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0003_auto_20230605_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oneclickpurchase',
            name='reference',
        ),
        migrations.AddField(
            model_name='oneclickpurchase',
            name='unique_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Unique Reference'),
        ),
        migrations.AlterField(
            model_name='oneclickpurchase',
            name='category',
            field=models.CharField(choices=[('one_click', 'One Click'), ('proposal', 'Proposal'), ('project', 'Project'), ('contract', 'Contract'), ('excontract', 'Ex-Contract')], default='', max_length=20, verbose_name='Purchase Category'),
        ),
        migrations.AlterField(
            model_name='oneclickpurchase',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.CharField(choices=[('one_click', 'One Click'), ('proposal', 'Proposal'), ('project', 'Project'), ('contract', 'Contract'), ('excontract', 'Ex-Contract')], default='', max_length=20, verbose_name='Purchase Category'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
