# Generated by Django 3.2.8 on 2022-06-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_subscriptionitem_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionitem',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='activation_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Activation Time'),
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='expired_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Est. Expiration'),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Activation Time'),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Activation Time'),
        ),
    ]
