# Generated by Django 3.2.8 on 2023-06-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20230605_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsale',
            name='disc_sales_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Discounted Salary'),
        ),
        migrations.AlterField(
            model_name='applicationsale',
            name='earning',
            field=models.PositiveIntegerField(default=0, verbose_name='Earning'),
        ),
        migrations.AlterField(
            model_name='applicationsale',
            name='earning_fee_charged',
            field=models.PositiveIntegerField(default=0, verbose_name='Earning Fee'),
        ),
        migrations.AlterField(
            model_name='applicationsale',
            name='sales_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Sales Price'),
        ),
        migrations.AlterField(
            model_name='applicationsale',
            name='total_earning_fee_charged',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Earning Fee'),
        ),
        migrations.AlterField(
            model_name='applicationsale',
            name='total_sales_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Applicant Budget'),
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='disc_sales_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Discounted Salary'),
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='earning',
            field=models.PositiveIntegerField(default=0, verbose_name='Earning'),
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='earning_fee_charged',
            field=models.PositiveIntegerField(default=0, verbose_name='Earning Fee'),
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='sales_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Sales Price'),
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='total_earning',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Earning'),
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='total_earning_fee_charged',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Earning Fee'),
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='total_sales_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Applicant Budget'),
        ),
        migrations.AlterField(
            model_name='extcontract',
            name='disc_sales_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Discounted Salary'),
        ),
        migrations.AlterField(
            model_name='extcontract',
            name='earning',
            field=models.PositiveIntegerField(default=0, verbose_name='Earning'),
        ),
        migrations.AlterField(
            model_name='extcontract',
            name='earning_fee_charged',
            field=models.PositiveIntegerField(default=0, verbose_name='Earning Fee'),
        ),
        migrations.AlterField(
            model_name='extcontract',
            name='sales_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Sales Price'),
        ),
        migrations.AlterField(
            model_name='extcontract',
            name='total_earning',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Earning'),
        ),
        migrations.AlterField(
            model_name='extcontract',
            name='total_earning_fee_charged',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Earning Fee'),
        ),
        migrations.AlterField(
            model_name='extcontract',
            name='total_sales_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Applicant Budget'),
        ),
        migrations.AlterField(
            model_name='proposalsale',
            name='disc_sales_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Discounted Salary'),
        ),
        migrations.AlterField(
            model_name='proposalsale',
            name='earning',
            field=models.PositiveIntegerField(default=0, verbose_name='Earning'),
        ),
        migrations.AlterField(
            model_name='proposalsale',
            name='earning_fee_charged',
            field=models.PositiveIntegerField(default=0, verbose_name='Earning Fee'),
        ),
        migrations.AlterField(
            model_name='proposalsale',
            name='sales_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Sales Price'),
        ),
        migrations.AlterField(
            model_name='proposalsale',
            name='total_earning',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Earning'),
        ),
        migrations.AlterField(
            model_name='proposalsale',
            name='total_earning_fee_charged',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Earning Fee'),
        ),
        migrations.AlterField(
            model_name='proposalsale',
            name='total_sales_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Applicant Budget'),
        ),
    ]
