# Generated by Django 4.1.9 on 2023-08-27 22:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_applicationsale_reference_contractsale_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsale',
            name='reference',
            field=models.URLField(default=uuid.uuid4, unique=True, verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='reference',
            field=models.URLField(default=uuid.uuid4, unique=True, verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='extcontract',
            name='reference',
            field=models.URLField(default=uuid.uuid4, unique=True, verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='proposalsale',
            name='reference',
            field=models.URLField(default=uuid.uuid4, unique=True, verbose_name='reference'),
        ),
    ]
