# Generated by Django 3.2.8 on 2022-06-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20220623_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Time'),
        ),
    ]
