# Generated by Django 3.2.8 on 2023-06-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0002_auto_20230606_2146'),
        ('transactions', '0005_auto_20230606_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='client_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='Client Fee'),
        ),
        migrations.DeleteModel(
            name='OneClickPurchase',
        ),
    ]
