# Generated by Django 4.1.9 on 2023-08-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_applicationsale_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsale',
            name='reference',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='reference',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='extcontract',
            name='reference',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='proposalsale',
            name='reference',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='Reference'),
        ),
    ]
