# Generated by Django 3.2.8 on 2022-06-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20220623_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionitem',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer ID'),
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subscription ID'),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Subscription Start'),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Subscription end'),
        ),
    ]
