# Generated by Django 4.1.9 on 2023-07-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_purchase_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalsale',
            name='duration',
            field=models.PositiveIntegerField(default=1, verbose_name='Duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposalsale',
            name='revision',
            field=models.PositiveIntegerField(default=1, verbose_name='Revision'),
            preserve_default=False,
        ),
    ]
