# Generated by Django 3.2.8 on 2022-07-16 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_remove_subscriptionitem_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionitem',
            options={'get_latest_by': ('-created_at',), 'ordering': ('-created_at',)},
        ),
    ]
