# Generated by Django 4.1.9 on 2023-07-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_proposalsale_duration_proposalsale_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalsale',
            name='package_name',
            field=models.CharField(default='basic', max_length=20, verbose_name='Selected Package'),
            preserve_default=False,
        ),
    ]
