# Generated by Django 3.2.8 on 2022-07-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_subscriptionitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='category',
            field=models.CharField(choices=[('proposal', 'Proposal'), ('project', 'Project'), ('contract', 'Contract')], default='', max_length=20, verbose_name='Purchase Category'),
        ),
    ]
