# Generated by Django 4.1.9 on 2023-07-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_proposalsale_package_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='paypal_transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='PayPal Transaction ID'),
        ),
    ]
