# Generated by Django 3.2.8 on 2022-07-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_purchase_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='client_fee',
            field=models.PositiveIntegerField(default=5, verbose_name='Client Fee'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SalesReporting',
        ),
    ]
