# Generated by Django 3.2.8 on 2022-08-27 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_alter_internalcontract_reaction'),
        ('teams', '0013_alter_package_monthly_projects_applicable_per_team'),
        ('proposals', '0008_proposalchat_proposal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0011_auto_20220723_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.CharField(choices=[('one_click', 'One Click'), ('proposal', 'Proposal'), ('project', 'Project'), ('contract', 'Contract')], default='', max_length=20, verbose_name='Purchase Category'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='flutterwave_order_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Flutterwave Order Key'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='paypal_order_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='PayPal Order Key'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='razorpay_order_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razorpay Order Key'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razorpay Payment ID'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razorpay Signature'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='stripe_order_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Stripe Order Key'),
        ),
        migrations.CreateModel(
            name='OneClickPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_paid', models.PositiveIntegerField(verbose_name='Salary Paid')),
                ('payment_method', models.CharField(blank=True, max_length=200, verbose_name='Payment Method')),
                ('category', models.CharField(choices=[('proposal', 'Proposal'), ('contract', 'Contract')], default='', max_length=20, verbose_name='Purchase Category')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='failed', max_length=10, verbose_name='Status')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ordered On')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modified On')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oneclickclient', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oneclickcontract', to='contract.internalcontract', verbose_name='Contract')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oneclickproposal', to='proposals.proposal', verbose_name='Proposal')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oneclickteam', to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
