# Generated by Django 4.1.9 on 2023-08-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_applicationsale_end_time_applicationsale_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsale',
            name='status',
            field=models.CharField(choices=[('pending', 'Not Started'), ('ongoing', 'Ongoing'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='status',
            field=models.CharField(choices=[('pending', 'Not Started'), ('ongoing', 'Ongoing'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='extcontract',
            name='status',
            field=models.CharField(choices=[('pending', 'Not Started'), ('ongoing', 'Ongoing'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='proposalsale',
            name='status',
            field=models.CharField(choices=[('pending', 'Not Started'), ('ongoing', 'Ongoing'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Action Type'),
        ),
    ]
