# Generated by Django 3.2.8 on 2022-08-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_auto_20220827_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneclickpurchase',
            name='earning_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='Earning Fee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oneclickpurchase',
            name='total_earning',
            field=models.PositiveIntegerField(default=0, verbose_name='Totoal Earning'),
            preserve_default=False,
        ),
    ]
