# Generated by Django 3.2.8 on 2022-08-27 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_auto_20220827_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oneclickpurchase',
            options={'ordering': ('-created_at',), 'verbose_name': 'One Click Purchase'},
        ),
    ]
