# Generated by Django 4.1.9 on 2023-08-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_applicationsale_cancel_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsale',
            name='cancel_status',
            field=models.CharField(blank=True, choices=[('not_cancelled', 'Not cancelled'), ('initiated', 'Initiated'), ('approved', 'Approved')], max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='applicationsale',
            name='cancel_type',
            field=models.CharField(blank=True, choices=[('deadline_exceeded', 'Deadline Exceeded'), ('user_abandoned_work', 'Work Abandoned'), ('user_not_responding', 'Client not Responding to Chat'), ('user_is_abusive', 'User is Abusive'), ('ordered_wrong_product', 'Wrong Product Ordered'), ('different_product_delivered', 'A different service/product submitted')], max_length=100, null=True, verbose_name='Issue Type'),
        ),
        migrations.AlterField(
            model_name='applicationsale',
            name='status',
            field=models.CharField(choices=[('not_cancelled', 'Not cancelled'), ('initiated', 'Initiated'), ('approved', 'Approved')], default='pending', max_length=20, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='cancel_status',
            field=models.CharField(blank=True, choices=[('not_cancelled', 'Not cancelled'), ('initiated', 'Initiated'), ('approved', 'Approved')], max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='cancel_type',
            field=models.CharField(blank=True, choices=[('deadline_exceeded', 'Deadline Exceeded'), ('user_abandoned_work', 'Work Abandoned'), ('user_not_responding', 'Client not Responding to Chat'), ('user_is_abusive', 'User is Abusive'), ('ordered_wrong_product', 'Wrong Product Ordered'), ('different_product_delivered', 'A different service/product submitted')], max_length=100, null=True, verbose_name='Issue Type'),
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='status',
            field=models.CharField(choices=[('not_cancelled', 'Not cancelled'), ('initiated', 'Initiated'), ('approved', 'Approved')], default='pending', max_length=20, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='extcontract',
            name='cancel_status',
            field=models.CharField(blank=True, choices=[('not_cancelled', 'Not cancelled'), ('initiated', 'Initiated'), ('approved', 'Approved')], max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='extcontract',
            name='cancel_type',
            field=models.CharField(blank=True, choices=[('deadline_exceeded', 'Deadline Exceeded'), ('user_abandoned_work', 'Work Abandoned'), ('user_not_responding', 'Client not Responding to Chat'), ('user_is_abusive', 'User is Abusive'), ('ordered_wrong_product', 'Wrong Product Ordered'), ('different_product_delivered', 'A different service/product submitted')], max_length=100, null=True, verbose_name='Issue Type'),
        ),
        migrations.AlterField(
            model_name='extcontract',
            name='status',
            field=models.CharField(choices=[('not_cancelled', 'Not cancelled'), ('initiated', 'Initiated'), ('approved', 'Approved')], default='pending', max_length=20, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='proposalsale',
            name='cancel_status',
            field=models.CharField(blank=True, choices=[('not_cancelled', 'Not cancelled'), ('initiated', 'Initiated'), ('approved', 'Approved')], max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='proposalsale',
            name='cancel_type',
            field=models.CharField(blank=True, choices=[('deadline_exceeded', 'Deadline Exceeded'), ('user_abandoned_work', 'Work Abandoned'), ('user_not_responding', 'Client not Responding to Chat'), ('user_is_abusive', 'User is Abusive'), ('ordered_wrong_product', 'Wrong Product Ordered'), ('different_product_delivered', 'A different service/product submitted')], max_length=100, null=True, verbose_name='Issue Type'),
        ),
        migrations.AlterField(
            model_name='proposalsale',
            name='status',
            field=models.CharField(choices=[('not_cancelled', 'Not cancelled'), ('initiated', 'Initiated'), ('approved', 'Approved')], default='pending', max_length=20, verbose_name='Action Type'),
        ),
    ]
