# Generated by Django 4.1.9 on 2023-08-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_alter_applicationsale_cancel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsale',
            name='cancel_status',
            field=models.CharField(choices=[('not_cancelled', 'Not cancelled'), ('initiated', 'Initiated'), ('approved', 'Approved')], default='not_cancelled', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='cancel_status',
            field=models.CharField(choices=[('not_cancelled', 'Not cancelled'), ('initiated', 'Initiated'), ('approved', 'Approved')], default='not_cancelled', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='extcontract',
            name='cancel_status',
            field=models.CharField(choices=[('not_cancelled', 'Not cancelled'), ('initiated', 'Initiated'), ('approved', 'Approved')], default='not_cancelled', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='proposalsale',
            name='cancel_status',
            field=models.CharField(choices=[('not_cancelled', 'Not cancelled'), ('initiated', 'Initiated'), ('approved', 'Approved')], default='not_cancelled', max_length=100, verbose_name='Status'),
        ),
    ]
