# Generated by Django 3.2.8 on 2022-08-30 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0018_auto_20220829_1905'),
        ('transactions', '0014_alter_oneclickpurchase_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneclickpurchase',
            name='extcontract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extoneclickcontract', to='contract.contract', verbose_name='Ext Contract'),
        ),
        migrations.AlterField(
            model_name='oneclickpurchase',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intoneclickcontract', to='contract.internalcontract', verbose_name='Int Contract'),
        ),
    ]
