# Generated by Django 3.2.8 on 2022-08-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_auto_20220830_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneclickpurchase',
            name='category',
            field=models.CharField(choices=[('proposal', 'Proposal'), ('contract', 'Contract'), ('externalcontract', 'External Contract')], default='', max_length=20, verbose_name='Purchase Category'),
        ),
    ]
