# Generated by Django 4.1.9 on 2023-08-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_alter_applicationsale_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='flutterwave_transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Flutterwave Transaction ID'),
        ),
    ]
