# Generated by Django 3.2.8 on 2022-09-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_alter_oneclickpurchase_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalsale',
            name='is_refunded',
            field=models.BooleanField(default=False, verbose_name='Refunded'),
        ),
    ]
