# Generated by Django 3.2.8 on 2022-09-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_proposalsale_is_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsale',
            name='is_refunded',
            field=models.BooleanField(default=False, verbose_name='Refunded'),
        ),
        migrations.AddField(
            model_name='contractsale',
            name='is_refunded',
            field=models.BooleanField(default=False, verbose_name='Refunded'),
        ),
    ]
