# Generated by Django 4.1.9 on 2023-08-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_purchase_flutterwave_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='unique_reference',
        ),
        migrations.AddField(
            model_name='purchase',
            name='paystack_order_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Paystack Order Key'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='paystack_transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Paystack Transaction ID'),
        ),
    ]
