# Generated by Django 4.1.9 on 2023-08-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_remove_purchase_unique_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='flutterwave_order_key',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='paystack_order_key',
        ),
        migrations.AddField(
            model_name='purchase',
            name='reference',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Order Key'),
        ),
    ]
