# Generated by Django 3.2.8 on 2022-09-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_auto_20220907_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.CharField(choices=[('one_click', 'One Click'), ('proposal', 'Proposal'), ('project', 'Project'), ('contract', 'Contract'), ('excontract', 'Ex-Contract')], default='', max_length=20, verbose_name='Purchase Category'),
        ),
    ]
