# Generated by Django 3.2.8 on 2022-09-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_auto_20220924_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsale',
            name='discount_offered',
            field=models.PositiveIntegerField(default=0, verbose_name='Discount Offered'),
        ),
        migrations.AlterField(
            model_name='applicationsale',
            name='total_discount_offered',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Discount'),
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='discount_offered',
            field=models.PositiveIntegerField(default=0, verbose_name='Discount Offered'),
        ),
        migrations.AlterField(
            model_name='contractsale',
            name='total_discount_offered',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Discount'),
        ),
        migrations.AlterField(
            model_name='proposalsale',
            name='discount_offered',
            field=models.PositiveIntegerField(default=0, verbose_name='Discount Offered'),
        ),
        migrations.AlterField(
            model_name='proposalsale',
            name='total_discount_offered',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Discount'),
        ),
    ]
