# Generated by Django 3.2.8 on 2023-05-14 18:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import proposals.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title field is Required', max_length=255, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('preview', models.CharField(error_messages={'name': {'max_length': 'Preview field is required with maximum of 250 characters'}}, max_length=255, verbose_name='Preview')),
                ('sample_link', models.URLField(blank=True, help_text='the link must be a verified url', max_length=2083, null=True, verbose_name='Sample Website')),
                ('status', models.CharField(choices=[('review', 'Review'), ('active', 'Active'), ('modify', 'Modify'), ('archived', 'Archived')], default='review', max_length=20, verbose_name='Status')),
                ('description', models.TextField(error_messages={'name': {'max_length': 'Description field is required'}}, max_length=3500, verbose_name='Description')),
                ('dura_converter', models.CharField(choices=[('one_day', '01 Day'), ('two_days', '02 Days'), ('three_days', '03 Days'), ('four_days', '04 Days'), ('five_days', '05 Days'), ('six_days', '06 Days'), ('one_week', '01 Week'), ('two_weeks', '02 Weeks'), ('three_weeks', '03 Weeks'), ('one_month', '01 Month')], default='one_day', max_length=100, verbose_name='Deadline')),
                ('service_level', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='basic', error_messages={'name': {'max_length': 'Service Level field is required'}}, max_length=20, verbose_name='Service Level')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('published', models.BooleanField(choices=[(False, 'Unfeature'), (True, 'Feature')], default=False, verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('salary', models.IntegerField(default=10, error_messages={'amount': {'max_length': 'Set the budget amount between 10 and 50000 currency points'}}, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50000)], verbose_name='Price')),
                ('revision', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Revision')),
                ('thumbnail', models.ImageField(help_text="image must be any of these 'JPEG','JPG','PNG','PSD', and dimension 820x312", upload_to=proposals.models.proposal_images_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPG', 'JPEG', 'PNG', 'PSD'])], verbose_name='Thumbnail')),
                ('faq_one', models.CharField(max_length=100, verbose_name='FAQ #1')),
                ('faq_one_description', models.TextField(max_length=255, verbose_name='FAQ #1 Details')),
                ('faq_two', models.CharField(blank=True, max_length=100, null=True, verbose_name='FAQ #2')),
                ('faq_two_description', models.TextField(blank=True, max_length=255, null=True, verbose_name='FAQ #2 Details')),
                ('faq_three', models.CharField(blank=True, max_length=100, null=True, verbose_name='FAQ #3')),
                ('faq_three_description', models.TextField(blank=True, max_length=255, null=True, verbose_name='FAQ #3 Details')),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposals',
                'ordering': ('-created_at',),
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProposalChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.merchant', verbose_name='Merchant')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposalschats', to='proposals.proposal', verbose_name='Proposal')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposalsender', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'ordering': ['sent_on'],
            },
        ),
    ]
