# Generated by Django 3.2.8 on 2023-05-14 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0001_initial'),
        ('teams', '0001_initial'),
        ('general_settings', '0001_initial'),
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalchat',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposalchats', to='teams.team', verbose_name='Proposal Team'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='category',
            field=models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.RESTRICT, to='general_settings.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.merchant', verbose_name='Merchant'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='skill',
            field=models.ManyToManyField(error_messages={'name': {'max_length': 'Skill field is required'}}, to='general_settings.Skill', verbose_name='Proposal Skills'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='team',
            field=models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, related_name='proposalteam', to='teams.team', verbose_name='Team'),
        ),
        migrations.CreateModel(
            name='ProposalSupport',
            fields=[
            ],
            options={
                'verbose_name': 'Proposal Support',
                'verbose_name_plural': 'Proposal Support',
                'ordering': ['created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('proposals.proposal',),
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
