# Generated by Django 3.2.8 on 2023-03-22 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_package_multiple_freelancer_teams'),
        ('proposals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalchat',
            name='merchant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='proposalchats', to='account.merchant', verbose_name='Merchant'),
            preserve_default=False,
        ),
    ]
