# Generated by Django 4.1.9 on 2023-09-16 20:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_merchant_packages'),
        ('proposals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.merchant', verbose_name='Merchant'),
        ),
        migrations.AlterField(
            model_name='proposalchat',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.merchant', verbose_name='Merchant'),
        ),
        migrations.AlterField(
            model_name='proposalproduct',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.merchant', verbose_name='Merchant'),
        ),
    ]
