# Generated by Django 3.2.8 on 2022-06-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='discount_code',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='discount_price',
        ),
    ]
