# Generated by Django 3.2.8 on 2023-03-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='description',
            field=models.TextField(error_messages={'name': {'max_length': 'Description field is required'}}, max_length=3500, verbose_name='Description'),
        ),
    ]
