# Generated by Django 3.2.8 on 2023-05-08 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_package_upsell_price'),
        ('proposals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalchat',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.merchant', verbose_name='Merchant'),
        ),
    ]
