# Generated by Django 3.2.8 on 2023-03-12 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_rename_user_merchant_merchant'),
        ('proposals', '0003_alter_proposal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='merchant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='proposalmerchant', to='account.merchant', verbose_name='Merchant'),
            preserve_default=False,
        ),
    ]
