# Generated by Django 4.1.9 on 2023-08-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_alter_proposal_duration_alter_proposal_revision'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='proposal',
            managers=[
            ],
        ),
    ]
