# Generated by Django 3.2.8 on 2022-06-11 23:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_auto_20220611_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='video',
        ),
        migrations.AddField(
            model_name='proposal',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='Proposal Progress', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50000)], verbose_name='Proposal Progress'),
        ),
    ]
