# Generated by Django 4.1.9 on 2023-08-27 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('proposals', '0004_alter_proposal_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='site',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposalchat',
            name='site',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposalproduct',
            name='site',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
            preserve_default=False,
        ),
    ]
