# Generated by Django 3.2.8 on 2022-06-14 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_remove_proposal_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferContract',
        ),
    ]
