# Generated by Django 4.1.9 on 2023-08-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_proposal_site_proposalchat_site_proposalproduct_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='site',
        ),
        migrations.RemoveField(
            model_name='proposalchat',
            name='site',
        ),
        migrations.RemoveField(
            model_name='proposalproduct',
            name='site',
        ),
    ]
