# Generated by Django 4.1.9 on 2023-06-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_alter_proposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='digital',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Digital Product'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='salary_tier1',
            field=models.PositiveIntegerField(default=0, verbose_name='Price Tier1'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='salary_tier2',
            field=models.PositiveIntegerField(default=0, verbose_name='Price Tier2'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='salary_tier3',
            field=models.PositiveIntegerField(default=0, verbose_name='Price Tier3'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='tier_pricing',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Tier Pricing'),
        ),
    ]
