# Generated by Django 3.2.8 on 2022-06-14 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0006_delete_offercontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposalreceiver', to=settings.AUTH_USER_MODEL, verbose_name='Receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposalsender', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposalchats', to='teams.team', verbose_name='Proposal Team')),
            ],
            options={
                'ordering': ['sent_on'],
            },
        ),
    ]
