# Generated by Django 4.1.9 on 2023-07-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_proposal_digital_proposal_salary_tier1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='salary_tier1',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='salary_tier2',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='salary_tier3',
        ),
        
        # migrations.AddField(
        #     model_name='proposal',
        #     name='pricing',
        #     field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=True, verbose_name='Tier Pricing'),
        # ),
        # migrations.AddField(
        #     model_name='proposal',
        #     name='pricing_tier',
        #     field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='basic', max_length=30, verbose_name='Pricing Tier'),
        # ),
    ]
