# Generated by Django 3.2.8 on 2022-06-14 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_proposalchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalchat',
            name='proposal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proposalschats', to='proposals.proposal', verbose_name='Proposal'),
            preserve_default=False,
        ),
    ]
