# Generated by Django 4.1.9 on 2023-07-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_remove_proposal_salary_tier1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='pricing',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=True, verbose_name='Tier Pricing'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='pricing1_duration',
            field=models.PositiveIntegerField(choices=[(1, '01 Day'), (2, '02 Days'), (3, '03 Days'), (4, '04 Days'), (5, '05 Days'), (6, '06 Days'), (7, '01 Week'), (14, '02 Weeks'), (21, '03 Weeks'), (30, '01 Month')], default=3, verbose_name='Price Tier1'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='pricing2_duration',
            field=models.PositiveIntegerField(choices=[(1, '01 Day'), (2, '02 Days'), (3, '03 Days'), (4, '04 Days'), (5, '05 Days'), (6, '06 Days'), (7, '01 Week'), (14, '02 Weeks'), (21, '03 Weeks'), (30, '01 Month')], default=5, verbose_name='Price Tier2'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='pricing3_duration',
            field=models.PositiveIntegerField(choices=[(1, '01 Day'), (2, '02 Days'), (3, '03 Days'), (4, '04 Days'), (5, '05 Days'), (6, '06 Days'), (7, '01 Week'), (14, '02 Weeks'), (21, '03 Weeks'), (30, '01 Month')], default=7, verbose_name='Price Tier3'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='pricing_tier',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='basic', max_length=30, verbose_name='Pricing Tier'),
        ),
    ]
