# Generated by Django 4.1.9 on 2023-07-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_alter_proposal_pricing1_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='salary_tier1',
            field=models.PositiveIntegerField(default=0, verbose_name='Price Tier1'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='salary_tier2',
            field=models.PositiveIntegerField(default=0, verbose_name='Price Tier2'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='salary_tier3',
            field=models.PositiveIntegerField(default=0, verbose_name='Price Tier3'),
        ),
    ]
