# Generated by Django 3.2.8 on 2022-08-30 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_alter_proposal_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='Proposal Progress', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50000)], verbose_name='% Progress'),
        ),
    ]
