# Generated by Django 3.2.8 on 2022-09-11 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_alter_proposal_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalchat',
            name='receiver',
        ),
    ]
