# Generated by Django 4.1.9 on 2023-07-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0011_proposal_revision_tier1_proposal_revision_tier2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='revision_tier2',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=True, verbose_name='Revision Tier2'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='revision_tier3',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=True, verbose_name='Revision Tier3'),
        ),
    ]
