# Generated by Django 3.2.8 on 2022-09-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0011_remove_proposalchat_receiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalSupport',
            fields=[
            ],
            options={
                'verbose_name': 'Proposal Support',
                'verbose_name_plural': 'Proposal Support',
                'ordering': ['created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('proposals.proposal',),
        ),
    ]
