# Generated by Django 4.1.9 on 2023-07-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0013_alter_proposal_revision_tier1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='description_tier1',
            field=models.CharField(default='dfffdsfdsfd', max_length=80, verbose_name='Package 1 preview'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='description_tier2',
            field=models.CharField(default='sdfdsfdsfds2', max_length=80, verbose_name='Package 2 preview'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='description_tier3',
            field=models.CharField(default='sdfdfdsfdfd3', max_length=80, verbose_name='Package 3 preview'),
            preserve_default=False,
        ),
    ]
