# Generated by Django 4.1.9 on 2023-07-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0016_rename_description_tier1_proposal_tier1_preview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='tier1_preview',
            field=models.CharField(default='Features for Basic package', max_length=80, verbose_name='Package 1 preview'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='tier2_preview',
            field=models.CharField(default='Features for Standard package', max_length=80, verbose_name='Package 2 preview'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='tier3_preview',
            field=models.CharField(default='Features for Premium package', max_length=80, verbose_name='Package 3 preview'),
        ),
    ]
