# Generated by Django 4.1.9 on 2023-07-13 19:37

from django.conf import settings
import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import proposals.models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_gallery_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0018_alter_merchant_project_type'),
        ('proposals', '0018_alter_proposal_tier1_preview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.BooleanField(choices=[(False, 'Free Download'), (True, 'Paid Download')], default=True, verbose_name='Product Type')),
                ('status', models.BooleanField(choices=[(False, 'Not Active'), (True, 'Active')], default=True, verbose_name='Status')),
                ('attachment', models.FileField(help_text="image must be any of these 'ZIP', 'RAR','JPEG','JPG','PNG','PSD'", storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\kateygh\\Desktop\\attachments'), upload_to=proposals.models.product_storage, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ZIP', 'RAR', 'JPG', 'JPEG', 'PNG', 'PSD'])], verbose_name='Attachment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.merchant', verbose_name='Merchant')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.proposal', verbose_name='Proposal')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Product Team')),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposals',
                'ordering': ('-created_at',),
            },
        ),
    ]
