# Generated by Django 4.1.9 on 2023-07-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0019_proposalproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalproduct',
            name='product_type',
            field=models.BooleanField(choices=[(False, 'Free Download'), (True, 'Paid Download')], verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='proposalproduct',
            name='status',
            field=models.BooleanField(choices=[(False, 'Not Active'), (True, 'Active')], verbose_name='Status'),
        ),
    ]
