# Generated by Django 4.1.9 on 2023-07-14 17:18

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import proposals.models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0020_alter_proposalproduct_product_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposalproduct',
            options={'ordering': ('-created_at',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='proposalproduct',
            name='attachment',
            field=models.FileField(help_text="image must be any of these 'ZIP', 'RAR','JPEG','JPG','PNG','PSD'", storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\kateygh\\Desktop\\multitenants\\attachments/'), upload_to=proposals.models.product_storage, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ZIP', 'RAR', 'JPG', 'JPEG', 'PNG', 'PSD'])], verbose_name='Attachment'),
        ),
    ]
