# Generated by Django 4.1.9 on 2023-07-14 20:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0021_alter_proposalproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalproduct',
            name='license',
            field=models.URLField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Product License'),
        ),
    ]
