# Generated by Django 4.1.9 on 2023-07-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0022_proposalproduct_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='duration',
            field=models.PositiveIntegerField(choices=[(1, '1 Time'), (2, '2 Times'), (3, '3 Times'), (4, '4 Times'), (5, '5 Times'), (6, '6 Times'), (7, '7 Times')], default=1, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='revision',
            field=models.PositiveIntegerField(choices=[(1, '1 Time'), (2, '2 Times'), (3, '3 Times'), (4, '4 Times'), (5, '5 Times'), (6, '6 Times'), (7, '7 Times')], default=1, verbose_name='Revision'),
        ),
    ]
