# Generated by Django 4.1.9 on 2023-07-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0025_alter_proposal_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalproduct',
            name='price',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
