# Generated by Django 4.1.9 on 2023-07-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0026_proposalproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalproduct',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Custom Price'),
        ),
    ]
