# Generated by Django 4.1.9 on 2023-07-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0027_alter_proposalproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalproduct',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Custom Price'),
        ),
    ]
