# Generated by Django 4.1.9 on 2023-07-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0028_alter_proposalproduct_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposalproduct',
            options={'ordering': ('created_at',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
