# Generated by Django 4.1.9 on 2023-08-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0029_alter_proposalproduct_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalproduct',
            name='product_type',
            field=models.BooleanField(choices=[(False, 'Free Download'), (True, 'Premium Download')], verbose_name='Product Type'),
        ),
        migrations.AlterUniqueTogether(
            name='proposalproduct',
            unique_together={('product_type', 'proposal')},
        ),
    ]
