# Generated by Django 4.1.9 on 2023-08-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_country_flag'),
        ('proposals', '0030_alter_proposalproduct_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together={('slug', 'merchant')},
        ),
    ]
