# Generated by Django 3.2.8 on 2023-05-19 21:27

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('general_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='websitesetting',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('curr_merchant', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.RenameField(
            model_name='websitesetting',
            old_name='site_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='ad_image',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='site_domain',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='site_name',
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Business Address'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Last Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='protocol',
            field=models.CharField(choices=[('https://', 'Live Site on: https://'), ('https://www.', 'Live Site with www: https://www'), ('http://', 'UAT Site:> http://')], default='https://', help_text='Warning! Make sure you have SSL Certificate for your site before switing to Secure options', max_length=20, verbose_name='Protocol Type'),
        ),
    ]
