# Generated by Django 4.1.9 on 2023-11-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='proposal_detail',
            field=models.BooleanField(choices=[(False, 'Proposal without Image'), (True, 'Proposal with Image')], default=False, verbose_name='Proposal Detail Display'),
        ),
    ]
