# Generated by Django 3.2.8 on 2022-05-28 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentapis',
            name='flutterwave_secret_hash',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Flutterwave secret Hash'),
        ),
    ]
