# Generated by Django 3.2.8 on 2022-06-01 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0002_paymentapis_flutterwave_secret_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiringfee',
            name='application_fee_fixed',
        ),
        migrations.RemoveField(
            model_name='hiringfee',
            name='contract_fee_fixed',
        ),
        migrations.RemoveField(
            model_name='hiringfee',
            name='proposal_fee_fixed',
        ),
        migrations.AddField(
            model_name='hiringfee',
            name='application_fee_extra',
            field=models.PositiveIntegerField(default=10, help_text='An extra Proposal Extra value charged beyond delta amount', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Application Extra Fee - Extra (#)'),
        ),
        migrations.AddField(
            model_name='hiringfee',
            name='contract_fee_extra',
            field=models.PositiveIntegerField(default=10, help_text='An extra contract Extra value charged beyond delta amount', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Contract Extra Fee - Extra (#)'),
        ),
        migrations.AddField(
            model_name='hiringfee',
            name='proposal_fee_extra',
            field=models.PositiveIntegerField(default=10, help_text='An extra Proposal Extra value charged beyond delta amount', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Proposal Extra Fee - Extra (#)'),
        ),
    ]
