# Generated by Django 3.2.8 on 2022-06-24 12:25

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0003_auto_20220601_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentapis',
            name='razorpay_subscription_price_id',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='RAZORPAY SUBSCRIPTION PRICE ID')),
        ),
    ]
