# Generated by Django 3.2.8 on 2023-05-20 00:34

import django.contrib.sites.managers
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0004_auto_20230520_0011'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='websitesetting',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('curr_merchant', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
