# Generated by Django 3.2.8 on 2022-07-10 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0005_paymentapis_paypal_sandbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentapis',
            old_name='paypal_sandbox',
            new_name='sandbox',
        ),
    ]
