# Generated by Django 3.2.8 on 2023-05-20 00:44

import django.core.validators
from django.db import migrations, models
import general_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0005_alter_websitesetting_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='banner_image',
            field=models.ImageField(blank=True, help_text="image must be any of these: 'JPEG','JPG','PNG','PSD'", null=True, upload_to=general_settings.models.site_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPG', 'JPEG', 'PNG', 'PSD'])], verbose_name='Home Banner Image'),
        ),
    ]
