# Generated by Django 3.2.8 on 2023-05-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0006_alter_websitesetting_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='category_type',
            field=models.BooleanField(choices=[(False, 'Silva Land'), (True, 'Royal Land')], default=False, verbose_name='Category Activator'),
        ),
    ]
