# Generated by Django 3.2.8 on 2022-07-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0006_rename_paypal_sandbox_paymentapis_sandbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payday_converter', models.CharField(choices=[('one_day', '01 Day'), ('two_days', '02 Days'), ('three_days', '03 Days'), ('four_days', '04 Days'), ('five_days', '05 Days'), ('six_days', '06 Days'), ('one_week', '01 Week'), ('two_weeks', '02 Weeks'), ('three_weeks', '03 Weeks'), ('one_month', '01 Month')], default='one_day', max_length=20, verbose_name='Duration')),
                ('duration', models.DateTimeField(blank=True, help_text='Time receiver should expect payment', verbose_name='Payday Deadline')),
            ],
            options={
                'verbose_name': 'Client Department',
                'verbose_name_plural': 'Clients Department',
            },
        ),
    ]
