# Generated by Django 3.2.8 on 2023-05-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0007_websitesetting_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='banner_type',
            field=models.CharField(choices=[('slide', 'Carousel Banner'), ('royal', 'Royal Banner'), ('hero', 'Hero Banner')], default=False, max_length=20, verbose_name='Banner Activator'),
        ),
    ]
