# Generated by Django 3.2.8 on 2023-05-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0008_alter_websitesetting_banner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='promo_type',
            field=models.BooleanField(choices=[(False, 'Call to Action'), (True, 'How it Works')], default=True, verbose_name='Marketing Section'),
        ),
    ]
