# Generated by Django 3.2.8 on 2023-05-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0009_websitesetting_promo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='banner_type',
            field=models.CharField(choices=[(1, 'Carousel Banner'), (2, 'Royal Banner'), (3, 'Hero Banner')], default=False, max_length=20, verbose_name='Banner Activator'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='promo_type',
            field=models.PositiveIntegerField(choices=[(False, 'Call to Action'), (True, 'How it Works')], default=True, verbose_name='Marketing Section'),
        ),
    ]
