# Generated by Django 3.2.8 on 2022-07-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0009_alter_payday_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payday',
            name='preview',
            field=models.CharField(default='Payday Timelines that users should expect money', help_text='"01 Week" means 7 Days, "02 Weeks" means 14 Days, "03 Weeks" means 21 Days, "01 Month" means 28-30 Days', max_length=100, verbose_name='Preview'),
        ),
    ]
