# Generated by Django 3.2.8 on 2022-07-29 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0010_alter_payday_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payday',
            options={'verbose_name': 'Payday Setting', 'verbose_name_plural': 'Payday Setting'},
        ),
        migrations.AlterField(
            model_name='depositcontrol',
            name='max_balance',
            field=models.PositiveIntegerField(default=2000, help_text='User with this Maximum balance has reached the max limit for further deposit(restricted to 50000 currency points)', validators=[django.core.validators.MaxValueValidator(50000)], verbose_name='Maximum Balance'),
        ),
    ]
