# Generated by Django 3.2.8 on 2022-07-30 13:40

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0011_auto_20220729_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_name', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True, verbose_name='Bucket Name'))),
                ('access_key', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True, verbose_name='S3 Access Key'))),
                ('secret_key', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True, verbose_name='S3 Secret Key'))),
                ('use_s3_bucket', models.BooleanField(default=True, verbose_name='Activate S3 Storage')),
            ],
        ),
        migrations.DeleteModel(
            name='EmailConfig',
        ),
    ]
