# Generated by Django 3.2.8 on 2023-05-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0011_auto_20230520_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='proposal_detail',
            field=models.BooleanField(choices=[(False, 'Proposal with Full Image'), (True, 'Proposal with Side Image')], default=False, verbose_name='Proposal Detail Display'),
        ),
    ]
