# Generated by Django 3.2.8 on 2022-07-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0012_auto_20220730_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='s3bucket',
            options={'verbose_name': 'S3 Storage Settings', 'verbose_name_plural': 'S3 Storage Settings'},
        ),
    ]
