# Generated by Django 3.2.8 on 2022-07-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0013_alter_s3bucket_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3bucket',
            name='use_s3_bucket',
            field=models.BooleanField(default=False, verbose_name='Activate S3 Storage'),
        ),
    ]
