# Generated by Django 3.2.8 on 2022-07-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0014_alter_s3bucket_use_s3_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3bucket',
            name='description',
            field=models.CharField(default='Amazon S3 Storage Configuration', max_length=100, verbose_name='Storage - Amazon S3'),
        ),
    ]
