# Generated by Django 3.2.8 on 2023-05-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0014_alter_websitesetting_promo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='project_type',
            field=models.BooleanField(choices=[(False, 'VerticAL display'), (True, 'Horizontal display')], default=False, verbose_name='Job Listing Type'),
        ),
    ]
