# Generated by Django 3.2.8 on 2022-07-30 21:52

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0015_s3bucket_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageBuckets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Local Storage and Amazon S3 Configuration', max_length=100, verbose_name='Storages')),
                ('bucket_name', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True, verbose_name='Bucket Name'))),
                ('access_key', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True, verbose_name='S3 Access Key'))),
                ('secret_key', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True, verbose_name='S3 Secret Key'))),
                ('storage_type', models.BooleanField(choices=[(True, 'Local Storage'), (False, 'Amazon S3 Bucket')], default=True, verbose_name='Storage Type')),
            ],
            options={
                'verbose_name': 'File and Image Storage',
                'verbose_name_plural': 'File and Image Storage',
            },
        ),
        migrations.DeleteModel(
            name='S3Bucket',
        ),
    ]
