# Generated by Django 4.1.9 on 2023-08-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0016_alter_websitesetting_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exachangerateapi',
            name='status',
            field=models.BooleanField(default=True, unique=True),
        ),
    ]
