# Generated by Django 3.2.8 on 2022-08-21 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0018_auto_20220821_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountsystem',
            name='level_four_rate',
            field=models.PositiveIntegerField(default=7, help_text='Highest Rate for L4 Discount with minimum of 7%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='L4 Rate'),
        ),
        migrations.AlterField(
            model_name='discountsystem',
            name='level_four_start_amount',
            field=models.PositiveIntegerField(default=1000, help_text='Minimum checkout Amount is $1000 and Above', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)], verbose_name='L4 Amount Start'),
        ),
        migrations.AlterField(
            model_name='discountsystem',
            name='level_one_delta_amount',
            field=models.PositiveIntegerField(default=199, help_text='checkout Amount Delta for L1', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)], verbose_name='L1 Amount Delta'),
        ),
        migrations.AlterField(
            model_name='discountsystem',
            name='level_one_rate',
            field=models.PositiveIntegerField(default=0, help_text='Starting Rate for L1 Discount with minimum default of 0 %', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0)], verbose_name='L1 Rate'),
        ),
        migrations.AlterField(
            model_name='discountsystem',
            name='level_one_start_amount',
            field=models.PositiveIntegerField(default=0, help_text='Minimum checkout Amount for L1', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)], verbose_name='L1 Amount Start'),
        ),
        migrations.AlterField(
            model_name='discountsystem',
            name='level_three_delta_amount',
            field=models.PositiveIntegerField(default=999, help_text='checkout Amount between Delta for L3', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)], verbose_name='L3 Amount Delta'),
        ),
        migrations.AlterField(
            model_name='discountsystem',
            name='level_three_rate',
            field=models.PositiveIntegerField(default=5, help_text='Medium Rate for L3 Discount with minimum default of 5%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='L3 Rate'),
        ),
        migrations.AlterField(
            model_name='discountsystem',
            name='level_three_start_amount',
            field=models.PositiveIntegerField(default=500, help_text='Minimum checkout Amount for L2', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)], verbose_name='L3 Amount Start'),
        ),
        migrations.AlterField(
            model_name='discountsystem',
            name='level_two_delta_amount',
            field=models.PositiveIntegerField(default=499, help_text='checkout Amount between Delta for L2', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)], verbose_name='L2 Amount Delta'),
        ),
        migrations.AlterField(
            model_name='discountsystem',
            name='level_two_rate',
            field=models.PositiveIntegerField(default=3, help_text='Second level Rate for L2 Discount with minimum default of 3%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='L2 Rate'),
        ),
        migrations.AlterField(
            model_name='discountsystem',
            name='level_two_start_amount',
            field=models.PositiveIntegerField(default=300, help_text='Minimum checkout Amount for L2', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)], verbose_name='L2 Amount Start'),
        ),
    ]
