# Generated by Django 3.2.8 on 2022-08-21 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0019_auto_20220821_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountsystem',
            name='level_four_rate',
            field=models.PositiveIntegerField(default=7, help_text='Highest Rate for L4 Discount with minimum default of 7%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='L4 Rate'),
        ),
        migrations.AlterField(
            model_name='discountsystem',
            name='level_four_start_amount',
            field=models.PositiveIntegerField(default=1000, help_text='Minimum checkout Amount with default of 1000 currency points', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)], verbose_name='L4 Amount Start'),
        ),
        migrations.AlterField(
            model_name='discountsystem',
            name='level_one_delta_amount',
            field=models.PositiveIntegerField(default=199, help_text='checkout amount delta with default of 199 currency points', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)], verbose_name='L1 Amount Delta'),
        ),
        migrations.AlterField(
            model_name='discountsystem',
            name='level_one_start_amount',
            field=models.PositiveIntegerField(default=0, help_text='Minimum checkout amount with default of zero(0) currency points', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)], verbose_name='L1 Amount Start'),
        ),
        migrations.AlterField(
            model_name='discountsystem',
            name='level_three_delta_amount',
            field=models.PositiveIntegerField(default=999, help_text='checkout amount delta with default of 999 currency points', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)], verbose_name='L3 Amount Delta'),
        ),
        migrations.AlterField(
            model_name='discountsystem',
            name='level_three_start_amount',
            field=models.PositiveIntegerField(default=500, help_text='Minimum checkout amount with default of 500 currency points', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)], verbose_name='L3 Amount Start'),
        ),
        migrations.AlterField(
            model_name='discountsystem',
            name='level_two_delta_amount',
            field=models.PositiveIntegerField(default=499, help_text='checkout amount delta with default of 499 currency points', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)], verbose_name='L2 Amount Delta'),
        ),
        migrations.AlterField(
            model_name='discountsystem',
            name='level_two_start_amount',
            field=models.PositiveIntegerField(default=300, help_text='Minimum checkout amount with default of 300 currency points', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)], verbose_name='L2 Amount Start'),
        ),
    ]
