# Generated by Django 3.2.8 on 2022-08-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0020_auto_20220821_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payday',
            name='payday_converter',
            field=models.CharField(choices=[('one_day', '01 Day'), ('two_days', '02 Days'), ('three_days', '03 Days'), ('four_days', '04 Days'), ('five_days', '05 Days'), ('six_days', '06 Days'), ('one_week', '01 Week'), ('two_weeks', '02 Weeks'), ('three_weeks', '03 Weeks'), ('one_month', '01 Month')], default='three_days', max_length=20, verbose_name='Duration'),
        ),
    ]
