# Generated by Django 3.2.8 on 2022-08-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0022_hiringfee_extcontract_fee_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='protocol',
            field=models.CharField(choices=[('https://', 'https://'), ('http://', 'http://')], default='https://', max_length=20, verbose_name='Protocol Type'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='www',
            field=models.CharField(choices=[('www.', 'www.'), ('', '')], default='www.', max_length=20, verbose_name='Use www path'),
        ),
    ]
