# Generated by Django 3.2.8 on 2022-08-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0023_auto_20220830_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitesetting',
            name='www',
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='use_www',
            field=models.BooleanField(choices=[(True, 'Use WWW'), (False, 'No WWW')], default=False, verbose_name='Use WWW Url'),
        ),
    ]
