# Generated by Django 3.2.8 on 2022-09-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0024_auto_20220830_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='protocol',
            field=models.CharField(choices=[('https://', 'Secure:> https://'), ('https://www.', 'Secure https://www'), ('http://', 'Insecure:> http://')], default='https://', max_length=20, verbose_name='Protocol Type'),
        ),
    ]
