# Generated by Django 3.2.8 on 2022-09-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0025_alter_websitesetting_protocol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitesetting',
            name='site_url',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='use_www',
        ),
    ]
