# Generated by Django 3.2.8 on 2022-09-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0026_auto_20220910_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Enter the full secure url path of your Facebook page', max_length=255, null=True, verbose_name='Facebook Page'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Enter the full secure url path of your Instagram page', max_length=255, null=True, verbose_name='Instagram Page'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Enter the full secure url path of your Twitter page', max_length=255, null=True, verbose_name='Twitter Page'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Enter the full secure url path of your Youtube page', max_length=255, null=True, verbose_name='Youtube Page'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='protocol',
            field=models.CharField(choices=[('https://', 'Secure:> https://'), ('https://www.', 'Secure https://www'), ('http://', 'Insecure:> http://')], default='https://', help_text='Warning! Make sure you have SSL Certificate for your site before switing to Secure options', max_length=20, verbose_name='Protocol Type'),
        ),
    ]
