# Generated by Django 3.2.8 on 2022-09-11 15:24

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0027_auto_20220910_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailer',
            name='from_email',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, help_text='This email will be the site-wide support email for all email sending', max_length=255, null=True, verbose_name='Site-Wide Support Email')),
        ),
    ]
