# Generated by Django 3.2.8 on 2022-09-11 15:51

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0028_alter_mailer_from_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testemail',
            name='test_email',
            field=django_cryptography.fields.encrypt(models.EmailField(blank=True, help_text='Test the email settings by sending a Test mail', max_length=100, null=True, verbose_name='Receiver Email')),
        ),
    ]
