# Generated by Django 3.2.8 on 2022-09-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0029_alter_testemail_test_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptiongateway',
            options={'verbose_name': 'Subscription Gateway', 'verbose_name_plural': 'Subscription Gateways'},
        ),
        migrations.RemoveField(
            model_name='subscriptiongateway',
            name='default',
        ),
        migrations.RemoveField(
            model_name='subscriptiongateway',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='subscriptiongateway',
            name='processing_fee',
        ),
        migrations.RemoveField(
            model_name='subscriptiongateway',
            name='status',
        ),
        migrations.AddField(
            model_name='subscriptiongateway',
            name='flutterwave',
            field=models.BooleanField(choices=[(False, 'Inactive'), (True, 'Active')], default=False, verbose_name='Flutterwave'),
        ),
        migrations.AddField(
            model_name='subscriptiongateway',
            name='paypal',
            field=models.BooleanField(choices=[(False, 'Inactive'), (True, 'Active')], default=False, verbose_name='PayPal'),
        ),
        migrations.AddField(
            model_name='subscriptiongateway',
            name='razorpay',
            field=models.BooleanField(choices=[(False, 'Inactive'), (True, 'Active')], default=False, verbose_name='Razorpay'),
        ),
        migrations.AddField(
            model_name='subscriptiongateway',
            name='stripe',
            field=models.BooleanField(choices=[(False, 'Inactive'), (True, 'Active')], default=False, verbose_name='Stripe'),
        ),
        migrations.AlterField(
            model_name='subscriptiongateway',
            name='name',
            field=models.CharField(blank=True, help_text='This is the switch for controlling the subscriptions appearing to customer', max_length=255, null=True, unique=True, verbose_name='Subscription Gateway'),
        ),
    ]
