# Generated by Django 3.2.8 on 2022-09-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0031_alter_subscriptiongateway_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiongateway',
            name='flutterwave',
            field=models.BooleanField(choices=[(False, 'Inactive'), (True, 'Active')], default=True, verbose_name='Flutterwave'),
        ),
        migrations.AlterField(
            model_name='subscriptiongateway',
            name='name',
            field=models.CharField(default='This is the switch for controlling the subscriptions appearing to customer', help_text='This is the switch to show or hide subscription gateway buttons', max_length=255, verbose_name='Preview'),
        ),
        migrations.AlterField(
            model_name='subscriptiongateway',
            name='paypal',
            field=models.BooleanField(choices=[(False, 'Inactive'), (True, 'Active')], default=True, verbose_name='PayPal'),
        ),
        migrations.AlterField(
            model_name='subscriptiongateway',
            name='razorpay',
            field=models.BooleanField(choices=[(False, 'Inactive'), (True, 'Active')], default=True, verbose_name='Razorpay'),
        ),
        migrations.AlterField(
            model_name='subscriptiongateway',
            name='stripe',
            field=models.BooleanField(choices=[(False, 'Inactive'), (True, 'Active')], default=True, verbose_name='Stripe'),
        ),
    ]
