# Generated by Django 3.2.8 on 2022-10-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0032_auto_20220916_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='This is the switch for controlling the subscriptions appearing to customer', help_text='This is the switch to show or hide deposit gateway buttons', max_length=255, verbose_name='Preview')),
                ('paypal', models.BooleanField(choices=[(False, 'Inactive'), (True, 'Active')], default=True, verbose_name='PayPal')),
                ('stripe', models.BooleanField(choices=[(False, 'Inactive'), (True, 'Active')], default=True, verbose_name='Stripe')),
                ('razorpay', models.BooleanField(choices=[(False, 'Inactive'), (True, 'Active')], default=True, verbose_name='Razorpay')),
                ('flutterwave', models.BooleanField(choices=[(False, 'Inactive'), (True, 'Active')], default=True, verbose_name='Flutterwave')),
            ],
            options={
                'verbose_name': 'Deposit Gateway',
                'verbose_name_plural': 'Deposit Gateways',
            },
        ),
    ]
