# Generated by Django 3.2.8 on 2022-10-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0033_depositgateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositgateway',
            name='name',
            field=models.CharField(default='This is the switch for controlling the deposit gateway appearing to customer', help_text='This is the switch to show or hide deposit gateway buttons', max_length=255, verbose_name='Preview'),
        ),
    ]
