# Generated by Django 3.2.8 on 2022-10-16 22:11

import django.core.validators
from django.db import migrations, models
import general_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0034_alter_depositgateway_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='ad_image',
            field=models.ImageField(blank=True, help_text="This will appear on 'proposal ad, project ad and all other ad slots'. image must be any of these: 'JPEG','JPG','PNG','PSD'", null=True, upload_to=general_settings.models.site_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPG', 'JPEG', 'PNG', 'PSD'])], verbose_name='Hero Image'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='brand_ambassador_image',
            field=models.ImageField(blank=True, help_text="This will appear on 'About Us Page'. image must be any of these: 'JPEG','JPG','PNG','PSD'", null=True, upload_to=general_settings.models.site_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPG', 'JPEG', 'PNG', 'PSD'])], verbose_name='Brand Ambassador Image'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='site_Logo',
            field=models.ImageField(blank=True, default='site/logo.png', null=True, upload_to=general_settings.models.site_path, verbose_name='Site Logo'),
        ),
    ]
