# Generated by Django 3.2.8 on 2022-10-22 14:33

import django.core.validators
from django.db import migrations, models
import general_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0036_auto_20221017_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='embed_video',
            field=models.URLField(blank=True, help_text='Enter the full path to your video url on youtube or vimeo etc', max_length=255, null=True, verbose_name='Embed Video Url'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='brand_ambassador_image',
            field=models.ImageField(blank=True, help_text="This will appear to logged-in user on 'About Us Page, Freelancer page, project page'. Size should be 255px x 255px. image must be any of these: 'JPEG','JPG','PNG','PSD'", null=True, upload_to=general_settings.models.site_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPG', 'JPEG', 'PNG', 'PSD'])], verbose_name='Brand Ambassador Image'),
        ),
    ]
