# Generated by Django 3.2.8 on 2022-10-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0037_auto_20221022_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='embed_video',
            field=models.URLField(blank=True, null=True, help_text='Your can Paste your Youtube or Vimeo video url here to embed. Only secured url allowed', verbose_name='Royal embed Video'),
        ),
    ]
