# Generated by Django 3.2.8 on 2022-10-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0038_alter_websitesetting_embed_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='embed_video',
            field=models.URLField(blank=True, help_text='Enter the full path to your video url on youtube or vimeo etc', max_length=2083, null=True, verbose_name='Embed Video Url'),
        ),
    ]
