# Generated by Django 3.2.8 on 2022-10-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0039_alter_websitesetting_embed_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='button_color',
            field=models.CharField(blank=True, default='purple', help_text="Customize colors for signup and login buttons. Example '3F0F8FF', or 'red' or 'blue' or 'purple' or any css color code. Warning!: Donnot add quotation marks around the color attributes", max_length=100, null=True, verbose_name='Hero Background Color'),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='navbar_color',
            field=models.CharField(blank=True, default='purple', help_text="Customize colors for Navbar. Example '3F0F8FF', or 'red' or 'blue' or 'purple' or any css color code. Warning!: Donnot add quotation marks around the color attributes", max_length=100, null=True, verbose_name='NavBar Color'),
        ),
    ]
