# Generated by Django 3.2.8 on 2022-10-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0040_auto_20221022_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitesetting',
            name='embed_video',
        ),
    ]
