# Generated by Django 3.2.8 on 2022-07-10 05:40

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freelancer',
            options={'verbose_name': 'Freelancer Profile', 'verbose_name_plural': 'Freelancer Profile'},
        ),
        migrations.AlterModelManagers(
            name='freelancer',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
