# Generated by Django 3.2.8 on 2023-03-08 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_rename_user_merchant_merchant'),
        ('freelancer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='merchant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='freelancemerchant', to='account.merchant', verbose_name='Merchant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelanceraccount',
            name='merchant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='freelanceaccmerchant', to='account.merchant', verbose_name='Merchant'),
            preserve_default=False,
        ),
    ]
