# Generated by Django 4.1.9 on 2023-08-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='freelancer',
            managers=[
            ],
        ),
    ]
