# Generated by Django 3.2.8 on 2022-07-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_auto_20220710_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelanceraccount',
            name='pending_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Pending Balance'),
        ),
    ]
