# Generated by Django 3.2.8 on 2022-07-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0004_freelanceraccount_pending_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelanceraction',
            name='action_choice',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('transfer', 'Transfer'), ('withdrawal', 'Withdrawal')], default='none', max_length=50, null=True, verbose_name='Action Type'),
        ),
    ]
