# Generated by Django 3.2.8 on 2023-06-06 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_merchant_project_type'),
        ('freelancer', '0004_alter_freelancer_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelanceraccount',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.merchant', verbose_name='Merchant'),
        ),
        migrations.AlterField(
            model_name='freelanceraction',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.merchant', verbose_name='Merchant'),
        ),
    ]
