# Generated by Django 3.2.8 on 2023-06-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0005_auto_20230606_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='created',
            field=models.BooleanField(default=False, verbose_name='user Created'),
        ),
    ]
