# Generated by Django 4.1.9 on 2023-08-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0005_freelancer_site_freelanceraccount_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='site',
        ),
        migrations.RemoveField(
            model_name='freelanceraccount',
            name='site',
        ),
        migrations.RemoveField(
            model_name='freelanceraction',
            name='site',
        ),
    ]
