# Generated by Django 3.2.8 on 2022-07-24 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0006_rename_paypal_sandbox_paymentapis_sandbox'),
        ('freelancer', '0005_alter_freelanceraction_action_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelanceraction',
            name='gateway',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='paymentaccount', to='general_settings.paymentgateway', verbose_name='Payment Account'),
            preserve_default=False,
        ),
    ]
