# Generated by Django 3.2.8 on 2022-07-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0006_rename_paypal_sandbox_paymentapis_sandbox'),
        ('freelancer', '0006_freelanceraction_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelanceraction',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymentaccount', to='general_settings.paymentgateway', verbose_name='Payment Account'),
        ),
    ]
