# Generated by Django 3.2.8 on 2022-07-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0007_alter_freelanceraction_gateway'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='freelancer',
            managers=[
            ],
        ),
    ]
