# Generated by Django 3.2.8 on 2022-08-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0008_alter_freelancer_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='freelancer/', verbose_name='Profile Photo'),
        ),
    ]
