# Generated by Django 3.2.8 on 2022-08-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0009_alter_freelancer_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='profile_photo',
            field=models.ImageField(default='freelancer/user-login.png', upload_to='freelancer/', verbose_name='Profile Photo'),
        ),
    ]
