# Generated by Django 3.2.8 on 2022-09-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0010_alter_freelancer_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelanceraccount',
            name='lock_fund',
            field=models.BooleanField(default=False, verbose_name='Lock Fund'),
        ),
    ]
