# Generated by Django 3.2.8 on 2022-09-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0011_freelanceraccount_lock_fund'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freelanceraccount',
            options={'ordering': ('id',), 'verbose_name': 'Freelancer Account', 'verbose_name_plural': 'Freelancer Account'},
        ),
        migrations.AlterModelOptions(
            name='freelanceraction',
            options={'ordering': ('-id',), 'verbose_name': 'Freelancer Ejournal', 'verbose_name_plural': 'Freelancer Ejournal'},
        ),
    ]
