# Generated by Django 3.2.8 on 2022-09-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0012_auto_20220914_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='hourly_rate',
        ),
    ]
