# Generated by Django 3.2.8 on 2022-09-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0013_remove_freelancer_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelanceraction',
            name='reference',
            field=models.CharField(blank=True, help_text='This is a unique number assigned for audit purposes', max_length=15, verbose_name='Ref Number'),
        ),
    ]
