# Generated by Django 3.2.8 on 2022-09-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0015_alter_freelanceraction_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelanceraction',
            name='reference',
        ),
        migrations.AddField(
            model_name='freelanceraction',
            name='reference_id',
            field=models.CharField(blank=True, help_text='This is a unique number assigned for audit purposes', max_length=15, verbose_name='Ref Number'),
        ),
    ]
