# Generated by Django 3.2.8 on 2022-09-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0016_auto_20220918_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelanceraction',
            old_name='reference_id',
            new_name='reference',
        ),
    ]
