# Generated by Django 3.2.8 on 2022-10-26 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0017_rename_reference_id_freelanceraction_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='key_skill_five_score',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Key Skill 5 Score'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='key_skill_four_score',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Key Skill 4 Score'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='key_skill_one_score',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Key Skill 1 Score'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='key_skill_three_score',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Key Skill 3 Score'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='key_skill_two_score',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Key Skill 2 Score'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='keyskill_five',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Key Skill 5'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='keyskill_four',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Key Skill 4'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='keyskill_one',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Key Skill 1'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='keyskill_three',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Key Skill 3'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='keyskill_two',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Key Skill 2'),
        ),
    ]
