# Generated by Django 3.2.8 on 2022-10-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0041_remove_websitesetting_embed_video'),
        ('freelancer', '0018_auto_20221026_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='skill',
            field=models.ManyToManyField(related_name='freelancerskill', to='general_settings.Skill', verbose_name='General skill'),
        ),
    ]
