# Generated by Django 3.2.8 on 2022-10-26 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0019_alter_freelancer_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='key_skill_five_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Key Skill 5 Score'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='key_skill_four_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Key Skill 4 Score'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='key_skill_one_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Key Skill 1 Score'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='key_skill_three_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Key Skill 3 Score'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='key_skill_two_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Key Skill 2 Score'),
        ),
    ]
