# Generated by Django 3.2.8 on 2022-10-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0020_auto_20221026_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='freelancer/awards/', verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='freelancer/awards/', verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='freelancer/awards/', verbose_name='Image 2'),
        ),
    ]
