# Generated by Django 3.2.8 on 2022-10-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0021_auto_20221030_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='support',
        ),
    ]
