# Generated by Django 3.2.8 on 2023-04-21 23:45

import control_settings.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_block', models.CharField(default='Hire Experts or Team', max_length=100, verbose_name='Banner Title')),
                ('subtitle_block', models.CharField(default='Consectetur adipisicing elit sed dotem eiusmod tempor incuntes ut labore etdolore maigna aliqua enim.', max_length=150, verbose_name='Banner Subtitle')),
                ('video_title', models.CharField(blank=True, default='See For Yourself!', max_length=100, null=True, verbose_name='Royal Video Title')),
                ('video_description', models.CharField(blank=True, default='Hire Experts or Team', max_length=100, null=True, verbose_name='Royal Video Description')),
                ('banner_type', models.BooleanField(choices=[(False, 'Switch Hero Banner'), (True, 'Switch Royal Banner')], default=False, verbose_name='Banner Type')),
                ('video_url', models.URLField(blank=True, help_text='Your can Paste your Youtube or Vimeo video url here to embed. Only secured url allowed', null=True, verbose_name='Royal embed Video')),
                ('banner_image', models.ImageField(blank=True, help_text="image must be any of these: 'JPEG','JPG','PNG','PSD'", null=True, upload_to=control_settings.models.home_layout_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPG', 'JPEG', 'PNG', 'PSD'])], verbose_name='Hero Image')),
                ('banner_color', models.CharField(blank=True, default='purple', help_text="Put your color here to decorate Hero Banner Background and buttons like signup and login. Example '3F0F8FF', or 'red' or 'blue' or 'purple' or any css color code. Warning!: Donnot add quotation marks around the color attributes", max_length=100, null=True, verbose_name='Hero Background Color')),
                ('banner_button_one_color', models.CharField(blank=True, default='green', help_text="Put your bootstrap color here to decorate Hero Button 1. Example 'primary' or 'secondary' or 'light' or 'success' . Warning!: Exclude quotation marks when you input color attributes", max_length=100, null=True, verbose_name='Hero Button1 Color')),
                ('banner_button_two_color', models.CharField(blank=True, default='light', help_text="Put your bootstrap color here to decorate Hero Button 2. Example 'primary' or 'secondary' or 'light' or 'success' . Warning!: Exclude quotation marks when you input color attributes", max_length=100, null=True, verbose_name='Hero Button2 Color')),
                ('show_gateways', models.BooleanField(default=True, verbose_name='Display Gateway')),
                ('gateway_title', models.CharField(blank=True, default='Collection and Payout Methods', max_length=100, null=True, verbose_name='Gateway Title')),
                ('category_title', models.CharField(blank=True, default='Explore Categories', max_length=100, null=True, verbose_name='Div Two Category Title')),
                ('category_subtitle', models.CharField(blank=True, default='Professional by categories', max_length=100, null=True, verbose_name='Div Two Category Subitle')),
                ('proposal_title', models.CharField(blank=True, default='Explore Proposals', max_length=100, null=True, verbose_name='Div Three Proposal Title')),
                ('proposal_subtitle', models.CharField(blank=True, default='Verified Proposals', max_length=100, null=True, verbose_name='Div Three Proposal Subitle')),
                ('promo_title', models.CharField(blank=True, default='#1 Choice For Businesses', max_length=100, null=True, verbose_name='Div Four Promo Title')),
                ('promo_subtitle', models.CharField(blank=True, default='Business on the Go', max_length=100, null=True, verbose_name='Div Four Promo Subitle')),
                ('promo_description', models.TextField(blank=True, default='The Example Marketplace', max_length=300, null=True, verbose_name='Div Four Promo Decription')),
                ('promo_image', models.ImageField(blank=True, default='freelancer/awards/banner.png', null=True, upload_to='promo/', verbose_name='Promo Image')),
                ('project_title', models.CharField(blank=True, default='Published Jobs', max_length=100, null=True, verbose_name='Div Five Project Title')),
                ('project_subtitle', models.CharField(blank=True, default='Apply and get Hired', max_length=100, null=True, verbose_name='Div Five Project Subitle')),
                ('footer_description', models.TextField(blank=True, default='Dotem eiusmod tempor incune utnaem labore etdolore maigna aliqua enim poskina ilukita ylokem lokateise ination voluptate velit esse cillum dolore eu fugiat nulla pariatur lokaim urianewce', max_length=250, null=True, verbose_name='Footer Content')),
            ],
            options={
                'verbose_name': 'Homepage Layout',
                'verbose_name_plural': 'Homepage Layout',
            },
        ),
        migrations.CreateModel(
            name='DepositController',
            fields=[
            ],
            options={
                'verbose_name': 'Deposit Control',
                'verbose_name_plural': 'Deposit Control',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.depositcontrol',),
        ),
        migrations.CreateModel(
            name='DepositSetting',
            fields=[
            ],
            options={
                'verbose_name': 'Deposit Setting',
                'verbose_name_plural': 'Deposit Setting',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.depositgateway',),
        ),
        migrations.CreateModel(
            name='DiscountSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Discount System',
                'verbose_name_plural': 'Discount System',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.discountsystem',),
        ),
        migrations.CreateModel(
            name='ExchangeRateSetting',
            fields=[
            ],
            options={
                'verbose_name': 'Currency Exchange Setting',
                'verbose_name_plural': 'Currency Exchange Setting',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.exachangerateapi',),
        ),
    ]
