# Generated by Django 4.1.9 on 2023-09-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositController',
            fields=[
            ],
            options={
                'verbose_name': 'Deposit Control',
                'verbose_name_plural': 'Deposit Control',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.depositcontrol',),
        ),
        migrations.CreateModel(
            name='DepositSetting',
            fields=[
            ],
            options={
                'verbose_name': 'Deposit Setting',
                'verbose_name_plural': 'Deposit Setting',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.depositgateway',),
        ),
        migrations.CreateModel(
            name='DiscountSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Discount System',
                'verbose_name_plural': 'Discount System',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.discountsystem',),
        ),
        migrations.CreateModel(
            name='ExchangeRateSetting',
            fields=[
            ],
            options={
                'verbose_name': 'Currency Exchange Setting',
                'verbose_name_plural': 'Currency Exchange Setting',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.exachangerateapi',),
        ),
    ]
