# Generated by Django 3.2.8 on 2022-09-16 15:36

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_settings', '0029_alter_testemail_test_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositController',
            fields=[
            ],
            options={
                'verbose_name': 'Deposit Control',
                'verbose_name_plural': 'Deposit Control',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.depositcontrol',),
        ),
        migrations.CreateModel(
            name='DiscountSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Discount System',
                'verbose_name_plural': 'Discount System',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.discountsystem',),
        ),
        migrations.CreateModel(
            name='ExchangeRateSetting',
            fields=[
            ],
            options={
                'verbose_name': 'Currency Exchange Setting',
                'verbose_name_plural': 'Currency Exchange Setting',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.exachangerateapi',),
        ),
        migrations.CreateModel(
            name='GatewaySetting',
            fields=[
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateway',
                'ordering': ['ordering'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.paymentgateway',),
        ),
        migrations.CreateModel(
            name='HiringSetting',
            fields=[
            ],
            options={
                'verbose_name': 'Hiring Fee Setting',
                'verbose_name_plural': 'Hiring Fee Setting',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.hiringfee',),
        ),
        migrations.CreateModel(
            name='MailerSetting',
            fields=[
            ],
            options={
                'verbose_name': 'Mailer',
                'verbose_name_plural': 'Mailer',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.mailer',),
        ),
        migrations.CreateModel(
            name='PaydayController',
            fields=[
            ],
            options={
                'verbose_name': 'Payday Control',
                'verbose_name_plural': 'Payday Control',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.payday',),
        ),
        migrations.CreateModel(
            name='PaymentAPISetting',
            fields=[
            ],
            options={
                'verbose_name': 'Payment API',
                'verbose_name_plural': 'Payment API',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.paymentapis',),
        ),
        migrations.CreateModel(
            name='PaymentsController',
            fields=[
            ],
            options={
                'verbose_name': 'Payments Control',
                'verbose_name_plural': 'Payments Control',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.paymentscontrol',),
        ),
        migrations.CreateModel(
            name='SubscriptionSetting',
            fields=[
            ],
            options={
                'verbose_name': 'Subscription Setting',
                'verbose_name_plural': 'Subscription Setting',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.subscriptiongateway',),
        ),
        migrations.CreateModel(
            name='TestMailSetting',
            fields=[
            ],
            options={
                'verbose_name': 'Test Email',
                'verbose_name_plural': 'Test Email',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.testemail',),
        ),
    ]
