# Generated by Django 4.1.9 on 2023-09-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control_settings', '0001_initial'),
        ('payments', '0001_initial'),
        ('general_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewaySetting',
            fields=[
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateway',
                'ordering': ['ordering'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.paymentgateway',),
        ),
        migrations.CreateModel(
            name='HiringSetting',
            fields=[
            ],
            options={
                'verbose_name': 'Hiring Fee Setting',
                'verbose_name_plural': 'Hiring Fee Setting',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.hiringfee',),
        ),
        migrations.CreateModel(
            name='MailerSetting',
            fields=[
            ],
            options={
                'verbose_name': 'Mailer Settings',
                'verbose_name_plural': 'Mailer Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.mailer',),
        ),
        migrations.CreateModel(
            name='PaydayController',
            fields=[
            ],
            options={
                'verbose_name': 'Payday Control',
                'verbose_name_plural': 'Payday Control',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.payday',),
        ),
        migrations.CreateModel(
            name='PaymentsController',
            fields=[
            ],
            options={
                'verbose_name': 'Payments Control',
                'verbose_name_plural': 'Payments Control',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.paymentscontrol',),
        ),
        migrations.CreateModel(
            name='SubscriptionSetting',
            fields=[
            ],
            options={
                'verbose_name': 'Subscription Setting',
                'verbose_name_plural': 'Subscription Setting',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.subscriptiongateway',),
        ),
        migrations.CreateModel(
            name='TestMailSetting',
            fields=[
            ],
            options={
                'verbose_name': 'Testing Email Settings',
                'verbose_name_plural': 'Testing Email Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.testemail',),
        ),
    ]
