# Generated by Django 3.2.8 on 2022-10-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0033_depositgateway'),
        ('control_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositSetting',
            fields=[
            ],
            options={
                'verbose_name': 'Subscription Setting',
                'verbose_name_plural': 'Subscription Setting',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('general_settings.depositgateway',),
        ),
    ]
