# Generated by Django 3.2.8 on 2022-10-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_settings', '0002_depositsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depositsetting',
            options={'verbose_name': 'Deposit Setting', 'verbose_name_plural': 'Deposit Setting'},
        ),
    ]
