# Generated by Django 3.2.8 on 2023-05-20 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_settings', '0002_gatewaysetting_hiringsetting_mailersetting_paydaycontroller_paymentscontroller_subscriptionsetting_t'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LayoutSetting',
        ),
    ]
