# Generated by Django 3.2.8 on 2022-10-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_settings', '0003_alter_depositsetting_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_block', models.CharField(blank=True, default='Hire Experts or Team', max_length=100, null=True, verbose_name='Div One Title')),
                ('subtitle_block', models.CharField(blank=True, default='Consectetur adipisicing elit sed dotem eiusmod tempor incuntes ut labore etdolore maigna aliqua enim.', max_length=150, null=True, verbose_name='Div One Subtitle')),
                ('video_title', models.CharField(blank=True, default='See For Yourself!', max_length=100, null=True, verbose_name='Div One Video Title')),
                ('video_description', models.CharField(blank=True, default='Hire Experts or Team', max_length=100, null=True, verbose_name='Div One Video Description')),
                ('video_url', models.URLField(blank=True, null=True,)),
                ('category_title', models.CharField(blank=True, default='Explore Categories', max_length=100, null=True, verbose_name='Div Two Category Title')),
                ('category_subtitle', models.CharField(blank=True, default='Professional by categories', max_length=100, null=True, verbose_name='Div Two Category Subitle')),
                ('proposal_title', models.CharField(blank=True, default='Explore Proposals', max_length=100, null=True, verbose_name='Div Three Proposal Title')),
                ('proposal_subtitle', models.CharField(blank=True, default='Verified Proposals', max_length=100, null=True, verbose_name='Div Three Proposal Subitle')),
                ('promo_title', models.CharField(blank=True, default='#1 Choice For Businesses', max_length=100, null=True, verbose_name='Div Four Promo Title')),
                ('promo_subtitle', models.CharField(blank=True, default='Business on the Go', max_length=100, null=True, verbose_name='Div Four Promo Subitle')),
                ('promo_description', models.TextField(blank=True, default='The Example Marketplace', max_length=300, null=True, verbose_name='Div Four Promo Decription')),
                ('promo_image', models.ImageField(blank=True, default='freelancer/awards/banner.png', null=True, upload_to='promo/', verbose_name='Promo Image')),
                ('project_title', models.CharField(blank=True, default='Published Jobs', max_length=100, null=True, verbose_name='Div Five Project Title')),
                ('project_subtitle', models.CharField(blank=True, default='Apply and get Hired', max_length=100, null=True, verbose_name='Div Five Project Subitle')),
                ('footer_description', models.TextField(blank=True, default='Dotem eiusmod tempor incune utnaem labore etdolore maigna aliqua enim poskina ilukita ylokem lokateise ination voluptate velit esse cillum dolore eu fugiat nulla pariatur lokaim urianewce', max_length=250, null=True, verbose_name='Footer Content')),
            ],
        ),
    ]
