# Generated by Django 3.2.8 on 2022-10-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_settings', '0004_layoutsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layoutsetting',
            options={'verbose_name': 'Homepage Layout', 'verbose_name_plural': 'Homepage Layout'},
        ),
        migrations.AddField(
            model_name='layoutsetting',
            name='gateway_title',
            field=models.CharField(blank=True, default='Collection and Payout Methods', max_length=100, null=True, verbose_name='Gateway Title'),
        ),
        migrations.AddField(
            model_name='layoutsetting',
            name='show_gateways',
            field=models.BooleanField(default=True, verbose_name='Display Gateway'),
        ),
    ]
