# Generated by Django 3.2.8 on 2022-10-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_settings', '0005_auto_20221009_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutsetting',
            name='show_video_content',
            field=models.BooleanField(default=True, verbose_name='Display Video Content'),
        ),
    ]
