# Generated by Django 3.2.8 on 2022-10-09 22:15

import control_settings.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_settings', '0006_layoutsetting_show_video_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layoutsetting',
            name='show_video_content',
        ),
        migrations.AddField(
            model_name='layoutsetting',
            name='banner_button_one_color',
            field=models.CharField(blank=True, default='green', help_text="Put your color here to decorate Hero Button 1. Example 'red' or 'blue' or 'purple' or any css color code. Warning!: Donnot add quotation marks around the color attributes", max_length=100, null=True, verbose_name='Hero Button1 Color'),
        ),
        migrations.AddField(
            model_name='layoutsetting',
            name='banner_button_two_color',
            field=models.CharField(blank=True, default='purple', help_text="Put your color here to decorate Hero Button 2. Example 'red' or 'blue' or 'purple' or any css color code. Warning!: Donnot add quotation marks around the color attributes", max_length=100, null=True, verbose_name='Hero Button2 Color'),
        ),
        migrations.AddField(
            model_name='layoutsetting',
            name='banner_color',
            field=models.CharField(blank=True, default='purple', help_text="Put your color here to decorate Hero Banner Background. Example '3F0F8FF', or 'red' or 'blue' or 'purple' or any css color code. Warning!: Donnot add quotation marks around the color attributes", max_length=100, null=True, verbose_name='Hero Background Color'),
        ),
        migrations.AddField(
            model_name='layoutsetting',
            name='banner_image',
            field=models.ImageField(blank=True, help_text="image must be any of these: 'JPEG','JPG','PNG','PSD'", null=True, upload_to=control_settings.models.home_layout_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPG', 'JPEG', 'PNG', 'PSD'])], verbose_name='Hero Image'),
        ),
        migrations.AddField(
            model_name='layoutsetting',
            name='banner_type',
            field=models.BooleanField(choices=[(False, 'Hero Banner'), (True, 'Royal Banner')], default=False, verbose_name='Banner Type'),
        ),
        migrations.AlterField(
            model_name='layoutsetting',
            name='subtitle_block',
            field=models.CharField(default='Consectetur adipisicing elit sed dotem eiusmod tempor incuntes ut labore etdolore maigna aliqua enim.', max_length=150, verbose_name='Banner Subtitle'),
        ),
        migrations.AlterField(
            model_name='layoutsetting',
            name='title_block',
            field=models.CharField(default='Hire Experts or Team', max_length=100, verbose_name='Banner Title'),
        ),
        migrations.AlterField(
            model_name='layoutsetting',
            name='video_description',
            field=models.CharField(blank=True, default='Hire Experts or Team', max_length=100, null=True, verbose_name='Royal Video Description'),
        ),
        migrations.AlterField(
            model_name='layoutsetting',
            name='video_title',
            field=models.CharField(blank=True, default='See For Yourself!', max_length=100, null=True, verbose_name='Royal Video Title'),
        ),
        migrations.AlterField(
            model_name='layoutsetting',
            name='video_url',
            field= models.URLField(blank=True, null=True, help_text='Your can Paste your Youtube or Vimeo video url here to embed. Only secured url allowed', verbose_name='Royal embed Video'),
        ),
    ]
