# Generated by Django 3.2.8 on 2022-10-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_settings', '0007_auto_20221009_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutsetting',
            name='banner_button_two_color',
            field=models.CharField(blank=True, default='light', help_text="Put your color here to decorate Hero Button 2. Example 'red' or 'blue' or 'purple' or any css color code. Warning!: Donnot add quotation marks around the color attributes", max_length=100, null=True, verbose_name='Hero Button2 Color'),
        ),
    ]
