# Generated by Django 3.2.8 on 2022-10-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_settings', '0008_alter_layoutsetting_banner_button_two_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutsetting',
            name='banner_type',
            field=models.BooleanField(choices=[(False, 'Switch Hero Banner'), (True, 'Switch Royal Banner')], default=False, verbose_name='Banner Type'),
        ),
    ]
