# Generated by Django 3.2.8 on 2022-10-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_settings', '0009_alter_layoutsetting_banner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutsetting',
            name='banner_button_one_color',
            field=models.CharField(blank=True, default='green', help_text="Put your bootstrap color here to decorate Hero Button 1. Example 'primary' or 'secondary' or 'light' or 'success' . Warning!: Exclude quotation marks when you input color attributes", max_length=100, null=True, verbose_name='Hero Button1 Color'),
        ),
        migrations.AlterField(
            model_name='layoutsetting',
            name='banner_button_two_color',
            field=models.CharField(blank=True, default='light', help_text="Put your bootstrap color here to decorate Hero Button 1. Example 'primary' or 'secondary' or 'light' or 'success' . Warning!: Exclude quotation marks when you input color attributes", max_length=100, null=True, verbose_name='Hero Button2 Color'),
        ),
        migrations.AlterField(
            model_name='layoutsetting',
            name='banner_color',
            field=models.CharField(blank=True, default='purple', help_text="Put your color here to decorate Hero Banner Background and buttons like signup and login. Example '3F0F8FF', or 'red' or 'blue' or 'purple' or any css color code. Warning!: Donnot add quotation marks around the color attributes", max_length=100, null=True, verbose_name='Hero Background Color'),
        ),
    ]
