# Generated by Django 3.2.8 on 2022-10-15 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_settings', '0010_auto_20221010_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailersetting',
            options={'verbose_name': 'Mailer Settings', 'verbose_name_plural': 'Mailer Settings'},
        ),
        migrations.AlterModelOptions(
            name='testmailsetting',
            options={'verbose_name': 'Testing Email Settings', 'verbose_name_plural': 'Testing Email Settings'},
        ),
    ]
