# Generated by Django 3.2.8 on 2022-05-25 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('projects', '0002_auto_20220525_1354'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutionproject', to='projects.project', verbose_name='Project Offered')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectpurchasemade', to='transactions.purchase', verbose_name='Purchase Client')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvedteam', to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ('-end_time',),
            },
        ),
    ]
