# Generated by Django 4.1.9 on 2023-08-25 21:43

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import resolution.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, help_text="Supported attachments: 'ZIP', 'RAR','JPEG','JPG','PNG','PSD'", null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\kateygh\\Desktop\\multitenants\\attachments/'), upload_to=resolution.models.jobs_storage, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ZIP', 'RAR', 'JPG', 'JPEG', 'PNG', 'PSD'])], verbose_name='Attachment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('review_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Review Title')),
                ('review_message', models.TextField(blank=True, max_length=650, null=True, verbose_name='Review Message')),
                ('rating', models.PositiveSmallIntegerField(blank=True, default=3, null=True, verbose_name='Rating')),
                ('review_status', models.BooleanField(choices=[(False, 'Pending'), (True, 'Completed')], default=False, verbose_name='Confirm Work')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed On')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.merchant', verbose_name='Merchant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposaljobs', to='transactions.proposalsale', verbose_name='Proposal Sold')),
            ],
            options={
                'verbose_name': 'Proposal File',
                'verbose_name_plural': 'Proposal Files',
                'ordering': ('-created_at',),
            },
        ),
    ]
