# Generated by Django 3.2.8 on 2023-06-06 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oneclickresolution',
            name='oneclick_sale',
        ),
        migrations.RemoveField(
            model_name='oneclickresolution',
            name='team',
        ),
        migrations.RemoveField(
            model_name='oneclickreview',
            name='resolution',
        ),
        migrations.DeleteModel(
            name='OneClickCancellation',
        ),
        migrations.DeleteModel(
            name='OneClickResolution',
        ),
        migrations.DeleteModel(
            name='OneClickReview',
        ),
    ]
