# Generated by Django 3.2.8 on 2022-06-04 15:17

import django.core.validators
from django.db import migrations, models
import resolution.models


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0003_auto_20220602_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCancelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='projectresolution',
            name='attachment',
            field=models.ImageField(blank=True, default='proposal_files/thumbnail.jpg', help_text="image must be any of these 'JPEG','JPG','PNG','PSD', and dimension 820x312", null=True, upload_to=resolution.models.application_file_directory, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPG', 'JPEG', 'PNG', 'PSD'])], verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='projectresolution',
            name='completed',
            field=models.BooleanField(choices=[(False, 'Pending'), (True, 'Completed')], default=False, verbose_name='Completed'),
        ),
    ]
