# Generated by Django 4.1.9 on 2023-08-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0003_proposaljob_remove_applicationreview_resolution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposaljob',
            name='cancel_message',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Additional Message'),
        ),
        migrations.AlterField(
            model_name='proposaljob',
            name='cancel_status',
            field=models.CharField(blank=True, choices=[('initiated', 'Initiated'), ('approved', 'Approved')], max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='proposaljob',
            name='cancel_type',
            field=models.CharField(blank=True, choices=[('team_exceeded_deadline', 'Team Exceeded Deadline'), ('team_abandoned_work', 'Team Abandoned Work'), ('team_not_responding', 'Team not Responding to Chat'), ('team_is_abusive', 'Team is Abusive'), ('ordered_wrong_product', 'I Ordered Wrong Product'), ('different_product_delivered', 'A different product delivered')], max_length=100, null=True, verbose_name='Issue Type'),
        ),
        migrations.AlterField(
            model_name='proposaljob',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=3, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='proposaljob',
            name='review_status',
            field=models.BooleanField(choices=[(False, 'Pending'), (True, 'Completed')], default=False, verbose_name='Confirm Work'),
        ),
    ]
