# Generated by Django 4.1.9 on 2023-08-05 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0004_alter_proposaljob_cancel_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposaljob',
            name='cancel_message',
        ),
        migrations.RemoveField(
            model_name='proposaljob',
            name='cancel_status',
        ),
        migrations.RemoveField(
            model_name='proposaljob',
            name='cancel_type',
        ),
        migrations.RemoveField(
            model_name='proposaljob',
            name='cancelled_at',
        ),
    ]
