# Generated by Django 3.2.8 on 2022-06-04 16:05

import django.core.validators
from django.db import migrations, models
import resolution.models


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0006_alter_projectresolution_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectresolution',
            name='attachment',
            field=models.FileField(blank=True, help_text="image must be any of these 'JPEG','PDF','JPG','PNG','PSD',", null=True, upload_to=resolution.models.application_file_directory, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPG', 'JPEG', 'PNG', 'PSD'])], verbose_name='Attachment'),
        ),
    ]
