# Generated by Django 3.2.8 on 2022-06-05 00:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('projects', '0003_auto_20220525_1529'),
        ('resolution', '0008_alter_projectresolution_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectResolutionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(500)], verbose_name='Message')),
                ('rating', models.PositiveSmallIntegerField(choices=[(0, '☆☆☆☆☆'), (1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=3, verbose_name='Rating')),
                ('status', models.BooleanField(choices=[(False, 'Pending'), (True, 'Completed')], verbose_name='Confirm Work')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicantreview', to='resolution.projectresolution', verbose_name='Applicant Review')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectreview', to='projects.project', verbose_name='Project Offered')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewteam', to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='ProjectCancelation',
        ),
    ]
