# Generated by Django 3.2.8 on 2022-06-05 17:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import resolution.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20220525_1529'),
        ('teams', '0001_initial'),
        ('resolution', '0010_alter_projectresolutionreview_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectresolution',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='projectresolution',
            name='completed',
        ),
        migrations.AlterField(
            model_name='projectresolutionreview',
            name='rating',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='projectresolutionreview',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewsteam', to='teams.team', verbose_name='Team'),
        ),
        migrations.CreateModel(
            name='ProjectCompletionFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, help_text="image must be any of these 'jpeg','pdf','jpg','png','psd',", null=True, upload_to=resolution.models.application_file_directory, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPG', 'PDF', 'JPEG', 'PNG', 'PSD'])], verbose_name='Attachment')),
                ('completed', models.BooleanField(choices=[(False, 'Pending'), (True, 'Completed')], default=False, verbose_name='Completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicantcomplettionfiles', to='resolution.projectresolution', verbose_name='Applicant Review')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completionfilesproject', to='projects.project', verbose_name='Project Offered')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectfilesteam', to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
