# Generated by Django 3.2.8 on 2022-06-06 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20220525_1529'),
        ('resolution', '0013_alter_projectresolution_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcompletionfiles',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicantcompletionfiles', to='resolution.projectresolution', verbose_name='Project File'),
        ),
        migrations.AlterField(
            model_name='projectresolutionreview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewapplication', to='resolution.projectresolution', verbose_name='Applicant Review'),
        ),
        migrations.AlterField(
            model_name='projectresolutionreview',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewproject', to='projects.project', verbose_name='Project Offered'),
        ),
    ]
