# Generated by Django 3.2.8 on 2022-06-07 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('projects', '0003_auto_20220525_1529'),
        ('resolution', '0014_auto_20220606_2127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectResolutionReview',
            new_name='ApplicationReview',
        ),
    ]
