# Generated by Django 3.2.8 on 2022-06-07 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0015_rename_projectresolutionreview_applicationreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationreview',
            name='project',
        ),
        migrations.RemoveField(
            model_name='applicationreview',
            name='team',
        ),
    ]
