# Generated by Django 3.2.8 on 2022-06-07 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0016_auto_20220607_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationreview',
            name='message',
            field=models.TextField(max_length=500, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(500)], verbose_name='Message'),
        ),
    ]
