# Generated by Django 3.2.8 on 2022-06-07 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0017_alter_applicationreview_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationreview',
            old_name='application',
            new_name='resolution',
        ),
    ]
