# Generated by Django 3.2.8 on 2022-06-09 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0018_rename_application_applicationreview_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationreview',
            name='title',
            field=models.CharField(default='Translation of blog post into English', max_length=100, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Title'),
            preserve_default=False,
        ),
    ]
