# Generated by Django 3.2.8 on 2022-06-16 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20220602_0627'),
        ('projects', '0005_alter_project_duration'),
        ('teams', '0001_initial'),
        ('resolution', '0019_applicationreview_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationreview',
            options={'ordering': ('-created_at',), 'verbose_name': 'Project Review', 'verbose_name_plural': 'Project Review'},
        ),
        migrations.AlterModelOptions(
            name='projectcompletionfiles',
            options={'ordering': ('-created_at',), 'verbose_name': 'Project File', 'verbose_name_plural': 'Project Files'},
        ),
        migrations.AlterModelOptions(
            name='projectresolution',
            options={'ordering': ('-created_at',), 'verbose_name': 'Application Approved', 'verbose_name_plural': 'Application Approved'},
        ),
        migrations.CreateModel(
            name='ProposalResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('completed', models.BooleanField(choices=[(False, 'Ongoing'), (True, 'Completed')], default=False, verbose_name='Completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposalaction', to='transactions.applicationsale', verbose_name='Application')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutionproposal', to='projects.project', verbose_name='Project Offered')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvedproposalteam', to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Proposal Approved',
                'verbose_name_plural': 'Proposal Approved',
                'ordering': ('-created_at',),
            },
        ),
    ]
