# Generated by Django 3.2.8 on 2022-06-16 20:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import resolution.models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20220602_0627'),
        ('proposals', '0008_proposalchat_proposal'),
        ('resolution', '0020_auto_20220616_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalresolution',
            name='application',
        ),
        migrations.RemoveField(
            model_name='proposalresolution',
            name='project',
        ),
        migrations.AddField(
            model_name='proposalresolution',
            name='proposal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resolutionproposal', to='proposals.proposal', verbose_name='Proposal Hired'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposalresolution',
            name='proposal_sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proposalaction', to='transactions.proposalsale', verbose_name='Proposal Sold'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationreview',
            name='message',
            field=models.TextField(max_length=250, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(500)], verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='projectresolution',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectapplicantsaction', to='transactions.applicationsale', verbose_name='Application Accepted'),
        ),
        migrations.CreateModel(
            name='ProposalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Title')),
                ('message', models.TextField(max_length=250, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(500)], verbose_name='Message')),
                ('rating', models.PositiveSmallIntegerField(default=3, verbose_name='Rating')),
                ('status', models.BooleanField(choices=[(False, 'Pending'), (True, 'Completed')], verbose_name='Confirm Work')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewproposal', to='resolution.proposalresolution', verbose_name='Applicant Review')),
            ],
            options={
                'verbose_name': 'Proposal Review',
                'verbose_name_plural': 'Proposal Review',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProposalCompletionFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, help_text="image must be any of these 'jpeg','pdf','jpg','png','psd',", null=True, upload_to=resolution.models.proposal_file_directory, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPG', 'PDF', 'JPEG', 'PNG', 'PSD'])], verbose_name='Attachment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicantcompletionfiles', to='resolution.proposalresolution', verbose_name='Proposal File')),
            ],
            options={
                'verbose_name': 'Proposal File',
                'verbose_name_plural': 'Proposal Files',
                'ordering': ('-created_at',),
            },
        ),
    ]
