# Generated by Django 3.2.8 on 2022-06-16 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0021_auto_20220616_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalreview',
            name='resolution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewproposal', to='resolution.proposalresolution', verbose_name='Proposal Review'),
        ),
    ]
