# Generated by Django 3.2.8 on 2022-06-16 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0023_rename_resolution_proposalcompletionfiles_proposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalresolution',
            name='proposal',
        ),
    ]
