# Generated by Django 3.2.8 on 2022-06-16 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0025_proposalresolution_proposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalresolution',
            name='proposal',
        ),
    ]
