# Generated by Django 3.2.8 on 2022-06-16 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0027_proposalresolution_proposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalresolution',
            name='proposal',
        ),
    ]
