# Generated by Django 3.2.8 on 2022-06-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0028_remove_proposalresolution_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalreview',
            name='status',
            field=models.BooleanField(choices=[(False, 'Pending'), (True, 'Completed')], default=True, verbose_name='Confirm Work'),
        ),
    ]
