# Generated by Django 3.2.8 on 2022-06-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0029_alter_proposalreview_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalreview',
            name='message',
            field=models.TextField(max_length=250, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='proposalreview',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
