# Generated by Django 3.2.8 on 2022-07-26 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0032_auto_20220725_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationreview',
            options={'ordering': ('-created_at',), 'verbose_name': 'Application Review', 'verbose_name_plural': 'Application Review'},
        ),
    ]
