# Generated by Django 3.2.8 on 2022-07-26 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0033_alter_applicationreview_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectresolution',
            name='project',
        ),
    ]
