# Generated by Django 3.2.8 on 2022-07-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0034_remove_projectresolution_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectresolution',
            name='completed',
        ),
        migrations.AddField(
            model_name='projectresolution',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=20, verbose_name='Action Type'),
        ),
    ]
