# Generated by Django 3.2.8 on 2022-08-23 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_alter_package_monthly_projects_applicable_per_team'),
        ('transactions', '0011_auto_20220723_1345'),
        ('resolution', '0035_auto_20220726_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=20, verbose_name='Action Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('contract_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractaction', to='transactions.contractsale', verbose_name='Contract Awarded')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvedcontractteam', to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Contract Awarded',
                'verbose_name_plural': 'Contract Awarded',
                'ordering': ('-created_at',),
            },
        ),
    ]
