# Generated by Django 3.2.8 on 2022-08-29 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0040_oneclickreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oneclickreview',
            options={'ordering': ('-created_at',), 'verbose_name': 'OneClick Review', 'verbose_name_plural': 'OneClick Review'},
        ),
    ]
