# Generated by Django 3.2.8 on 2022-09-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0041_alter_oneclickreview_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalresolution',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='ongoing', max_length=20, verbose_name='Action Type'),
        ),
    ]
