# Generated by Django 3.2.8 on 2022-09-16 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0020_alter_assignmember_options'),
        ('transactions', '0020_extcontract'),
        ('resolution', '0043_auto_20220907_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExContractResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='ongoing', max_length=20, verbose_name='Action Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('contract_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extcontractaction', to='transactions.extcontract', verbose_name='Contract Awarded')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvedextcontractteam', to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Ext-Contract Awarded',
                'verbose_name_plural': 'Ext-Contract Awarded',
                'ordering': ('-created_at',),
            },
        ),
    ]
