# Generated by Django 3.2.8 on 2022-09-16 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_extcontract'),
        ('teams', '0020_alter_assignmember_options'),
        ('resolution', '0044_excontractresolution'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExContractResolution',
            new_name='ExtContractResolution',
        ),
    ]
