# Generated by Django 3.2.8 on 2022-09-16 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0045_rename_excontractresolution_extcontractresolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtContractReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('message', models.TextField(max_length=650, verbose_name='Message')),
                ('rating', models.PositiveSmallIntegerField(default=3, verbose_name='Rating')),
                ('status', models.BooleanField(choices=[(False, 'Pending'), (True, 'Completed')], default=True, verbose_name='Confirm Work')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewextcontract', to='resolution.extcontractresolution', verbose_name='Contract Review')),
            ],
            options={
                'verbose_name': 'Contract Review',
                'verbose_name_plural': 'Contract Review',
                'ordering': ('-created_at',),
            },
        ),
    ]
