# Generated by Django 3.2.8 on 2022-09-24 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0046_extcontractreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_type', models.CharField(choices=[('team_abandoned_work', '(1) Team Abandoned Work'), ('team_not_responding', '(2) Team not Responding to Chat'), ('team_exceeded_deadline', '(3) Team Exceeded Deadline'), ('team_is_abusive', '(4) Team is Abusive'), ('ordered_wrong_product', '(5) I Ordered Wrong Product'), ('different_product_delivered', '(6) A different product delivered')], default='team_exceeded_deadline', max_length=100, verbose_name='Issue Type')),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('approved', 'Approved')], default='initiated', max_length=100, verbose_name='Issue Type')),
                ('message', models.TextField(blank=True, max_length=350, null=True, verbose_name='Additional Message')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelapplication', to='resolution.projectresolution', verbose_name='Application')),
            ],
        ),
    ]
