# Generated by Django 3.2.8 on 2022-09-24 22:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0047_applicationcancellation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationcancellation',
            options={'ordering': ('-created_at',), 'verbose_name': 'Proposal Approved', 'verbose_name_plural': 'Proposal Approved'},
        ),
        migrations.AddField(
            model_name='applicationcancellation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationcancellation',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified On'),
        ),
    ]
