# Generated by Django 3.2.8 on 2022-09-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0048_auto_20220924_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationcancellation',
            options={'ordering': ('-created_at',), 'verbose_name': 'Application Cancelled', 'verbose_name_plural': 'Application Cancelled'},
        ),
        migrations.AlterField(
            model_name='applicationcancellation',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('approved', 'Approved')], default='initiated', max_length=100, verbose_name='Status'),
        ),
    ]
