# Generated by Django 3.2.8 on 2022-09-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0049_auto_20220924_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcancellation',
            name='message',
            field=models.TextField(default='', max_length=500, verbose_name='Additional Message'),
            preserve_default=False,
        ),
    ]
