# Generated by Django 3.2.8 on 2022-09-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0050_alter_applicationcancellation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcancellation',
            name='cancel_type',
            field=models.CharField(choices=[('team_exceeded_deadline', '(1) Team Exceeded Deadline'), ('team_abandoned_work', '(2) Team Abandoned Work'), ('team_not_responding', '(3) Team not Responding to Chat'), ('team_is_abusive', '(4) Team is Abusive'), ('ordered_wrong_product', '(5) I Ordered Wrong Product'), ('different_product_delivered', '(6) A different product delivered')], default='team_exceeded_deadline', max_length=100, verbose_name='Issue Type'),
        ),
    ]
