# Generated by Django 3.2.8 on 2022-09-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0051_alter_applicationcancellation_cancel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcancellation',
            name='cancel_type',
            field=models.CharField(choices=[('team_exceeded_deadline', 'Team Exceeded Deadline'), ('team_abandoned_work', 'Team Abandoned Work'), ('team_not_responding', 'Team not Responding to Chat'), ('team_is_abusive', 'Team is Abusive'), ('ordered_wrong_product', 'I Ordered Wrong Product'), ('different_product_delivered', 'A different product delivered')], default='team_exceeded_deadline', max_length=100, verbose_name='Issue Type'),
        ),
    ]
