# Generated by Django 3.2.8 on 2022-09-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0052_alter_applicationcancellation_cancel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectresolution',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='ongoing', max_length=20, verbose_name='Status'),
        ),
    ]
