# Generated by Django 3.2.8 on 2022-09-25 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0053_alter_projectresolution_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_type', models.CharField(choices=[('team_exceeded_deadline', 'Team Exceeded Deadline'), ('team_abandoned_work', 'Team Abandoned Work'), ('team_not_responding', 'Team not Responding to Chat'), ('team_is_abusive', 'Team is Abusive'), ('ordered_wrong_product', 'I Ordered Wrong Product'), ('different_product_delivered', 'A different product delivered')], default='team_exceeded_deadline', max_length=100, verbose_name='Issue Type')),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('approved', 'Approved')], default='initiated', max_length=100, verbose_name='Status')),
                ('message', models.TextField(max_length=500, verbose_name='Additional Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified On')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelproposal', to='resolution.proposalresolution', verbose_name='Proposal')),
            ],
            options={
                'verbose_name': 'Proposal Cancelled',
                'verbose_name_plural': 'Proposal Cancelled',
                'ordering': ('-created_at',),
            },
        ),
    ]
