# Generated by Django 3.2.8 on 2022-09-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0054_proposalcancellation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalresolution',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='ongoing', max_length=20, verbose_name='Action Type'),
        ),
    ]
