# Generated by Django 3.2.8 on 2022-09-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0056_contractcancellation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractresolution',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='ongoing', max_length=20, verbose_name='Action Type'),
        ),
    ]
