# Generated by Django 3.2.8 on 2022-10-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0057_alter_contractresolution_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneclickresolution',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='ongoing', max_length=20, verbose_name='Action Type'),
        ),
    ]
