# Generated by Django 3.2.8 on 2022-10-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0059_oneclickcancellation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extcontractresolution',
            options={'ordering': ('-created_at',), 'verbose_name': 'Ext Contract Awarded', 'verbose_name_plural': 'Ext Contract Awarded'},
        ),
    ]
