name: Django Deployment

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3 python3-pip python3-venv nginx supervisor -y
      
    - name: Deploy code to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        key: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
        script: |
          cd /webapps/trosgate/trosgate_env
          source bin/activate
          git pull
          pip3 install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic
          sudo systemctl restart nginx
          sudo supervisorctl restart trosgate
